### ISSUE TITLE
Dark events rework

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#102]
Based on my experience, dark events seem to be kind of working, in that I have seen both strategic and tactical ones and I am getting missions to counter them. However, the following issues need to be addressed:

- Mixing of LW2 and WOTC (e.g. Chosen specific) DEs
- Differences in detection between tactical and strategic DEs. I was able to easily counter center mass which is almost impossible to counter in vanilla LW2
- Whether or not more than 3 DEs can be active or pending at the same time?
- Durations of DEs and whether the tactical ones would be permanent or not (for scaling enemies as in LW2)?
- The UI is messed up (see below)
![20190416122525_1](https://user-images.githubusercontent.com/15093261/56238196-c0c8bd80-6042-11e9-91b9-5f071fbcd0ab.jpg)

**Comment by yoshimo** [comment]
What is the problem of the first bullet point?

**Comment by ansabalirai** [comment]
No problem per se, just want to make sure that the WOTC dark events are classified correctly into tactical (permanent) and strategic (temporary) DEs, For instance. I don't think chosen having no weakness should be permanent.

**Comment by pledbrook** [comment]
Center Mass is a LW2 dark event using the old configuration. I'm not sure it's as impossible to detect as you think.

**Comment by pledbrook** [comment]
These are the WOTC dark events:
```

	DarkEvents.AddItem(CreateSignalJammingTemplate());
	DarkEvents.AddItem(CreateTheCollectorsTemplate());
	DarkEvents.AddItem(CreateStilettoRoundsTemplate());
	DarkEvents.AddItem(CreateLightningReflexesTemplate());
	DarkEvents.AddItem(CreateReturnFireTemplate());
	DarkEvents.AddItem(CreateBendingReedTemplate());
	DarkEvents.AddItem(CreateSealedArmorTemplate());
	DarkEvents.AddItem(CreateUndyingLoyaltyTemplate());
	DarkEvents.AddItem(CreateBarrierTemplate());
	DarkEvents.AddItem(CreateHighAlertTemplate());
	DarkEvents.AddItem(CreateDarkTowerTemplate());
	DarkEvents.AddItem(CreateLostWorldTemplate());
	DarkEvents.AddItem(CreateCounterattackEventTemplate());
	DarkEvents.AddItem(CreateCollateralDamageTemplate());
	DarkEvents.AddItem(CreateSpiderAndFlyTemplate());
	DarkEvents.AddItem(CreateLeftBehindTemplate());
	DarkEvents.AddItem(CreateGoneToGroundTemplate());
	DarkEvents.AddItem(CreateMadeWholeTemplate());
	DarkEvents.AddItem(CreateWildHuntTemplate());
	DarkEvents.AddItem(CreateLoyaltyAmongThievesAssassinTemplate());
	DarkEvents.AddItem(CreateLoyaltyAmongThievesHunterTemplate());
	DarkEvents.AddItem(CreateLoyaltyAmongThievesWarlockTemplate());
```
Which should we remove? High Alert and Undying Loyalty are prime candidates I think.

**Comment by DerAva** [comment]
Adding some comments to the event list below. Overall, in regards to Dark Events, a few things to consider:
- Additional DEs dillute the DE pool, so might delay unit upgrades (Tactical DEs)
- It should be considered if tactical DEs for upgrades for the new unit types should be added
- It should be considered which existing tactical DEs apply to new enemy types

DE List:

- Signal Jamming: Increases all scanning times for 6 weeks.  - POIs are rare and actual scanning times are mostly short, since you spend most of the time "intel-scanning" with the avenger.  -> REMOVE due to minimal impact
- Gone to Ground: Black Market is closed for 6 weeks.  - can STAY, but maybe nerf duration and if possible don't require re-scanning when it reappears.
- Stiletto Rounds: ADVENT gain special rounds that inflict "Bleeding" status. - overlap with Viper Rounds DE - REMOVE
- Undying Loyalty: ADVENT have a chance to be reanimated as Psi Zombies when they die.  - too harsh, REMOVE
- Barrier: Enemy Tech and Psionic Defense are doubled. - basically makes hacking impossible for a month, reduces rewards from missions. Bit nasty, but undecided on that one (maybe nerf impact?)
- ADVENT Sealed Armor: ADVENT become immune to fire, poison, acid and ice. - STAY
- Lightning Reflex: ADVENT Troopers have the Lightning Reflexes trait; that is, the first reaction shot against them each turn is guaranteed to miss.  - need to determine which "Troopers" it applies to. OW is main protection from Yellow Alert shots, so might get really nasty here. Undecided
- Collateral Damage: ADVENT troops carry more explosives.  - seems totally toothless (no enemy ever runs out of explosives as is), REMOVE
- High Alert: You no longer start missions concealed.  - too harsh, REMOVE
- Lost World: The Lost may appear in any missions.  - FUN, please STAY
- ADVENT Bending Reed: Stun Lancers have a chance to move after performing a melee attack.  - already exists as a Tactical DE (whirlwind) - REMOVE
- ADVENT Return Fire: Missed shots against ADVENT Officers and Priests will trigger return fire.  - STAY, maybe extend to more enemies?
- Dark Tower: XCOM soldiers suffer greater losses to Will in combat.  - undecided, depends on how the will/fatigue system is used in the end
- Counterattack: ADVENT units have a chance to enter overwatch upon being revealed.  - REMOVE - pointless with yellow/green alert actions
- Show of Force: The Aliens try to snuff out XCOM through brute strength, adding more enemies to every mission for a month.  - already exists - REMOVE new version
- Left Behind: All Covert Actions have a risk of a soldier being captured. - probably stay
- Spider and Fly: There is a risk of ambush on all Covert Actions. - probably stay

All Chosen related DEs can probably stay, but should get removed from the pool when all Chosen are dead (see: https://steamcommunity.com/sharedfiles/filedetails/?id=1126771111 )

**Comment by jmartinez989** [comment]
hmm I seem to be in the minority here but I really am not bothered too much but the Undying Loyalty DE. It is a bit annoying to have he enemies reanimate but did not hinder my campaign too much.

Also in the minority about high alert. I honestly don't mind it too much, gives me all the more reason to get lots of Shinobis and encourages better positioning for me. Definitely makes things more interesting. Also means that you will likely be less active in missions for that month.

Also regarding bending reed, it is best to remove it because it does something whirlwind doesn't and that is that it gives the stunlancers a permanent boost to mobility when they melee attack. Bending reed is bugged at the moment and whenever I see the Assassin she always gets her mobility up to almost 60 because of how long it takes to kill her and how many times she will attack with her sword. Other than that yes it is redundant.

**Comment by pledbrook** [comment]
@DerAva Thanks for listing those with descriptions of what they do. I'll remove the duplicates and minimally effective ones.

I don't have an opinion on most of the rest having never encountered them. I think if a dark event forces you to think more carefully about what missions to take, who to take on them, and how to play them, then we should consider retaining them. It kind of depends on how badly they hurt. The truth is, there isn't much play experience with LWOTC and these dark events.

So for High Alert and Undying Loyalty, how about I reduce the duration? Perhaps by half.

@jmartinez989 Hmmm...I'll have a look at the Bending Reed implementation to see if there's an obvious fix for it. Will also check on the workshop.

**Comment by pledbrook** [comment]
OK, so I'm disabling Bending Reed, Collateral Damage, Stiletto Rounds, and Signal Jamming. I have also implemented the fix for the Chosen DEs so that they aren't in the pool once all the Chosen are defeated.

Finally, I reduced the duration of High Alert and Undying Loyalty to 12-18 days (from 28). We'll need more playtesting to decide whether the numbers need changing or whether they should be removed entirely. To be honest, I think it's partly about players getting used to them and adjusting their play, and also fixing all the other things that make LWOTC campaigns a roller coaster right now.

Last thing: Bending Reed doesn't look like it's bugged. The way it's implemented implies that it absolutely should increase mobility on every attack. However, there is a configuration variable for it: `BENDINGREED_MOBILITY_INCREASE` in _XComGameData_SoldierSkills.ini_. It's currently set to 1.5 (as in 1.5 times the mobility stat on each attack). That could probably do with being reduced to 1.2 or even 1.1.

**Comment by pledbrook** [comment]
OK, so Bending Reed is definitely bugged, but will likely be fixed in the community highlander. I'll set the mobility multiplier to 1 for now to disable the mobility increase until the bug is fixed.

**Comment by pledbrook** [comment]
Bending Reed is fixed in [our fork of the community highlander](https://github.com/long-war-2/X2WOTCCommunityHighlander/commit/afe8e1d7540cc60eaa4a609f7232ff867267eb13) (thanks to @MrNiceUK)

**Comment by pledbrook** [comment]
Closing as most of the original points have been addressed. Please raise additional issues for any specific changes/bugs.
