### ISSUE TITLE
cover and advent damage

### ISSUE THREAD

**Issue by bobjjones** [long-war-2/lwotc#1026]
if advent is using mag weapons, how come advent troopers do so little damage. Xcom base assault rifles do more than advent mag weapons. That doesn't make a lot of sense to me. I think it would be better if advent weapons did more damage but had lower accuracy. A wide graze band makes the option even more appealing. Overall, making advent weapons fo proper mag tier damage would increase damage a lot. To compensate, xcom soldiers can get better dodge stats, advent accuracy can go down, or cover can be more effective. The player uses cover a lot more and better than advent, so increasing cover effectiveness would benefit the player and make up for the 8nceased damage when you do get hit.

**Comment by WaldoTheRanger** [comment]
I agree that advent should do a lot more damage, especially on legend.

The kind of comprehensive tweaks you're suggesting though would take a lot of work to balance properly, and might do better as a submod.

I would love to see such a mod, but I think just increasing damage such that advent does 1 more base damage than xcom on legend would be fine for now. maybe also reducing aim slightly to counter it. I could go without that though.

on rookie I'd be fine with the amount of damage they do in legend now, but legend needs to be a challenge.

I think for now my solution will be the equalized advent mod, and cover damage reduction. kinda scared about how that will affect the rest of the campaign, with advent tech upgrades and such (and generally conflicting with other balance decisions), but I'll also be playing with a bunch of extra gear mods (like jetpacks and molotovs and such) so it should cancel out.

**Comment by pledbrook** [comment]
The fundamental problem is that LW2/LWOTC heavily promote alpha striking and making ADVENT do more damage will just push the game further in that direction. That's on top of the game punishing the player quite hard for taking wounds, even light ones.

Dodge wouldn't help that much because it's an unreliable stat. Over the course of a campaign it has a strong effect, but mission to mission it doesn't protect from that much damage.

A rebalance of LWOTC would almost certainly use some form of damage mitigation from cover, but even then I'm not sure the enemies would be changed to deal more damage. Getting the damage number balanced is more important than thematic sense.

**Comment by WaldoTheRanger** [comment]
hmm fair enough.
I'll just play with my wacky mods then.

**Comment by WaldoTheRanger** [comment]
Well Idk actually.

You could at least make it a second wave option for damage values to be reverted to more like vanilla for people who want the extra challenge.

it just seems weird to make the enemies do little to no early game damage on the hardest difficulty.

**Comment by WaldoTheRanger** [comment]
also I'll probably have to make a separate issue for this, but any idea off the top of your head why I'm not getting the second wave options when I start a campaign? I have the mod enabled, and everything else works fine.

**Comment by WaldoTheRanger** [comment]
wait are advanced options and second wave different?
nevermind I'm an idiot.

**Comment by Grobobobo** [comment]
Working as intended.
