### ISSUE TITLE
Latest Update Borked Mod List?

### ISSUE THREAD

**Issue by jusomagna** [long-war-2/lwotc#1029]
So with the latest update to XCOM 2, they added it to a launcher for all the Firaxis games, but when I go to manage mods for XCOM 2 WOTC, Long War of the Chosen and X2WOTCCommunityHighlander don't show up. double and triple checked I reinstalled the mods correctly and it's not showing in the list. any fix/workaround?

**Comment by LandofMert** [comment]
yep, I'm in the same boat.  Longwar of the chosen mods are in Mod folder, but don't show up on Mod list.

**Comment by Bluemethod** [comment]
LWOTC seems to mostly work after this issue started except I noticed the red soldier stats are gone. Has anyone experienced this?

**Comment by zyxpsilon** [comment]
Same silly problems here!

**Comment by Leskit** [comment]
It initially worked for me, but i've been having a problem with recurrent crashing. Once my game crashed, I did the delete config folder data, verify game files thing, but then lwotc was gone. Someone on the steam forums suggested:
"go to C:\Program Files (x86)\Steam\steamapps\common\Xcom2\Binaries\Win64\Launcher then create a shortcut of ModLauncherWPF.exe I suggest to right click on the shortcut to pin it to the task bar then on the task bar right click on the icon , right click again then click propertys then in the target right at the end of .exe" type -noRedScreens -review then click ok"

I tried I got into my save game once, and then the game wouldn't even boot. Someone also suggested some alternative mod launcher menus but I didn't know their shorthand (AML?) It looks like an absolute mess on the steam forums.

**Comment by pardeki** [comment]
I have the same problem.

**Comment by q6161217** [comment]
I also have the same problem.

**Comment by LandofMert** [comment]
is there any word that Github will chance their Installation guide to give
us a new way to play?

**Comment by Charlie0309** [comment]
I had the same problems. The Highlander and LWOTC mod do not appear in the mod list. I am not using the alternative mod launcher thingy.

To get it working, I just reactived all of the other mods I was using (more or less... it is hard to tell as they appear in a completely different order). I was only using the recommended mods, plus a few ease of life mods (commanders choice, evac all, overwatch all, better info etc). Dont think I had anything modifying other aspects of gameplay.

Everything seems to work fine. I have played for a few hours over a couple of sessions. This is a late game save (just researched the shadow chamber stuff... although I have not gone on any of those missions). Just played a few generic missions (plus a liberate comm tower) Not come across a single problem... yet.

I did not delete the config folder. I am guessing if you do this it will trash your game, as it will pull the wrong config files without the LWOTC mod being active.

I must admit, this is my first playthrough of Xcom2 since it first came out, as I did not want to play LW2 without WOTC (and viceversa). I sunk a lot of hours over the lockdown, and I would have been very upset if I lost my progress, so I hope you can all salvage your games.

**Comment by JimmyInt3055** [comment]
> 
> 
> yep, I'm in the same boat. Longwar of the chosen mods are in Mod folder, but don't show up on Mod list.

Exactly the Same for me to.

**Comment by Leskit** [comment]
I don't know what changed, but the workaround suggested on Steam started working for me:

on the steam forums suggested:
"go to C:\Program Files (x86)\Steam\steamapps\common\Xcom2\Binaries\Win64\Launcher then create a shortcut of ModLauncherWPF.exe I suggest to right click on the shortcut to pin it to the task bar then on the task bar right click on the icon , right click again then click propertys then in the target right at the end of .exe" type -noRedScreens -review then click ok"

I'm still getting random crashes, but I was getting those when I started using the lwotc mod so I don't think they're related.

**Comment by LandofMert** [comment]
I installed the Alternate Mod Launcher to get past it.

**Comment by JimmyInt3055** [comment]
> 
> 
> I don't know what changed, but the workaround suggested on Steam started working for me:
> 
> on the steam forums suggested:
> "go to C:\Program Files (x86)\Steam\steamapps\common\Xcom2\Binaries\Win64\Launcher then create a shortcut of ModLauncherWPF.exe I suggest to right click on the shortcut to pin it to the task bar then on the task bar right click on the icon , right click again then click propertys then in the target right at the end of .exe" type -noRedScreens -review then click ok"
> 
> I'm still getting random crashes, but I was getting those when I started using the lwotc mod so I don't think they're related.

This solution works!!!!!

**Comment by JimmyInt3055** [comment]
What's with the red screen on loading? I have only lwotc, highlander, required and recommended mods loaded.

**Comment by Leskit** [comment]
I think it's because it's a dev mode, and the red screen tells you an error that is occurring. Right click on your shortcut, go to "shortcut", then in the target window, enter " -noRedScreens" _after_ the parentheses and that will stop the red screens from showing up. My target line looks like:
...\Launcher\ModLauncherWPF.exe" -noRedScreens

**Comment by Bluemethod** [comment]
When can we use the Steam launcher again? When LWOTC releases a new version? My current process when adding/removing mods is to boot up ModLauncherWPF, check all mods, main menu, exit, boot up Steam launcher, check all mods, then play the game. It gets tedious after a while. For some reason Alternate Mod Launcher breaks on me.

**Comment by JimmyInt3055** [comment]
In the middle of a mission I get intermintent black screen with icons available but cant see anything, on trying to shoot I see everthing but not for movement. Anyone know what is causing this?

**Comment by TheOtherNewJack** [comment]
> When can we use the Steam launcher again? When LWOTC releases a new version? My current process when adding/removing mods is to boot up ModLauncherWPF, check all mods, main menu, exit, boot up Steam launcher, check all mods, then play the game. It gets tedious after a while. For some reason Alternate Mod Launcher breaks on me.

Same here my man. It's terrible and not working. I'm not jumping through random suggestions. It's broken.

**Comment by Grobobobo** [comment]
The installation instructions have been adjusted.
