### ISSUE TITLE
New Screen on Mods doesn't show mods for long wor

### ISSUE THREAD

**Issue by Wolfe319** [long-war-2/lwotc#1044]
Long war was working before reload computer after hard drive crash.  Now the Long War doesn't show up on list of mods, 

![image](https://user-images.githubusercontent.com/65974355/82934969-5c24a580-9f5a-11ea-958d-3910583d5107.png)

I have done the extraction of files and still no luck any ideas. 

![image](https://user-images.githubusercontent.com/65974355/82935217-b0c82080-9f5a-11ea-840d-526b076dc5a8.png)

**Comment by AuroraHalsey** [comment]
Put the LWOTC folders in XCOM2/XComGame/Mods instead of in /r/XCOM2/XCom2-WarOfTheChosen/XComGame/Mods.

**Comment by Wolfe319** [comment]
Done that, now i have Mods available but still have New Game instead of Long War
![image](https://user-images.githubusercontent.com/65974355/82951600-7c159280-9f75-11ea-91ce-e75e2c01a3b2.png)

**Comment by AuroraHalsey** [comment]
Ok, I've been having the same problem for over an hour now. Finally fixed it.

Put it back in the **XCOM2/XComGame/Mods instead of in XCOM2/XCom2-WarOfTheChosen/XComGame/Mod**s folder.

Download the Alternative Mod Launcher
https://github.com/X2CommunityCore/xcom2-launcher

Follow AML set up instructions.
https://github.com/X2CommunityCore/xcom2-launcher/wiki/Getting-started

Make sure that the steam workshop and **XCOM2/XComGame/Mods instead of in XCOM2/XCom2-WarOfTheChosen/XComGame/Mods** folder are in the AML mod directories.

Refresh AML, enable all the mods you want, then launch WoTC from the AML.

**Comment by Wolfe319** [comment]
Do you know what happen?  Is this because of XCOM - Squad game?

**Comment by Wolfe319** [comment]
It seem that now i have performance issue as before i had no issue.

**Comment by AuroraHalsey** [comment]
I assume it's happening because of the new Firaxis launcher.

As for performance issues, the config deletion resets settings. Have you graphics settings been reset to maximum?

**Comment by Wolfe319** [comment]
yes, they were reset to max but i had already change them back after playing a normal game.   It is now just hangs and doesn't start now.  I have done the usual trouble shooting steps and restarted and close all other app in foreground and background.  No luck

**Comment by Wolfe319** [comment]
AuroraHalsey, just want to say thank you for your help and good health to you and yours...
