### ISSUE TITLE
And then... LWoTC suddenly doesn't show up at all

### ISSUE THREAD

**Issue by Silamandoran** [long-war-2/lwotc#1054]
First off, a huge shoutout to all the development and support teams for LWoTC. Some of my favorite humans, there. Taking a fantastic game and shooting it into a league of its own. Looking forward to supporting them however I can!!

I'd been rocking a campaign, got through liberating my first region and on a mission (intel reward, I think), it crashes as I fire a rocket. Greetings, desktop. Had one crash before, reloading the save worked fine then tho. No worries. But decided to verify integrity of game files anyways, see if it might stop this from happening again. 

3 files missing. Ok. Rebooted and ran the game again and LWoTC wasn't even showing up anymore - as if I hadn't been running LWoTC at all. Suspected maybe I blundered my way into having to reinstall the LWoTC mod by verifying integrity (??). Had been using Beta 3, downloaded and unpacked Beta 3.1. 

Now, Long War of the Chosen and the Community Highlander mods don't even show up on my mods list in the new menu. They are still in the  steam/steamapps/common/xcom2/xcom2-warofthechosen/xcomgame/mods  folder...  no idea how to proceed now, or if my save is salvageable. 

Countless thanks~

**Comment by Underratedt4co** [comment]
I have been trying to start a fresh long war of the chosen campaign (for the first time) and both 'Long War of the Chosen' and 'Community Highlander' mods didn't show up on my manage mods list either. I believe the issue is with the new mod manager ui (attached screenshot).

![error 1](https://user-images.githubusercontent.com/66368448/83638121-0603d200-a5ec-11ea-88a6-5c467725c4c0.PNG)

![error 2](https://user-images.githubusercontent.com/66368448/83638404-6dba1d00-a5ec-11ea-9f84-95307ebc83db.PNG)

![error 3](https://user-images.githubusercontent.com/66368448/83638412-71e63a80-a5ec-11ea-800b-106e56a72f7e.PNG)

Followed troubleshooting guide but it is out of date with the new mod manager. Attempted a work around to edit config defaultmods file to install the two mods manually with limited success. I could get lwotc and community highlander mods running but nothing else. When I loaded the game I got a red error stating the 4 necessary mods were missing and I could not get them to load manually.

Sadly I tried for a couple of days to play without the other 4 required mods but it made it unplayable. Had a bug where I would choose 6 soldiers for infiltration but then another 2-3 would be on the skyranger too, filled in from the roster. This made squad management impossible and messed with infiltration timers having stowaways, making the game too frustrating to continue.

**Comment by ansabalirai** [comment]
First thing I would suggest is to get AML installed and running. You can find instructions here: https://github.com/long-war-2/lwotc/wiki/New-Player-Resources

Also, consider joining the LWOTC discord here: https://discord.gg/vv5yJF9

**Comment by Underratedt4co** [comment]
Just ran it using the AML. Loaded perfectly first try. You are a life saver @ansabalirai <3

Might be worthwhile updating the troubleshooting guide/installation guide if the new mod manager makes the current instructions nonviable

**Comment by Silamandoran** [comment]
AML works like a charm. Grazie~

**Comment by TheOtherNewJack** [comment]
AML doesn't work for me and I don't think people should tout it as a "fix" anyway, it's a workaround for an issue that still exists and surely needs looking at.

**Comment by ansabalirai** [comment]
No one is "touting" it as a fix. Using AML is highly recommended, that is all. If you cannot get it to work, you should ask for help in LWOTC or modder's discord troubleshooting channel.

**Comment by TheOtherNewJack** [comment]
I have seen it described as a fix. I am right that it is a workaround. Stop arguing with me, this issue is still there, I don't even WANT to use AML. Fuck yourself and may your family get COVID.

**Comment by McTrevor79** [comment]
> I have seen it described as a fix. I am right that it is a workaround. Stop arguing with me, this issue is still there, I don't even WANT to use AML. Fuck yourself and may your family get COVID.

Seriously??

**Comment by Grobobobo** [comment]
The launcher change has been reflected in installation instructions.
