### ISSUE TITLE
Beta Strike needs to affect reinforcements timers

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#1060]
Title is self explantory. Its no fun if you are facing more enemies that you can kill (Since they will come faster than you can ever kill them) even before you get to the objective.

**Comment by curtnoel** [comment]
I would have to say I agree with this idea. The reinforcement mechanic is very obscure to me as a new long war player and I think something like this would help more people learn the ropes a little more, lets say, gently. Reinforcements counting down when they dont even know your there seems illogical(unless they can see the skyranger already in which case they would bring everything they got all at once-right?)

**Comment by GrouchPotato** [comment]
Just to throw in a couple of cents of opinion, possibly controversial but here's what I feel:

Yes, reinforcement timers do need to be extended for beta-strike, but only by a little. Part of the reason I'm playing beta-strike with long war is that it makes me think far more in terms of tactical objectives on certain mission types. If it's supplies you're after, you've got to focus on getting in and out with those supplies quickly because you're not going to survive if you try and kill everything on the way.

It makes you come up with new strategies - CC, distraction, hacking, doing things like claymoring a petrol station or car away from the squad to pull patrols in a different direction become far more important than racking up kills. Alternatively I might take only one or two stealth soldiers and do what I need to do without killing anything at all. Sometimes it's too much though and you need to decide early to abandon the mission, find a position where you can reasonably safely hunker down to evac out.

But sometimes it just gets a bit silly. You think you've managed to keep things under control and then, for example, you get dumped on by a load of super-tough vipers and you don't have enough CC available to keep them shut them down before they've pulled soldiers to certain death.

It also means there are a lot of missions I don't take on that I might otherwise give a go, as getting good infiltration becomes essential in most cases.

While all this is kind of cool in terms of needing to be a bit imaginative about battle strategy, another issue is that soldiers aren't getting as much XP/AP through the game. Perhaps this isn't too big a deal, as player power run-away has always been a thing in XCOM.

So I'm supporting the idea of extending the timers a bit, but I wouldn't go for simply doubling them. Perhaps *1.5 would be a good middle-ground.

Perhaps you could give the player choice here with a new Second Wave option, or tie it into the 'Double Mission Timers' option that's already there. Personally, I'd prefer the former.

_For background, I play on Commander with the LWOTC spec-ops classes mod and a couple of other non-op class mods that I've tweaked for LWOTC. I've also not yet reached end-game, but previous experience of LWOTC (well, XCOM in general) tells me that thing should get easier rather than harder._

**Comment by wdanny69** [comment]
this has been done

https://github.com/long-war-2/lwotc/commit/656caf83d5d99db5816c18dd2f940556b1bb2b9b
