### ISSUE TITLE
Consider range-based aim and damage balance

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#107]
I would like to see a buff to close range aim, for example +40 at point blank. On top of that, I think shotguns should perhaps be balanced around doing extra damage at close range, which is realistic. Then the bonus to crit chance would probably be removed. And slug shot could be modified to do close range damage at range. At the moment it's a bit weak, although everything is weak against lightning reflexes :wink:

**Comment by MagSigeasol** [comment]
I feel the aim bonus might make Xcom too strong. The aliens don't benefit from close range (and don't lose aim on distance), so it would be a straight-up buff to the player. Something on which some of the experienced legend playtesters might hold an opinion.

On the close range damage, shotguns are already plenty powerful,. If you proceed on close range damage (which, realistically, is the goal of the shotgun), you may want to fiddle with the assault tree given that extra damage + close and personal would be bonkers on a crit. Assault are already very strong early on, a damage increase would be easy GTS > assault training. 

Regarding close range aim benefits, the tactical weapon pack LMG does not have a close range aim bonus (just like the base game). An easy fix, but if people are using it would be worth having it scale similarly (and it would be great if the tactical weapon pack weapons were just like standard weapons and were more of a cosmetic choice than anything with unique weapon mods).

**Comment by pledbrook** [comment]
Wait, what? Enemy units don't have aim adjustment based on range? That can't be right, surely? I suggested increasing the aim bonus on the basis that both sides would benefit.

Thanks for the note about the TLP LMG. Are all of the TLP weapons based on new weapon templates?

**Comment by ansabalirai** [comment]
I am pretty sure enemies do get range bonuses. Maybe not as crazy as xcom with shotguns, but they do. Regarding damage, assault is balanced around getting perks for doing more damage (through more shots, more crit chance and even more damage (killer instinct), so fiddling with damage numbers can throw the balance out of whack and make some perks as must have (and must skip). 
This is similar to the graze mechanic discussion, where since it is not working in the current build, grazing fire is probably useless. I had no idea how much I relied on the graze band until it is disabled. I really hope it is at least included as an option, so people who are suckers for RNG can still enable it.

**Comment by SirMrMister** [comment]
I think most weapons should have a close range aim bonus only up to a point - say, 2.5 tiles. Closer than that and you get some slight aim penalty because asault rifles and such are a bit more cumbersome at very close range.

Only SMGs, sawed-off shotguns and autopistols should be immune to near-adjacency range penalties methinks. Normal shotguns can keep the extra damage from point blank range, but they are still long weapons and should suffer a but in aim.

**Comment by ansabalirai** [comment]
Just to clarify, cannons and sniper rifles have close range penalties in LW2 anyway. If SMGs, sawed offs and pistols are ok, it only leaves shotguns and assault rifles? To me, the bonus aim at close range for them seems reasonable. One of the issues with fiddling the range tables is people having to relearn the optimum ranges for all weapons. I know I had to manually TTC a number of times to find the optimum range for the cannon in LW2 (6 tiles I think). Add to that the fact that most T3 enemies have innate defense and defensive perks up the wazoo, I would vote for not fiddling the numbers too much at this stage. 
Just my two cents

**Comment by jmartinez989** [comment]
In LW2 the Aliens do in fact benefit from weapon ranges. It was only in vanilla that they did not get weapon ranges.

**Comment by MagSigeasol** [comment]
Oh, my bad, I honestly thought they did not. Not sure why I thought that, and might explain why I have been getting murdered through high cover in proximity to xenos.

Re: cannons, I checked again and the aim bonus / malus works like this:
Aim bonus per range square to enemy | -10 | -5 | 0 | 5 | 10 | 8 | 6 | 4 | 2 | 0 | (i.e. 5 squares from the enemy = 10 aim bonus).

The shotgun table is impressive, being | 60 | 45 | 30 | 15 | 8 | 4 | 0 | 0 | -4 | -8...
I would be cautious on amending the shotgun table given the close range bonus already provided.

Apologies for the incorrect statement above. Re: TLP weapons, I presume (I have not checked) it would be its own type of weapon with its own table (like the alien ruler DLC weapons).

**Comment by pledbrook** [comment]
The TLP weapons have their own templates, but they read the values from the vanilla weapon config. LW2 just changes those values, so the TLP weapons *should* behave the same as the vanilla ones. However, they may not be buildable and may have too few weapon attachment slots. Not sure what to do with that side of things.

**Comment by pledbrook** [comment]
As for having to look up optimum range, I would like to take a leaf from LWR's book and have more of this important information available in the UI somewhere.

**Comment by pledbrook** [comment]
Dropping this. Something that's more for LWOTC-R if anything.
