### ISSUE TITLE
Unable to continue main quest

### ISSUE THREAD

**Issue by RomashkinAndrew** [long-war-2/lwotc#1070]
I had two main quest objectives: to use skulljack on a codex and to complete mission from codex's
brain. I completed the first one, got the mission to complete avatar autopsy, but objective to to use skulljack on a codex remained. I completed the mission from codex's brain (but the objectve remaired), completed opened shadow projects, but now I can't move forward: I have 3 objectives: to use sculljack on the codex, complete mission from codex's brain and to complete avatar autopsy. But the only shadow project remained (avatar autopsy) is unavailable (it says I must complete all other shadow project), mission from codex's brain is no longer available on the map and I even can't use the sculljack on the codex.

The problem is that in the midgame I installed [[WotC] RW Fixed MidCampaign Language Changing](https://steamcommunity.com/sharedfiles/filedetails/?id=883407133) mod to change my language from russian to english. It might be a mod incompatibility issue (finished ojectives are stll displayed in russian), but I haven't found this mod in incompatible nor compatible ones. 

I am not sure if it's this mod, lwotc, or incompatibility problem, but if someone could recheck if that's the reason - it would be nice.

[save_AUTOSAVE- Campaign 4, Mission 137.zip](https://github.com/long-war-2/lwotc/files/4814554/save_AUTOSAVE-.Campaign.4.Mission.137.zip)

**Comment by copyrite** [comment]
Closing because this is already old. The suggested fix would have been to use the console command `forcecompleteobjective` anyway. See listed objectives under the Steam Community guide [XCOM 2:All console commands and IDs [WOTC]](https://steamcommunity.com/sharedfiles/filedetails/?id=2608547705), ignore the part where it says the command is for "missions" -- it's actually strictly for strategic objectives.
