### ISSUE TITLE
Officer abilities not shown on tactical map

### ISSUE THREAD

**Issue by CeyowenCt** [long-war-2/lwotc#109]
It has been a while since I've played LW2 so I don't recall exactly how the officer abilities work, but I have played 2 missions with an officer present and have not seen their abilities. One had OM and one had FF. The command range toggle appears and functions, and the leadership history window shows in the barracks.

**Comment by pledbrook** [comment]
I have an officer infiltrating on a mission, so I'll be able to check this and attach a save file if I can confirm.

**Comment by pledbrook** [comment]
Just went on a mission with an officer and they have Command and Oscar Mike as expected. You're definitely using alpha-2 with a separate X2WOTCCommunityHighlander? If so, make sure that there isn't some other highlander that might be causing issue. Also, clear out Config directory. As a last resort, remove `profile.bin` from your saves directory, although I would just move it somewhere safe so that you can restore it if it's not the problem.

**Comment by CeyowenCt** [comment]
Yes I've got alpha 2, your HL (and unless the launcher reactivated it, the
other community HL is inactive), and I think I cleared configs before I
started the campaign but I'll do it again.

**Comment by pledbrook** [comment]
Well, if you're still experiencing the problem, please attach a save.

**Comment by pledbrook** [comment]
Assuming this has been sorted.
