### ISSUE TITLE
Scale supply raids differently

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#11]
Supply raids were always hard to balance because the rewards for under infiltrating were so great. I propose that the rewards are reduced as infiltration level falls. This could either be done on a straightforward percentage basis (rewards = %infil * base rewards) or at discrete levels. For example:

 * 75-99% infiltration = 75% rewards
 * 50-74% infiltration = 50% rewards
 * 25-49% infiltration = 25% rewards
 * 0-24% infiltration = 0% rewards

It might also be worth scaling the number of enemies _down_ as well, since their corpses have intrinsic value and drop loot.

The justification for this would be that XCOM would be hitting a waypoint where supplies are congregating. At 0% infiltration, no supplies have actually reached that waypoint. As infiltration goes up, more supplies and their escorts arrive.

Note that I don't think over infiltration should have any effect on supply raids.

**Comment by pledbrook** [comment]
One thing to bear in mind is that successfully completing the supply currently reduces enemy strength (alert level) by one overall. This should probably be conditional on fully infiltrating the raid.

**Comment by ansabalirai** [comment]
I understand that the underinfiltration cheese should be addressed. That being said, I would suggest keeping the same behavior as in LW2, since command pods plus yellow alerts mean no one should be attempting low infiltration supply raids at all. WOTC generated maps for supply raid (1-2 I have seen so far) are also not very big, so squadsight cheesing is not really a reliable option.
In any case, reducing the enemy strength upon successful completion should always be applicable, since it is one of the few reliable ways of countering advent legions.
A slightly unrelated issue (I will create one separately for this) is that yellow alert does not seem to be working and the anti-Beagle maneuver instead is triggering most of the time. I am not sure if you specifically took a look at that, but it will have some deep seated impacts on raids, retals, etc.

**Comment by pledbrook** [comment]
People still do and successfully complete 0% or otherwise very low infiltration supply raids and consider it the way to beat the game.

An alternative is to scrap infiltration altogether and make Supply Raids instant response and rely on the fatigue mechanic to offset the loss of infiltration. This would make it far easier to balance around these missions as the rewards would be pretty consistent (although scaled by ADVENT strength).

**Comment by pledbrook** [comment]
I went for an alternative approach with the Underinfiltration sit reps.
