### ISSUE TITLE
Need to rebalance reapers (with suggestion)

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#110]
So in the current state of the game right now reapers are just too good. This is mainly because, as you would probably guess, their detection radius is only 1 which is pretty ridiculous. This alone already makes them pretty op but then add in their skills like silent assassin, remote start and their claymores and now you have a unit that can pretty much kill half the mop and stay stealthed (and in early game they can kill an entire pod of advent with claymore and retain stealth for the entire squad).

I think that reapers should be reworked so that they benefit more on the infiltration side than on the scouting side. My suggestions are below for how I think reapers should be balanced:
    - Make it so shadow no longer gives them a concealment radius of 1. Instead make it somewhere between rifle and smg.
    - To make up for their loss of 1 tile detection radius make them take up almost no time for infiltration. Essentially make them pretty much a free soldier to take on a mission where they barely, if at all, affect infiltration times.

The changes above should balance them out a bit because now they can't just be the ultimate scouts and you have to think a bit more about rushing them into a tile but also makes them useful for fielding a larger squad for infiltration.

**Comment by MagSigeasol** [comment]
I agree with the concealment bonus, but perhaps it could be an innate ghostwalker detection radius (i.e. still better than regular smg soldier, but still a shorter radius. 

I think there is a case for balancing all three of the heroes for the early game. They are just fantastic early on and, currently, it is easy to rush to get one of each in the first month.

**Comment by pledbrook** [comment]
I would just like to point out that Xwynns always considered Tradecraft to be an OP ability, even after several nerfs to it. And _that_ only reduced the infiltration time. It didn't eliminate it.

**Comment by pledbrook** [comment]
@MagSigeasol  Do you consider Skirmishers to be that great early game? They've always felt like the weakest faction soldier, but perhaps I just haven't had as much joy with Justice.

**Comment by GitWadeanthony** [comment]
Skirmishers are a little on the weak side early game and mid game mainly due to their weapon and one per mission perks while Templar and Reaper are a bit overpowered early game due to their perks so they avoid many issues caused by weak weapon choices. If you plan to use Skirmishers as a gun unit that gets in close a Ranger with an smg does it better mainly because of sawed off shotgun. Increasing the base bullpup 7 to 3-5 would be a nice start, 
Reflex is a waste of a perk as is- once per mission for 1 extra action point is too weak when you have leaders and (i assume it's changing) teamwork, Whiplash should have more charges or cool down based, don't think Reckoning needs a 5 turn cool down - maybe 3 turns,   

Eventually the Reaper's claymore will get outpaced by the amount of HP and Armor some units have but early game- it can wipe out a pod of advent- would nerfing it's damage from 3-5 make it a bit more fair?

I agree that giving Shadow Ghostwalker's detection range instead because 1 tile is insane. They also miss the laser weapon rank which hurts their damage. I would move their Shrapnel perk up two ranks and Needle perk down one rank. Remote start is really good on urban maps but if it appears to be too good how about giving it a long cool down like 5 -6 turns?

Templar are very good but still comes with risk of pulling other pods and to reliability kill sectiods you still need as least 1 focus, I kind of put them on the same level as Sword perk only Shinobi.

**Comment by MagSigeasol** [comment]
Skirmisher's are certainly not as strong as a reaper for early game missions, and I think it would be fair to say they are the weakest of the three at the beginning, but that is only because the other two bring utility that is easier to be effectively utilised. Momentum makes the templar an improvement over the sword-specced shinobi just because it can strike and find relatively safe cover (where available). Parry is also a surprisingly good upgrade to force attacks away from your other troops and minimise wounds. 

A skirmisher can be great though - for example, I used grapple to get to a flanking position up high, used justice to pull a priest out of high cover, and that priest was then in range of other units to flank-shot kill, or I could follow up with the bullpup close range for the kill. It is a skirmisher's ability to get a lot done in one turn that gives them their value, but that requires the right situation. I usually take the grenade perk on the first upgrade so that I can be a ghetto rapid deployment grenadier. 

Reapers, on the other hand, just wait for a pod to be on top of a car = 12 damage see you later.  For example, I had a rescue mission, two advent by a car, two advent + sectoid on roof. Reaper claymore (upgraded) on roof, remote start on car = two dead advent. Squad still concealed. Ranger shoots claymore, blows massive hole in roof, kills all three. Still have 4 soldiers with full turn, 1 with a shot remaining, and a concealed uber-stealth reaper. Extremely light mission became Extremely ez mode.

**Comment by ansabalirai** [comment]
Since this is becoming a bit of an extended discussion, I will chip in with my 2 cents as well. If the eventual plan is to integrate the Chosen, it might be worth considering doing that first to see how the overall picture in a typical mission with the chosen and one or more faction soldiers looks like before making balance changes. One of the reasons the faction soldiers were considered OP apart from their abilities were their bonuses vs specific Chosen. If Chosen are not in the cards, it is perfectly ok to me to just remove the faction classes altogether and have a simpler LW2 experience.
In any case, I like the suggestion made by @jmartinez989 to give reapers an increased detection range and buff their infiltration times instead. Essentially, have them start with covert and/or ghostwalker. 
As much as Xwynns liked to hate on tradecraft being an OP perk, note that it was mostly before patch 1.4/1.5 came out, which heavily nerfed the 1/2 man squad shenanigans people were pulling. Currently, there is little difference in infiltration times between 2 and 4 man squads and tradecraft certainly does not make an appreciable difference in that case. So, I do not think it is quite as OP. 
Skirmishers are certainly quite weak early game, to the point that I have one sitting as a haven advisor, since he is basically a cheap imitation of a ranger and cannot even get the laser version of the gun instead, so his damage is abysmal and he does not have sapper anyway, so grenades are almost useless. Their aim progression is also shit btw

**Comment by Grognerd** [comment]
I love remote start and would hate to see it get overly nerfed ... but logically, a massive deadly explosion going off in the AO should have consequences. All enemy pods on the map going to yellow alert, at the very least.

**Comment by SirMrMister** [comment]
Regarding Reflex - there is a mod that buffs it by removing the once per mission clause, but I feel that is a bit too much maybe both remove said clause AND give it a cooldown so it cannot be used two turns in a row?

**Comment by torma** [comment]
In my opinion @jmartinez989 points out most relevant issues in his initial post but not many of them were addressed. The suggestions are fine but I have a different idea on how to make the reaper part of the lw2 experience. Which is reaper base abilities need to be nerfed some others reworked.
I realize this can be a loot of work for any developer so I'll try to build up this post from stages. The developers can decide which of them they would like to or can implement and also split this one into several tickets in the long run.

1. Integrate a mods like Shadow Concealment Nerf:
https://steamcommunity.com/sharedfiles/filedetails/?id=1397449502
I loved this one in my vanilla campaign.
This nerfs shadow concealment like this:
 - Reapers ending their turn flanked by an active enemy will get revealed
 - Non movement actions made from half cover or less add +10% to the chanse of breaking out from shadow
I have not seen any other mods which nerf reapers but I'm just one gamer.

2. nerf Shadow, nerf reaper triggered Explosions, ability tweaks
In terms of alert remote start and claymore explosions should have the same radius as a rocket explosion and should alert pods withing the radius of the explosion.
Any explosions caused by the reaper should reveal the reaper, destroy corpses and break concealment for the squad, I think this should effect:
 - Shooting a claymore, making it explode
 - Using remote start
Distraction - should trigger if the reaper is not the one shooting the claymore and the claymore kills at least one unit.
Homing mine - should add + 10% to the chance of breaking out from shadow concealment and should trigger a reveal roll.
Remote start should have a 6 turn cooldown. I assume this could be used to put the reaper back into shadow concealment under the right conditions. Explosive objects may be chained with triggering a Claymore explosion. This combo would kill most enemies including late game enemies (excluding bosses, rulers, choosen). I assume a reaper with the Distraction talent would be put back into shadow concealment. If this is not the case then I think 4 turn cooldown is enough.

Shadow Concealment rework (in addition to the changes in "Shadow Concealment Nerf"):
 - Shadow should be an ability at Master Sergeant not baseline.
 - Not killing a target should always reveal the reaper.
 - Detection radius should be increased but I think this could be the same as a shinobi with an smg
 - Shadow should not increase mobility. Instead the reaper should have the same mobility as any soldier with an smg.
Needle - +2 Armor Piercing (without requiring shadow)

All these may be too much. I would also like to hear other peoples opinion.
What I see right now in my test campaign on legend is that under the right conditions a reaper can just solo most missions. I don't want a soldier to be picked for every mission above all others. So the goal is to find some sort of a niche for the reaper. It should be the glass cannon version of a shinobi. I'm fine with scouting, pick off weakened targets and do heavy damage even blasting away bosses once a mission. 

3. Rework class tree, more ability tweaks
Holes need to be filled in and choices need to be added. While one also needs to think about class fantasy.
The WOTC reaper is a spy, a saboteur and a hitman at the same time. I'll start from trying to require to choose from these three but mostly reusing existing abilities.
Going down the Stealth tree should make the reaper an exceptional scout while also retaining some ability to shoot from concealment.
Saboteur and Marksman trees sacrifice some of the scouting potential for more damage. Saboteur focusing on explosives and Marksman focusing on the vector rifle.

| Rank | Stealth | Saboteur | Marksman |
| --- | --- | --- | --- |
| Squaddie | | Claymore | |
| Lance Corporal | Ghostwalker | Boosted Cores | Blood Trail |
| Corporal | Sting | Shrapnel | Death Dealer |
| Sergeant | Covert | Highlands | Needle |
| Staff Sergeant | Target Definition | Biggest Booms | Soul Harvest |
| Tech Sergeant | Silent Killer | Remote Start | Bring 'Em On |
| Gunnery Sergeant | Tradecraft | Homing Mine | Banish |
| Master Sergeant | Shadow | Distraction | Annihilate |

I would also like to apply the ability changes from the previous section for: Distraction, Homing mine, Remote start, Needle.
Target Definition may be too strong on non timed missions. If that's the case then it should be replaced with something else.
Death Dealer: +2 critical damage. (This is not the same ability as the one replacing Executioner mentioned in this bug: https://github.com/long-war-2/lwotc/issues/77 but I like the name and the icon so might as well use them)
Biggest Booms: Should also apply to Claymore and Remote start.
Boosted Cores: Should also apply to Claymore and Remote start.
Infiltration: I think it could be removed as a GTS ability. I find this one of the most useless abilities in the game.
Sting: Should be reworked to have 4 turn cooldown and 4 charges. 

4. Assets and upgrades
Laser and coil version of the vector rifle need to be created. Base damage and loudness between the smg and rifle. I assume with the same damage as the bullpup mentioned in this issue https://github.com/long-war-2/lwotc/issues/105 should be fine but without the range penalty and it could be as quiet as the smg.
The weapon bonuses could be the standard ones. The laser version should have an aim bonus, the coil one point of armor piercing and the plasma should apply rupture on hit.
Prerequisites same as for the sniper rifle.
Two new tiers for the Claymore adding +1 shredding and +2 damage. Prerequisites could be the muton autopsy and muton elite autopsy.

**Comment by captainbeastfeast** [comment]
Maybe just change it so that they can't shadow conceal by default unless  you have 100% infiltration on missions. I suppose you could activate the ability to get around this after the battle starts but this would use up a charge of the ability.

I don't think reaper should be nerfed too excessively, he is a hero class unit and is meant to be a cut above the rest, especially in the early game.

I would recommend making the chosen more of a challenge in the final release.

**Comment by tunbridgep** [comment]
I would also reduce/remove the RNG from the "attack and maybe stay concealed" ability, since sometimes it's useless and sometime's it's OP.

I would change it to "your first attack is always going to retain concealment, your second attack is always going to break it"

I would also make shooting claymores lose concealment for the whole squad always

But I think much better people than me are handling this, and this thread has been a really good read.

The other issues I think are that the Reaper is kinda bad and the Templar is basically a better version of the Psi Ops, making PsiOps really seem like second-class units IMO.

**Comment by pledbrook** [comment]
Implemented in [this commit](https://github.com/long-war-2/lwotc/commit/95b36ab529bb79b8e991343385a14abddde70999). There will probably be further balancing work on all the faction soldiers in the future.
