### ISSUE TITLE
No extraction zone on my second mission

### ISSUE THREAD

**Issue by Voidfeather** [long-war-2/lwotc#1123]
After completing a mission to get some supplies, my squad was force to die facing the endless hordes of reinforcements, because Firebrand decided to abandon them.

No extraction zone spawned, and there was no option to evac on the panel. I removed a mod "instant avenger screens" after starting the campaign because it's not compatible. Would that cause any issues?

[save_Save 12.zip](https://github.com/long-war-2/lwotc/files/5249706/save_Save.12.zip)

**Comment by charly1r** [comment]
If you are playing with a controller gamepad R3 does not work to call the Skyranger it has been reported here:
https://github.com/long-war-2/lwotc/issues/962
Since I am using steam link and streaming from my PC, I have to restart the game in keyboard mode and press P
to call the skyranger, save the game then continue using my gamepad.
(don't forget to call the skyranger way early before you accomplish your goal or you have to wait several turns waiting for it and possibly get attacked by reinforcements)
