### ISSUE TITLE
Develop goals for game balance

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#116]
There are several ongoing discussions around balance at the moment, but there are no overarching goals to help guide those. We should decide on how we want the game to play so that compatible decisions can be made on the finer-grained balance questions.

## Replayability

I think we should have just a few areas that we focus on for replay value:

 * Soldiers - these should be as distinctive as possible between campaigns, via classes, perks and stats. Particularly perks.
 * Tech paths - make different routes through the tech tree distinctive and comparable in power/effectiveness. Breakthroughs or inspiration can be used to nudge players down one path or another.
 * Factions? - there is the potential for faction bonuses to change the dynamic of both the strategy and tactical game. Making it so that new factions can only be contacted after an extended period of time means that the player would be limited to one factions bonuses for a significant portion of the game, which would change how the game plays.

## Strategy

 * Try to eliminate bad RNG as a campaign ender.

    The campaigns are long, so losing one late because of a MSGT squad wipe due to really bad luck is very painful. Such a loss should hurt, but not end the campaign. Nor should one or two mistakes cost the campaign either.

 * Make strong strategic objectives more interesting and more challenging to obtain (but not via RNG)

    The obvious example is Avatar progress reduction. Finding a facility lead in LW2 was very RNG based. That just doesn't seem fun or interesting. Rather, it should be easier to get a lead, but that would set off a chain of missions that would eventually end up at the facility itself.

    Discovering Chosen weaknesses could be another objective. Weakening ADVENT strength. Countering Dark Events. These things should be less RNG based so that players have more control over them, but they should be challenging to achieve.

 * Allow for a quick end game

    It can be frustrating to reach a point at which you can end the game, but you have to wait for resources, missions, tech, etc. before you can finish it. There shouldn't be too many constraints on reaching the Fortress.

## Tactical

 * Introduce variety in how missions are played - for example, stealth vs blow everything up; fast and aggressive vs more chess like
 * Make all soldiers as relevant, but as distinctive as possible
 * Encourage close quarters combat, but make it high risk/high reward
 * Try to ensure that there aren't just one or two dominant strategies (e.g. drawing pods into overwatch traps = high damage, low risk)

**Comment by ansabalirai** [comment]
Impressive write-up, but I think it would be good to link the goals to examples of concrete steps that can be taken to achieve the goals. Here goes my attempt:

Replayability:

- LW2 class perks are quite varied and lead to an interesting mix, especially with not created equally and hidden potential. So, we don't really need to change them. For faction soldiers, different from the discussion on balancing their existing perks, it would be interesting to see if they can get the three perks on each tree as LW2 classes. I have not played much modded WOTC, but I imagine people have come up with modded versions of those classes which might be worth looking at. However, given that you are not going to have many of these classes anyway, it might not be worth the effort.
- Breakthroughs offer very interesting decisions when it comes to tech tree progression. I have had experience delaying lasers to get breakthrough on weapon damage to great effect, which has actually changed the way I pick perks for different classes. Some balancing might be needed to avoid OP combinations, but in the current stage, with the increases number of research projects in LW2, simply reducing the frequency of triggering breakthroughs and (to a lesser extent) inspirations can be sufficient. 
- This is a big one. If the plan is to not have factions being available for contact from the very get go, one way could be to link them to specific regions like the Chosen, so you can only make contact once you make contact with a specific region where their HQ is.

Strategy
- I am not sure how this can be avoided fully, given how soldier progression works. Due to doom clock constantly ticking and FL cooldown of 15 days, you do not really have much time to train up more than a few squads simultaneously. For instance, I have been experimenting with a bigger starting barracks (50 rather than 20 rookies) to set up multiple squads from the get go, but it is not really viable due to thinning out XP gains. These are the two levers that can at least mitigate the issue you mentioned, but at the same time, losing a MSgt squad does not necessarily mean the campaign is finished (See Ronar's liberator's play-through on L/I on Twitch as an example)
- I guess the idea of linking important strategic missions to specific chains (like the liberation chains) is interesting, but would likely require a lot of work. Facility leads can indeed be made somewhat easier to obtain, given that you still need to make contact with the region and infiltrate it. Regarding dark events, by design some of them were purposely made hard/impossible to detect to ensure enemies scaled in terms of perks as well as raw survivability. If we want to revert to WOTC behavior where you are notified of all ongoing ones and you get chance to counter one of them each month, it would leave it less to RNG (but seems somehow less appealing)
- But the name implies it has to be grueling and long :P . Anyway, I think this can be done similar to dynamic war in LW1, with increased resources from missions (might not work given the non-sweep nature of most missions) and increased XP progression in general. A related aspect is that supply raids and troop columns currently  give relatively little resources and you basically have to rely on selling corpses to get the economy going (but I think this has been raised as a separate issue)

Tactical:
- This would depend on a complete overhaul of the way the tactical game plays, i.e. mission objectives, timers, xcom vs enemy healths, concealment, redefining perks to discourage alpha-striking,  just to name a few. I would suggest to focus on incorporating all essential features first and have people play a few campaigns to the very end on different difficulties (I am not even sure if someone is playing this on Legend) and report on what they think can be adjusted. Otherwise, based on what I have seen happen to groups that worked on porting LW2 to WOTC, things can quickly get out of hand.

**Comment by SirMrMister** [comment]
Replayability:

- I mentionied this in another thread, and I'll repeat it here: I think [Chosen Reward Variety](https://steamcommunity.com/sharedfiles/filedetails/?id=1619292810) would increase replayability and combat always purposely rushing towards a specific chosen because its item reward is the most OP or the player's favorite. By introducing four new unique item rewards for each chosen (grenade, utility, armor, misc) and making it so defeating a chosen gives you a research that upon completion gives the player only two of the six possible items, chosen randomly on a per-campaign basis, defeating the same chosen will change things for the player in different ways each campaign. The individual probabilities for each item can be configured in the mod's files. Also note that yes, some items are too OP in the mod, but I'm trying to sell you the concept or idea of the mod rather than its specific implementation - the specific items should be rebalanced according to LWOTC's standards.

Tactical:

-Allow for alien rulers to appear alongside chosen. My vision for the alien rulers is for them to not be allied/subjected to ADVENT, but rather they be indomitable creatures that fight both against you for what Vahlen did to them and against ADVENT to liberate their species. I want to see them less as an enemy and more as a force of nature, a battlefield element that can affect both you and the aliens. Granting them permanent Frienzied debuff might allow for that, but I dunno if it would let the other aliens soot at them.

**Comment by GitWadeanthony** [comment]
**Replayability**

For factions, I prefer they can only be contacted after rescuing one of their soldiers via a jailbreak/extract VIP in a new region. No time restriction besides how long you take to leave your starting region, limiting the player to one faction for a significant portion of the game is just not enjoyable to me. You could make it so influence is related to liberation status of the region so people actually push to liberate more regions and keep them. 

First faction + soldier – you get at the beginning of the game, first mission.

Can’t do any covert ops with other factions till you rescue one of their soldiers from VIP extraction or jailbreak which makes contact with the faction.

Recruit more faction soldier via Covet ops missions (Personnel Extraction and recruit) which spawn a mission to rescue them or assist them in a mission such as hack a workstation etc– this has a 100% chance to be a faction soldier for that faction or via jailbreaks/vip extraction which is a random chance (besides the first one to make contact with them).  Don’t limit amount like vanilla wotc does which is 2 for starting faction and 1 for other faction until they die. 
Maybe this mod/code needs to be added - [Recruit Multiple Heroes From All  ](https://steamcommunity.com/sharedfiles/filedetails/?id=1126788564&searchtext=recruit)

Completing up to Liberation 3 or 4(network tower) in their region makes influence go from low > mid
Completing Liberation 5- Facility Assault or defeating their chosen(just doing Lib 5 could be too easy): mid > high


**Strategy**

This may not fall into directly into eliminating bad RNG but Invasions are awful in current lw2- it’s like lw1 base defense with non stop reinforcements, for the average player it’s a nightmare. Maybe I just suck at them but after completing or failing one, I generally have no desire to play that save file anymore. 

My proposal is the allow “Find a Lead” to detect invasion supply raids and allow the covert ops mission “Intel Collection” to “Find a lead” instead of getting Intel (or make it percentage based betweer find a lead or intel) and maybe increase the time it takes to complete. 


**Tactical**

On making all soldiers relevant, I had some thoughts on improving the faction soldiers with what is already in the game/code- I already voiced some of these in other post. 

- 3 slots for weapon attachments for the faction weapons 
- buffing their weapons min/max damage and armor stats to match xcom soldiers since they can’t use heavy and light exo armor after all.

- Adding Pistols to Templar weapon pool. (I’m mild on this, it’s basically a secondary weapon for them after all)

- Adding Shotgun and SMG to Skirmishers weapon pool.
- Giving Bullpup +1 mobility and minor reduction in detection range, not as much as SMG.

- Giving Vektor Riles/Reapers limited Squadsight (+5 tile vision range over non sniper rifles) like the 
- Marksman rifle in LW1 while keeping it weaker then the Sniper rifle. 
- Maybe giving Sharpshooters access to Vektor rifles if we give them limited squadsight as another option.

- Maybe adding a Laser/Coil weapon or all the faction soldiers. But this will require someone that can make the models for the weapons. 

Giving the faction soldiers 3 rows of perks and another rank to match Xcom soldiers by just adding in their possible abilities to the empty slots.

Reapers get Squadsight (squaddie), Holo-Targeting, Shredder, Kill Zone, Deadeye and Tactical Rigging. This leaves them with 3 (9 total) empty perks that can be added. 

Templars get 8 possible perks and only 5 empty perks slots. Bladestorm, Reaper, Lightning Hands, Quickdraw, Sustain, Fortress, Shadowstep, Faceoff. If the goal is to not just make them a better sword Shinboi, I would remove either or both Bladestorm and Reaper from the pool. No idea what to do with the Pistol perks- not just for Templar but for other soldiers.

Skirmishers have 7 empty perk slots and 5 possible perks. Return Fire, Tactical Rigging, Lightning Reflexes (at a later rank so they don’t overlap with Assualt too much), Volatile Mix, Saturation Fire (with Bullpup only). 
Also I feel some perk have to be changed due to being too weak to contest with other perks. 
- Reflex – Once per mission is extremely bad, change to once per turn (or put it on a cooldown)
- Interrupt – Another once per mission ability, would put on a cooldown. Doesn’t complete with Combat Presence or Retribution as is.
- Whiplash – I would give 1-2 extra charges at the very least or have it improve with weapon tech and make it a guarantee hit. To compare Combat protocol gets better with tech/doesn’t miss/2 Charges, Capacitor Discharge 1 charge/doesn’t miss/large AoE).  
- If Judgment is anything like LW2 Sparks Intimidate, it needs a buff in percentage. Decent tank perk otherwise to combo with Reflex and Return Fire. 

 GTS perks- I dislike WoTC moving all of these to resistance orders.
All the combat training for the long war soldiers were removed and I feel these could be removed too or added to their normal perks ranks.
Parkour: 5% chance for a free move after the first move of the turn. I would just rework this into something else.
Infiltration: Increases hacking by +25. ADVENT security towers cannot see this unit when it is concealed.  Maybe too strong of a buff with Sahdow. 
Mentally Awake: Start every mission with 1 Focus.

Readd 
Vulture, Wetwork, integrated warfare, vengeance, lightning strike. 

Vulture is too important for getting weapon attachments and money in the early game before you complete your first lib chain. 

If you want to keep these as resistance orders, I have no idea what to put here, can't just have Tactical Infiltrations and Large Unit Infiltrations as the only GTS perks. Maybe move some of the Continent Bonus mainly Armed to the Teeth and Wired here.

**Comment by pledbrook** [comment]
@GitWadeanthony:

> No time restriction besides how long you take to leave your starting region, limiting the player to one faction for a significant portion of the game is just not enjoyable to me.

Is there a particular facet of the factions that you want access to, such as the soldiers? Or everything (soldiers, covert actions, resistance orders, scannable HQs)?

**Comment by pledbrook** [comment]
To everyone: I would prefer to keep this as a discussion about the balance goals, rather than particular balance ideas. I understand why Rai gave some examples, but this isn't an issue/thread for balance suggestions. If you have a balance idea, please add it to an existing issue that covers that topic (for example the one on Reapers) or simply raise a new issue. Thanks!

**Comment by GitWadeanthony** [comment]
> 
> 
> @GitWadeanthony:
> 
> > No time restriction besides how long you take to leave your starting region, limiting the player to one faction for a significant portion of the game is just not enjoyable to me.
> 
> Is there a particular facet of the factions that you want access to, such as the soldiers? Or everything (soldiers, covert actions, resistance orders, scannable HQs)?

Mainly the Soldiers themselves, if it's anything like leveling up Sparks and Psi soldiers mid game they feel like dead weight that you have to carry unless they start at say SSGT and then it becomes a question of why waste resources (armor/weapons/influence)  on them when you can just improve the troops you already have. I don't mind resistance orders/base scanning/covert actions being locked out due to time- story wise you would have to proof yourself to them before they allow you access to their resources and gameplay wise they can tip the scale into win more or getting super soldiers. 

If you want to go PSI you may be sacrificing getting mag weapons/armor earlier - so if you want to get all the faction soldiers asap you could be sacrificing finishing a LIB chain and/or expanding too quickly and not have enough intel to boost supply raids etc. And the resistance factions don't have to be right next door either, they can be two region over or you need to find a lead that tells you were they are located before you can make contact. 

Maybe it's just me and some people don't mind that, but locking out the factions for significant portion of the game with how long LW2 can go on for plus the many times people will restart the campaign doesn't sound enjoyable.

**Comment by Kazanir** [comment]
I think one great goal to add here would be finding ways to integrate the WOTC mechanics with the LW2 strategic layer in some fashion. I'll make these suggestions (or refine them) in the various specific topics for each, but some examples of what I mean might be:

- Chosen entering the game or increasing the frequency of their appearance based on various strategic events, like liberating a region, advancing the plot, or completing a Golden Path mission.
- Chosen might also affect haven/rebel/Advent behavior in various ways, boosting the likelihood of missions in a specific region they are active in, hindering Haven jobs, or modifying the alert/vigilance/force levels available to Advent in the region. Could also depend on the success/failure of the Chosen's efforts against you (i.e. killing/capturing your dudes or causing failed missions.)
- Similarly, the faction havens could also be paced in their discovery this way, making contact only at certain points in the game's story and requiring you to establish a haven in their region before they are able to work with XCOM. (Probably want to take care to make sure each faction isn't unreachably distant from the starting zone...)
- Covert ops being allowed to choose a region to target and affecting different haven behaviors depending on the faction, e.g. Reapers might prevent retaliation efforts in the region for a month, Templar might boost rebel XP gain or the stats of recruited rookies, and Skirmishers might expose the list of mission types that are off cooldown/possible in a given region.
- Less-potent versions of these ideas as either covops or resistance orders -- something like bonuses to supply column detection, drawing Advent's attention (increasing vigilance), or blocking reinforcements to the region for a period of time, etc.

The overall idea is to bring the two systems together here; for me the LW2 strategic layer is one of the most rewarding parts of the mod and I think providing the WOTC mechanics with ways to push and pull on those levers would be pretty cool and give players a lot of flexibility in how they want to play the game.
