### ISSUE TITLE
FRA Translation

### ISSUE THREAD

**Issue by Savancosinus** [long-war-2/lwotc#1216]
Hi!
I'm currently translating this mod in french, and I've a few questions.

1 - Dedication_LW 
_"ignore reaction fire for the rest of the turn"_
Does it mean that you trigger the shots but it's always a failure, or you don't trigger the shots at all?

2 - Weapon Handling
_<Bullet/> Point Blank does not affect the aim penalty from Snap Shot.<br/>"_
"Weapon Handling" instead of "Point Blank"?

3 -Corpsman
Can't see in the perk tree (classdata). And I need some context to translate it. What is this?

4 - Shooting Sharp
_"Your ranged attacks gain +<Ability:SS_PIERCE/> penetration against units in cover."_
Penetration = Armor-piercing?

I'm really impressed: a lot of things were improved and I really love what you've done here. Congrats.

**Comment by pledbrook** [comment]
1. Works the same as Shadow Step, i.e. it does not trigger overwatch shots
2. The text should say "Weapon Handling" in place of "Point Blank" (it has been [fixed in GitHub](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Localization/XComGame.int#L5932))
3. It apparently (according to English localisation) grants a free medikit charge - I'm currently trying to find out exactly how it interacts with the medikit item
4. Yes. I plan to update the English localisation to say "pierce" rather than "penetration"

**Comment by Savancosinus** [comment]
thx!

**Comment by Savancosinus** [comment]
2 more questions, and that should be good.

1 - ChosenKeen
Does that mean that soldiers never die when the Chosen is present? Seems weird at first glance... Do I miss something?

2 - Parkour vs Parkour_LW
Should I delete the old override of Parkour? Why did you add a new version of an already existing perk? (Just curious)

**Comment by pledbrook** [comment]
1. Yes, any soldier that reaches 0 health will bleed out rather than die if a Chosen is present, regardless of overkill damage
2. LW tends to add a new variant of the ability in cases where the behaviour changes substantially from vanilla; I do this so that other mods built around the old behaviour still work as expected when they use that vanilla ability. Yes, please remove the old translation override for 'Parkour'.
3. Yes, you're correct. There were too many changes for me to catch all of the errors :smile:
4. Mayhem, not MayhemBonuses. It's not a big deal as the latter is never visible to players. However, that made me realise I had added a duplicate entry.

**Comment by Savancosinus** [comment]
Lol, my question should be uncleared.
_Yes, you're correct. There were too many changes for me to catch all of the errors smile_
I would like to know if the shot triggers at the start of the enemy's turn, OR at the end of the enemy's turn. Maybe have you read "at the start of the end"? :)
If it's at the end of the turn, does the shot triggers even if the target is not visible anymore?

**Comment by pledbrook** [comment]
Ah. I thought you were commenting on the grammar error ("enemies turn") since you mentioned "enemy's turn".

From Grobobobo:
> lead the target shot triggers whenever the target attempts to do something on their turn
e.g. when the target moves or shoots or tries Mindspin.

**Comment by Savancosinus** [comment]
One last thing: the translation is done, but I can't create banches on GitHub. Last time, I forked the project, but it wans't a good idea...

Modop:
> git clone [url]
> git add *
> git commit -m "done"
> git push --set-upstream origin update-translation-fra-v22_3

I entered my credentials, but I've got an error.
_fatal: unable to access 'https://github.com/long-war-2/lwotc.git/': The requested URL returned error: 403_
Do I need to request access? Is there an other way to push my code?

**Comment by pledbrook** [comment]
Which repo did you clone? You need to clone your fork, not this repository.

**Comment by Savancosinus** [comment]
Oh, I see. 
_This branch is 293 commits behind long-war-2:master._ 
How can I update my branch with your changes?

**Comment by pledbrook** [comment]
```
> git remote add upstream <long-war-2 url> 
```
Then switch to your `master` branch if you're not already on it and do:
```
> git pull upstream master --ff-only
```
The `--ff-only` (fast forward only) will fail if your `master` isn't in sync with upstream. It's a safety check.

Do make sure to always make changes on a different branch from `master`. This allows you to easily keep `master` in sync with the long-war-2 repository as it is basically a mirror of it.

**Comment by Savancosinus** [comment]
Oh merveilleux, it's working! Thx a lot Pledbrook!!! :smile:

**Comment by Savancosinus** [comment]
BTW, I'll also correct some lines in the int files (Ex: Mayhem 20% -> 25%).

**Comment by pledbrook** [comment]
I've already fixed that one and pushed it to the repo. ANyway, I'm going to close this now as it's not an issue.
