### ISSUE TITLE
Advent sentries overwatch instead of ready for anything

### ISSUE THREAD

**Issue by kdports** [long-war-2/lwotc#125]
Since Advent Sentries have ready for anything, they should be able to shoot, and then overwatch. However, on Gatecrasher the sentry I was facing overwatched right away, despite him having a target to shoot at with more than 0% aim

**Comment by Ronar1** [comment]
This isn't completely a bug since the tier 2 and 3 guardian and sentinel have covering fire which doesn't proc from ready for anything. Also sentries with 1 ammo may opt to OW instead of shoot as a viable choice, but it should definitely be a balance concern for tier 1 sentries to not ow if they already have 2 or more ammo.

**Comment by pledbrook** [comment]
Most M1 sentries I've seen use Ready for Anything. This would have to be consistent behaviour for me to consider as a bug. If you're really concerned, attach a save file and I may take a look at some point. But it wouldn't be a priority.

**Comment by ansabalirai** [comment]
Agree that this does not seem like a bug per se. IIRC, there is some randomness when it comes to triggering passive abilities, but it does not seem connected to the this mod.

**Comment by pledbrook** [comment]
It looks like the Sentry doesn't have any special logic based on the fact that it has Ready For Anything. I'm pretty sure you're seeing the same behaviour as in original LW2. However, we may want to consider changing the behaviour tree for Sentries.

**Comment by pledbrook** [comment]
I haven't seen anything that concerns me about Sentry behaviour, so closing this.
