### ISSUE TITLE
Highlighted hp for damage preview should display minimum damage for gun, not maximum

### ISSUE THREAD

**Issue by Ronar1** [long-war-2/lwotc#126]
When you're picking a target for a shot, the hp that glows shouldn't be the max damage roll a gun can do, but rather the minimum.

**Comment by MajorEvil** [comment]
In response to this, there are mods out there other than LWOTC in steam that allready do this. I have play-tested these mods with the current version of LWOTC Alpha 2.0 and they are 100% stable: Namely Additional Icons, Extended Infomation for WOTC, and Show More Buff Details. Because of this, I don't think this should be an issue that needs to be looked at and patched in any way at all. If you download those mods from steam and then install them manually like I did, you should be fine.

**Comment by pledbrook** [comment]
Extended Information crashes the game on Mac unfortunately. I was hoping to make it a dependency, but not with that issue.

**Comment by SirMrMister** [comment]
Personally I think these UI enhancements should be left for after the campaign is moreorless fully working, useful as they are. I'm still of the opinion of integrating rather than dependencies (due to how most of them are incompatible with each other), specially because doing so as early as possible would mean testers who really like them can keep testing without having to semi-compromise their feedback by using mods other than LWOTC (regardless of how stable they presumably are).

**Comment by pledbrook** [comment]
Extended Information does this, so one can always rely on that mod for this behaviour. Will remove the milestone for now.

**Comment by pledbrook** [comment]
Probably won't end up doing this without a highlander change. May revisit if enough people want it.
