### ISSUE TITLE
Game Hangs on start up with mods

### ISSUE THREAD

**Issue by 321nick** [long-war-2/lwotc#1274]
Running LWOTC with just whats required from the AML works fine. Running it with modjam and some additional mods has it hang on start up indefinitely, not using any CPU.  i did all the installation instructions, ie verify files, delete configs in mydocuments/mygames etc, and running LWOTC aloen works fine. but running it with other stuff causes it too not start up

Heres my mod list: 
[dumb LWOTC modlist.txt](https://github.com/long-war-2/lwotc/files/6215089/dumb.LWOTC.modlist.txt)

And heres my launch.log: 
[Launch.log](https://github.com/long-war-2/lwotc/files/6215090/Launch.log)

**Comment by 321nick** [comment]
Even only enabling mods that are on Kirukas LWOTC Modjam collection (well, the one by SGT hobo that kiruka links on the workshop page) the game still fails too launch. i can run LWOTC too the main menue and see the Long War button, if i run it alone, but even LWOTC modjam roster collection just dont work for me. i dont get it.

**Comment by pledbrook** [comment]
This could be because of Rocket Launchers 2.0 (not necessarily that mod's fault, it's just LWOTC and it have some issues). One thing you could try is to go into RL 2.0's *XComRockets.ini* config file and make sure that any `create_rocket_XXX=` line is set to `false` for everything saying Thermobaric or Plasma Ejector.

Let us know if that helps.

**Comment by pledbrook** [comment]
Reopen this if it's still a problem with beta 4, but I'm pretty sure this is fixed.
