### ISSUE TITLE
Models appearing on squares away from where they actually are.

### ISSUE THREAD

**Issue by The13Inquisitor** [long-war-2/lwotc#128]

**Comment by The13Inquisitor** [comment]
Had this crop up twice now:

First time, an activated Drone just kept going off out of the playable mission area after a missed overwatch while it's actual location was right in front of the squad.

The second time, a load after a crash resulted in a Sentinel appearing to in front of a Templar, while it was across on the other side of the structure from them.

**Comment by jmartinez989** [comment]
Had this happen as well. Had a mech whos model was way at the back of the map but my template could charge them. I reloaded the game and it was now behind us on the opposite end of the map.

This seemed to happen sometimes in vanilla LW2 as well.

**Comment by MajorEvil** [comment]
although this could be an issue with long war, it has been known to happen with any other mods as well. such as a better advent for example. That's the risk everyone must take when installing any mod, because a mod to any game can still cause bugs due to the fact you are modding the core files of the game. Correct me if I am wrong, but I am not sure if this is something that can be easily fixed.

**Comment by The13Inquisitor** [comment]
First time I've had it happen and I've played a lot of vanilla LW2.

**Comment by pledbrook** [comment]
My impression is that it's more common than it was in original LW2. You're right in that it's almost certainly not easy to fix. It might be possible if I get a save file from before the start of the alien turn that actually reproduces it.

**Comment by pledbrook** [comment]
I'm giving up on this as an issue. I think it's just a base-game problem that is more prevalent in LWOTC. Perhaps something like a race condition is the source or some other threading issue.
