### ISSUE TITLE
Assassin Too OP

### ISSUE THREAD

**Issue by ctm98** [long-war-2/lwotc#1283]
There was a warning regarding updating that even though the strengths would be removed from the pool, chosen that already gained them would keep them, which is why updating on existing campaigns was not recommended. Regardless, this is outdated.

_Originally posted by @Grobobobo in https://github.com/long-war-2/lwotc/issues/1282#issuecomment-814871061_

In response to the above, ive never had a previous version than the most recent and only got the game and started a campaign a week ago. Could this be a bug that the assassin is still regaining health and ridiculously over powered? The other chosen aren’t so bad but she is a squad wiper every time

**Comment by Grobobobo** [comment]
Does she either have the soulstealer or the regeneration strength? What version do you consider "most recent"?

**Comment by ctm98** [comment]
I have been ignoring the retaliation missions in her area as of late but I believe it is the soulstealer one - re-gaining five health every round. The version I have is the dev build 23.1.

**Comment by Grobobobo** [comment]
> The version I have is the dev build 23.1.
There were 2 releases since then, dev 24 and dev 25. she gets changed a bit in dev 24, and the most recent version is dev 25.
https://www.reddit.com/r/LWotC/comments/lrph7d/unofficial_lwotc_dev_build_24_now_available/
https://www.reddit.com/r/LWotC/comments/m3m33t/lwotc_dev_build_241_now_available/
https://www.reddit.com/r/LWotC/comments/mfndpz/lwotc_dev_build_25_now_available/

Can I close the issue now?

**Comment by ctm98** [comment]
Thanks I will give the new version a try will I need to start a new campaign? Can close, sorry about that

**Comment by Grobobobo** [comment]
Starting a new campaign is recommended, yes.
