### ISSUE TITLE
Priests (and other WOTC enemies in general) do not seem to be using special abilities

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#129]
It seems priests only seem to shoot and are now aware of their special abilities. I imagine the same can be applicable in general for other WOTC units (i.e. not part of LW2 list of enemies)

**Comment by pledbrook** [comment]
@tracktwo Does anything spring to mind? Do the new enemy types need to be added to some pod manager configuration?

**Comment by pledbrook** [comment]
Actually, I think I worked out that I need to add the new unit types to AIJobs. Can't remember the details, though.

**Comment by MajorEvil** [comment]
I had this happen recently as well in an episode I just uploaded to YT. I will post the link here with a timestamp when able so that everybody can see what happened.

As you will be able to see when I post the link here, while the turns are constantly passing with the Priest active, all he did was shoot every single time. Normally, in game, priests tend to use either stasis or mind control first. Forcing the player to deal with the priest or deal with the Mind controlled guy, or face the consequences.

I can see an improvement opportunity though to the priest A.I however while we are on subject. For example, I could see that the priests could be made so that their actions more randomised. Also, if there is a flanking opportunity for the priest to take, it would make sense for the priest to do that instaid of a mind control/stasis every time. Would make the priest more interesting and harder to deal with.

**Comment by tracktwo** [comment]
These behaviours are not necessarily job related, it could just be the default BT for priests is incorrect somehow. There are some logging facilities for AI, more than one IIRC. You can unsuppress a bunch of them with the "Unsuppress" console command, grep the wotc game configs for "Suppress" to find the list of categories and look for anything with "AI" in it to unsuppress. You should then get more detailed info in the log about what the priest is doing. IIRC there was also a debug console command that would show you the previous AI decisions in an on-screen UI but I forget what it is, you might be able to find it by looking through the `exec` functions for anything with "AI" or "BT" in it.

If all they do is move and shoot it sounds like somehow their BT is being replaced with a generic one instead of a priest-specific one that knows about their special abilities they should attempt. With the debug commands or logs you should be able to see what nodes it is considering, and that may help to identify either a problem with the tree itself or maybe some conditions governing the use of the special abilities are always failing.
