### ISSUE TITLE
Bleeding unit on Ambush can return to roster alive

### ISSUE THREAD

**Issue by NilchEi** [long-war-2/lwotc#1304]
On ambush mission, I just let the covert operatives bleedout then evac'd to verify some reports about units returning from Ambush missions when they shouldn't.

When both covert operatives were bleeding out, both of them properly died as expected after evac.

So when only one of covert operatives were bleeding out, I teleported the other remaining covert operative to evac. The mission report says 1 soldier died, but when I went to the barracks the soldier that had been left behind was still alive, albeit gravely wounded.

Therefore there does seem to be some condition that allows knocked-out soldier to survive on Ambush missions. Maybe when one of covert operatives successfully evac, the game treats the other covert operatives as extracted as well regardless of their status? That's what my testing above seems to suggest at first glance.

I have attached my savefile here. AmbushGeoscape is savefile before doing Ambush mission, AmbushTactical is a save where there's one soldier bleeding out and all other soldiers are on evac zone, and AmbushAfter is save after evac from AmbushTactical showing that bleeding-out soldier is still on the roster.

[AmbushSaves.zip](https://github.com/long-war-2/lwotc/files/6454128/AmbushSaves.zip)

**Comment by pledbrook** [comment]
The problem was that the Covert Escape mission was configured as having a triad objective. I don't know how WOTC treats triad objectives, but LW2/LWOTC treats them as body recovery (like Network Tower) but without enemy corpse retrieval. So LWOTC was recovering the bleeding-out soldier when the triad objective (extract one covert operative) was completed.

Solution is to mark the objective as non-triad.
