### ISSUE TITLE
Templar Changes

### ISSUE THREAD

**Issue by pupujuku73** [long-war-2/lwotc#1310]
I'm writing to give my thumbs down to the Templar changes.

The work being done on LWOTC is for the most part awesome, and makes sense, but the recent changes have me perplexed.  The Templar has been fundamentally changed to a tank class, removing some real cool things like deflect, reflect and parry.  I'm not sure what to do with the class now... are they supposed to sit out in the open and take all the hits?  A couple of Muton blasts will still finish them anyway, despite the seemingly clunky perks like 'padding'.  What's the point of 'Momentum' if cover is meaningless? And do we really want the entire squad grouping up together for low cover... that just screams for an enemy rocket or grenade.  There is already a class that does this anyway: The Spark.

I know the coding for the shield took a lot of work, and the shield could be useful in certain circumstances.  Why not create a whole new class to use it?  With all the changes being made, is there any rule that says that there can only be the original 8 LW classes?   Narratively speaking, it's kind of silly that the psionically-obsessed Templars would resort to lugging around an ugly sheet of metal anyway.

Adding a secondary slot to the Templar wasn't necessary but it is interesting.  I'm currently playing with a Templar using throwing knives as a Secondary weapon.  What I think would be an interesting  creation for a secondary weapon would be a Psionic grenade or proximity mine, which cause a Psionic Rift effect (ala the Codex) or a Void Rift effect (Psi-Op).

As someone who is a huge fan of the game, and the work you are doing, I though it important that I share my thoughts.   Big thanks to all you guys for all your hard work!

**Comment by pledbrook** [comment]
The Templar rework was done because we were unsatisfied with how it worked and the fact that the melee build wasn't distinctive enough from a sword-oriented Shinobi. Plus the autopistol felt like a waste of a slot, particularly with all the other classes getting a pistol slot.

Parry was situationally (but not uncommonly) over powered since it blocked all damage, including from explosives. And because it blocks all damage, it scales insanely well into the late game. Deflect was strong, but not particularly interesting as a passive and pretty unreliable. There's no real engagement from the player other than hoping that the Templar manages to deflect a shot. Reflect is in a similar boat.

One of the fundamental problems was with how Templars interact with focus. Vigilance was just too strong and picked for every build. It demonstrated that having a reliable source of focus generation was important in making the class more interesting to use rather than just a Rend bot, but it granted focus too easily with no decision making required on the part of the player.

The rework balances things out. There are still ways to scale the Templar's melee damage through Apotheosis, Amplify and Concentration for example, but it's also much more viable to mix this up with spells and tanking. In general, the rework has opened up more avenues of how to play the class.

> are they supposed to sit out in the open and take all the hits? 

They can tank more damage than the average soldier, but that doesn't mean you can ignore positioning or fail to control/kill sufficient enemies if you activate a whole bunch of them at once.

> What's the point of 'Momentum' if cover is meaningless?

Because repositioning after an attack is strong, whether it's to get behind high cover (Templars can take cover in the current iteration), move next to another enemy for a Bladestorm attack, or to protect an otherwise vulnerable squad mate.

> And do we really want the entire squad grouping up together for low cover... that just screams for an enemy rocket or grenade

This is actually a common strategy when combined with Formidable and/or Incoming. It's very strong. The Templar gets Fortress if I remember correctly.

> There is already a class that does this anyway: The Spark.

There are definitely some similarities between the two in terms of tanking, but I'm not sure why one class having tank capabilities precludes another one from having them. A Templar is still a melee-focused spell caster, which a SPARK is not. Neither is really a dedicated tank class unless you build the SPARKs in a very specific way with Sacrifice.

Anyway, we recognise that not everyone is going to like the faction soldier reworks, but that's just the nature of this kind of work. Where you may like the old-style Templar, we see significant problems and a lack of engaging mechanics (stuff that requires decision making) and diversity of builds.

I'm going to close this issue because it's not something that can actually be resolved. You'll still be able to comment on it, but I encourage you to offer feedback on the [LWOTC subreddit](https://www.reddit.com/r/LWotC/), which is a more suitable forum for such discussions.
