### ISSUE TITLE
FRA - UTF-8

### ISSUE THREAD

**Issue by Savancosinus** [long-war-2/lwotc#1328]
Hi,
@pledbrook - Could you revert the encoding for FRA files?
We need to keep "UCS-2 LE BOM" to display special characters correctly (é, è, à, etc.).

**Comment by pledbrook** [comment]
UTF-8 supports all characters in the Unicode Character Set. UTF-16 is *not* required for é, etc.

**Comment by pledbrook** [comment]
If you're running into an issue with UTF-8, I'm happy to do what I can to help. But I don't want to change the encoding away from UTF-8 unless there's a good reason.

**Comment by Savancosinus** [comment]
I have an issue. Encoding does'nt work properly. :(
Notepad++ -> Encoding --> UTF-8.
I think we already had this issue few months ago.

**Comment by pledbrook** [comment]
In what way does it not work properly? This is Notepad++ with a .fra localised file open with UTF-8:

![image](https://user-images.githubusercontent.com/19075/121676887-17a87100-caad-11eb-8202-1d975e94ab5b.png)

The accents work fine. I'm wondering what's different for you.

**Comment by robojumper** [comment]
So the facts are:

* Localization files on GitHub and thus in the local project repository clones must be UTF-8. These are text files, and git only properly handles UTF-8 encoded text.
* Localization files in the `XComGame/Mods/LongWarOfTheChosen/Localization` built project must be UTF-16. The game can only handle ASCII and UTF-16 encodings.
* As part of the build process, the build tool must convert localization files from UTF-8 to UTF-16.

This works entirely fine if changes to localization are made in the project and the project is subsequently built, before launching the game. I suspect @Savancosinus may be copying the files from the project to `XComGame/Mods/LongWarOfTheChosen/Localization`, editing them there and copying them back to the project submit the changes to GitHub in order to skip the build times.

**Comment by pledbrook** [comment]
@Savancosinus Can you confirm whether robojumper is correct in his assessment, please? If you want to copy the localisation files directly into the installed mod, then it's probably best to manually convert them to UTF-16 (UCS-2 LE) in Notepad++ and then convert them back to UTF-8 when you're ready to submit the changes in GitHub. Alternatively, submit them as UTF-16 and I will perform the conversion back to UTF-8 myself.

**Comment by Savancosinus** [comment]
I can confirm. ^^

Thx!

________________________________
De : Peter Ledbrook ***@***.***>
Envoyé : samedi 12 juin 2021 14:46
À : long-war-2/lwotc ***@***.***>
Cc : Savancosinus ***@***.***>; Mention ***@***.***>
Objet : Re: [long-war-2/lwotc] FRA - UTF-8 (#1328)


@Savancosinus<https://github.com/Savancosinus> Can you confirm whether robojumper is correct in his assessment, please? If you want to copy the localisation files directly into the installed mod, then it's probably best to manually convert them to UTF-16 (UCS-2 LE) in Notepad++ and then convert them back to UTF-8 when you're ready to submit the changes in GitHub. Alternatively, submit them as UTF-16 and I will perform the conversion back to UTF-8 myself.

**Comment by Savancosinus** [comment]
Closed.
