### ISSUE TITLE
Cannot infiltrate alien facility

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#139]
[save_FacilityInfiltrate.zip](https://github.com/long-war-2/lwotc/files/3126251/save_FacilityInfiltrate.zip)
It looks like there is a problem with trying to infiltrate an alien facility. If you uncover an alien facility and then try to infiltrate it there is no way to check the infiltration status on it, the label for the infiltration status never shows up. When you click on the facility again it brings up the "Assualt Facility" menu again acting as if it does not have a squad infiltrating it. If you send another squad to infiltrate while one is already there then it will just give you the option to abort the first attempted infiltration.

Attached my save file of this.

**Comment by pledbrook** [comment]
So the problem here is that the Geoscape icon for facilities is of type `UIStrategyMapItem_AlienNetworkComponent`, whereas all the of the other mission sites are represented by `UIStrategyMapItem_Mission`, which we override with `UIStrategyMapItem_Mission_LW` ([see _XComEngine.ini_](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Config/XComEngine.ini#L42)).

The only solution I can think of based on my limited knowledge is the following:

 1. Create a `UIStrategyMapItem_AlienNetworkComponent_LW` class that extends the vanilla version
 2. Set up a ModClassOverride for this in _XComEngine.ini_
 3. Factor out the method implementations of `UIStrategyMapItem_Mission_LW` into a separate, reusable class. You might need to put implement the shared logic as static methods. I don't know. You certainly can't put them in a shared super-class.
 4. Add the set of methods defined in `UIStrategyMapItem_Mission_LW` to `UIStrategyMapItem_AlienNetworkComponent_LW` and have the two sets of methods (one in each class) use the shared implementations.

It sounds like it should be fairly straightforward, but I'm sure the devil is in the detail.

**Comment by jmartinez989** [comment]
Ok this actually gives me a lot to work with. I'll see how much progress I can make with this.

**Comment by jmartinez989** [comment]
Ok so I got it to the point where this is almost working as would be expected. I can now send a squad to infiltrate and the progress bar shows up with the infiltration percentage. Once it is at 100 percent I can start infiltration and mission starts without a problem and plays like how an alien facility normally would.

Can place x-4 charge and leave and complete mission. The only thing that is left is that when the mission is done there is no notification that avatar project progress has been reduced (the amount of avatar project is reduced by the number of doom pips the facility had).

**Comment by pledbrook** [comment]
@jmartinez989 Can we count this as fixed now?

**Comment by jmartinez989** [comment]
Yeah. I'll work on the issue of the game not displaying the animation message of the doom the facility had being removed from the avatar project.
