### ISSUE TITLE
Infilatration Time does not update properly

### ISSUE THREAD

**Issue by tonideleo** [long-war-2/lwotc#1390]
Version: Dev Build 27.3

Updated Issue: This was actually a similar issue to #383 and #303. Squad selection is not saved and I always end up with more soldiers in the mission. That's the reason the infiltration time is wrong.

Initial Issue:
Whenever I remove a soldier from my mission, the infiltration time doesn't update properly. To make it change, I have to click on add a soldier and then cancel the action. Only in that way the infiltration time updates. It happened a couple times already I was supposed to infiltrate more than 100% and ended up being below 80%.

**Comment by pledbrook** [comment]
Can you clarify which infiltration time you mean? I just tested the Squad Select screen and removing individual soldiers updates the displayed infiltration time just fine. Clear Squad does not, but it's not a big deal because you need to add at least one soldier, at which point the infiltration time gets updated properly.

**Comment by Tedster59** [comment]
cleaning up some old issues so closing.
