### ISSUE TITLE
Integrate XCom Scamper

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#14]
This works really well in Long War Rebalance and allows for a faster tactical game. It might be necessary to reduce the mobility for the free action, though. Not sure if that's possible.

**Comment by SirMrMister** [comment]
Keep in mind that LWR's integrated XCOM Scamper synergizes with LWR's integrated chain pod activation (for non-LWR players: Alien pods are also activated if they see the activation of another pod you activated directly; also at the end of alien turn any pod with LoS of an activated alien will also activate).

This chained activation is what prevents you from abusing the XCOM scamper by activating a pod, scamper, activating another pod, scampering again, ad nauseum to cross unlikely distances in a single turn, as after activating one pod it's very unlikely there'll be any other unactivated pod in scamper distance.

So I wouldn't worry about the XCOM scamper mobility and instead would consider if it's interesting to implement the chained pod activation (it works wonders in LWR, but I understand that XCOM2 might be a very different beast, and with the extra moddability it might be worth to consider it on a per-alien-type basis; e.g. Lost don't chain-activate).

**Comment by pledbrook** [comment]
Good point, and I should have mentioned it. Thinking about it, switching enemies to yellow alert might be a good compromise that avoids rebalancing all the pods for missions, which chain activation would entail.

To be honest, I'm not sure how open to abuse XCOM scamper would be for LW2 missions, even without the proposed changes to activation. Especially if scamper distance is reduced to half an action.

**Comment by SirMrMister** [comment]
Yeah, it seems like a good compromise would be to place in yellow alert any pods that see another pod's activation.

Regarding the scamper itself, I think that unlike in LWR here we take into account purposeful pod activation - that is, if we were going by LWR rules, then you could purposely throw a grenade from concealment into an inactive pod, activate it, and get a scamper to retreat the grenadier. That doesn't sound right to me. Out-of-concealment overwatch ambushes would be mitigated by the fact that in LWR overwatching soldiers don't get to scamper (even if they spend all their reaction fire before the alien scamper ends), but that doesn't seem enough.

I think that if XCOM scamper were to be implemented in XCOM2, then it should only be given when an action activates an alien that wasn't visible before taking that action, if that's possible to code. If not, then I'm okay with keeping it as in LWR but with reduced mobility. And this time making sure that Run n Gun cannot be activated after being granted a scamper move, and that someone who activated Run n Gun and moved two actions but didn't shoot yet before being granted scamper can choose wether to shoot OR scamper, but not scamper and shoot.

**Comment by BlackRose39** [comment]
I took a look at the scamper in the original lw, and it does look interesting. If we do implement it, I would make it so it has (doesn't have to be all of them).

- Provides a movement only action point
- Provides a reduced mobility (but this could be tricky since it would affect the other remaining action points, such as if you only took a blue move to reveal, would the second move be affected? My thought is that if someone used their last action to reveal enemies, they would get a free movement action at a reduced mobility (or not). If they still have action points remaining, do not give them anything.)
- Only activate ONCE per turn (Or when concealment is broken?)
- Regarding the grenadier abuse as mentioned, I think both the reduced mobility and enemy taking offensive actions depending on their alert would counter that. The enemies, esp. MECS, may going into overwatch, discouraging that extra movement. 

In addition, a slow, careful approach is still desirable. You wouldn't have the full movement range to get into any cover if a soldier goes out into the open.

If you want, there's more user discussions here.
https://www.reddit.com/r/Xcom/comments/8pys9e/lw_rebalance_v1183_new_feature_xcom_scamper_on/

Also, here's a mod for WOTC that gives scamper here:
https://steamcommunity.com/sharedfiles/filedetails/?id=1628518894

Of particular note is that the scamper mobility is penalized 60%, and is not granted if for example, a wall gets blown up by the grenadier as well as options to ONLY allow scamper given to the soldier who revealed the pod.

**Comment by pledbrook** [comment]
Unlikely to happen in classic LWOTC.
