### ISSUE TITLE
Apex predator broken

### ISSUE THREAD

**Issue by KrzepkiSzpinak** [long-war-2/lwotc#1402]
Hi, 

when apex predator triggers for my sharpshooter ( usually when opening at a pod ) the whole pod just freezes and I don't mean panicked units, mechanical as well ( not sure if only for the duration of potential panic ). Even if there are no organic enemies, crit seems to trigger that odd behaviour. It doesn't happen every time though, I am trying to figure out the conditions. 

Edit: Can't reproduce it, couple of missions in a row and it seems ok so might have been non related glich

Edit 2: Ok it happened again - it seems that the trigger by sharpshooter when none of my soldiers are in visual range DOESN'T activate the pod which freezes for the whole duration of panic (not panicked units as well). After panic ends, the pod moves but shooting at it when no units are in visual range still doesn't activate it.

Dev build 27.3

BR

**Comment by pledbrook** [comment]
Please reopen with a reproducible example if you encounter this with LWOTC 1.0. I suspect this is either down to the scamper bug (which has been fixed) or somehow you're hitting the vanilla bug where pods don't activate if you damage them from out of line of sight. That seems unlikely, though, since you need vision on the pod to shoot them with a Sharpshooter.
