### ISSUE TITLE
Is estat_will (will stat) increase supposed to stop at LCPL?

### ISSUE THREAD

**Issue by 0xStarcat** [long-war-2/lwotc#1409]
Hi, 

I'm pretty new to this mod and noticed none of my soldiers got any will increases when they reached CPL. I also promoted them all to MSGT with the `LevelUpBarracks` cheat and nobody saw any will stat increaes. 

 I went digging through the [config/XComClassData.ini](https://github.com/long-war-2/lwotc/blob/1b0f994e2673c99ebf3dc7fce5890d58ebfbd5bf/LongWarOfTheChosen/Config/XComClassData.ini) file where these things are usually configured and saw that indeed all of the will increases are set to 0 like this:

```
(StatType=eStat_Will,StatAmount=0)
```

There's no `RandStatAmount` or `CapStatAmount` to handle randomization in any of the rules, nor is there a `GlobalStatProgression` in any of the ability templates to handle this globally for a class. I also had someone tell me on [discord](https://discord.com/channels/590853492084572170/590853806175158272/875218417702019102) that having a low will at MSGT and no increases at promotion was normal for them. I'm by no means familiar with XCom modding (just a good googler) and as I mentioned I'm pretty new  to this mod, so I wanted to raise this issue and ask if having no will stat increases beyond CPL was a bug or intended behavior? 

It seems to me like you'd want higher will as you level up, particularly as some perks like Judgement say "higher the will, higher the panic chance". Is it possible that will stat increases be handled differently than through promotions? (IE: the officer mechanics maybe?) and I just haven't played enough to see them?

**Comment by Arubiano83** [comment]
Yes, it's intended. It would trivialize will otherwise. The idea is you have to manage your will/tired/shaken status. If soldier will keeps increasing, those systems would be pointless.

Also a bit patronizing of you thinking you are the first to notice this, when there is a discord full of people playing lwotc, including multiple streamers. 
Anyhow, no, that will doesn't increase isn't an an oversight.

**Comment by 0xStarcat** [comment]
@Arubiano83 I think you'll want to stop calling people who raise issues patronizing otherwise you'll turn away potential contributors to this mod. Are you a dev or a contributor to this mod? If so I'd say you should document this decision if so many people have noticed it and said something. 

Speaking of that, I did my research which included searching these issues, googling, AND asking the discord about this and no one seemed to know. I raised this issue not because I thought it was the first time it'd been raised but so I could understand if it was a bug or not, the intent behind the choice better, and document the replies in writing for future searchers.

**Comment by TwinuX** [comment]
WOTC reduces will pretty significantly from base X2, by removing some of the late-game growth. Part of the reason for this is to support the Fatigue System.

LWOTC utilises the Fatigue System with a few alterations, so keeps the changed will growth. Getting more will with each promotion would allow soldiers to just out-level their fatigue, which is not ideal. 

The will changes also increase the relevance of Focus PCSs, will-increasing abilities/officer-effects/CAs, and makes enemy psionic attacks more effective late-game. Sectoid Commanders in particular were rather ineffective in LW2, because XCOM's will was too high by the point they started spawning.

**Comment by Arubiano83** [comment]
Apparently i am a misinterpreter of messages. Not a dev or contributor. Just a loudmouth.

 But no, the will doesnt go up. And honestly,  just doing mission normally,  you'll barely notice any effect on tired status. Only noticeable affect is sectoids being more effective. The will system has been discussed a lot on the lwotc discord. You could drop by there to ask more about it.

**Comment by pledbrook** [comment]
See TwinuX's response for the main reasons behind the current system. There are no plans to change it at the moment.

**Comment by 0xStarcat** [comment]
Thanks @TwinuX and @Arubiano83 this makes the system a little clearer to me. Having not gotten far enough to have officers or seen the sectoid commanders it wasn’t immediately obvious to me why the stay would remain as it does, and I do i enjoy the fatigue system a lot. 

The discord is a great place and for any Googlers who might have this question I hope this issue is a good reference
