### ISSUE TITLE
[Beta 5] Detection range is displayed incorrectly

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1486]
When I move a unit to the field shown in the screenshot, the enemies are alerted.

![Detection_Range](https://user-images.githubusercontent.com/87030865/143672707-3fac7250-63a0-4556-8eff-99094a4d989e.jpg)

[save_Detection_Range.zip](https://github.com/long-war-2/lwotc/files/7611402/save_Detection_Range.zip)

**Comment by pledbrook** [comment]
Sorry, going to file this one under XCOM 2 jank too. Rooves can be particularly bad with detection tile painting, but sometimes there are other instances where you move to a non-painted tile and still end up breaking concealment.

Also note that this often happens when you can't see one of the members of the pod, and *they* end up being the ones seeing you. Not saying that's the case here. Haven't checked. Just putting it out there.

**Comment by MoreFirepower** [comment]
> Also note that this often happens when you can't see one of the members of the pod, and _they_ end up being the ones seeing you. Not saying that's the case here.

A shinobi on the ground had the entire pod in view.
