### ISSUE TITLE
[Beta 5] Relay can not be damaged

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1487]
A hotfix would be nice! I can not continue playing otherwise.

![Relais](https://user-images.githubusercontent.com/87030865/143674248-5f28782a-98bd-4f3e-a728-e184861863eb.jpg)

[save_AUTOMATISCHER SPIELSTAND- Kampagne 21, Einsatz 20, Runde 13.zip](https://github.com/long-war-2/lwotc/files/7611464/save_AUTOMATISCHER.SPIELSTAND-.Kampagne.21.Einsatz.20.Runde.13.zip)

**Comment by pledbrook** [comment]
Sorry, I can't load non-English save files. Have you tried this with just the minimal required mods for LWOTC? No one else has reported this, so it sounds more like a mod interaction than a base LWOTC bug.

**Comment by MoreFirepower** [comment]
> Have you tried this with just the minimal required mods for LWOTC?

I think so!

![Mods1](https://user-images.githubusercontent.com/87030865/143675929-bb4e07de-70b9-4d6b-a78a-6601a8f163a2.jpg)

![Mods2](https://user-images.githubusercontent.com/87030865/143675935-4385bd68-c4ae-4744-b992-762e29ff2b13.jpg)

When I fire at the relay, the damage points are displayed in a popup, but the state bar does not change.

I would really, really like to keep playing the game! Is there any way to manually add the displayed damage via console commands?

**Comment by pledbrook** [comment]
Oh right, I know what's going on. You are doing damage. The problem is that the relay is only showing the vanilla number of HP pips, whereas the actual health of the relay is much higher. If you keep damaging the relay, the pips should eventually start dropping down until you kill it.

This is a known issue with no known fix. Sometimes the game displays the wrong HP for environmental objects. Usually it works fine. Please just try to keep damaging it and see whether it's eventually destroyed.

**Comment by MoreFirepower** [comment]
I will try, thank you very much!

**Comment by pledbrook** [comment]
Known issue, no idea how to fix it.
