### ISSUE TITLE
Two potential bugs in Beta5

### ISSUE THREAD

**Issue by MoreFirepower** [long-war-2/lwotc#1498]
1. I constantly experience that when snipers aim at chosen, the game displays much too high hit probabilities and damage. Afterwards, a noticeable number of shots with 80%+ hit probability miss and if they do hit, the damage is much lower than predicted (most recently I think I observed a limit of 12 damage points per hit, even with plasma lance and deadeye!). 

2. When a still concealed shinobi ran two (or one?) squares past a cloaked phantom, the shinobi was not noticed.  I guess that's not how it's supposed to be?

![Unbenannt-1](https://user-images.githubusercontent.com/87030865/145249142-11b58856-54e6-4e20-bb0e-1f7595e3c4d5.jpg)

**Comment by MoreFirepower** [comment]
A phantom suddenly appears on the roof and does not see the shinobi

![Ph](https://user-images.githubusercontent.com/87030865/145814633-77d6f742-2572-4ff0-8c3d-74248f69bb47.jpg)

**Comment by pledbrook** [comment]
1. I haven't seen any issues with this. If you have a screenshot of a non-graze doing less damage than previewed in the shot HUD, that would be helpful.
2. I'm wondering if these are because the Spectre is showing in a different location from where they actually are, which is not particularly uncommon and just some base-game issue we believe.

**Comment by Grobobobo** [comment]
None of these are lwotc bugs really.
