### ISSUE TITLE
Soldiers able to get additional abilities for zero AP from Traning Center

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#152]
It looks like the training center is allowing some skills to be acquired for 0 AP even after you have promoted the soldier (the skill they get on promotion always costs 0 AP). This lets the soldier get a lot of unintended skills from all trees.

**Comment by ansabalirai** [comment]
This is a known issue for some time and there was some extended discussion on how to solve the conundrum since before alpha 2 release I think (see #23 and #82 for more discussion). However, more relevant to the issue you pointed out, it seems to happen if you buy an ability from the training center screen (rather than the normal promotion screen) for a specific tier and then the other abilities in that tier become free I think.
Regarding how to fix, a simple/quick idea for now can be to not allow them to train from training center at all (removing "+bAllowAWCAbilities=true" in the class data ini) for LW2 classes, but for a long term solution, see my suggestions in #23

**Comment by Kazanir** [comment]
This seems to be fixed by the new integration of NPSBD FWIW.

**Comment by jmartinez989** [comment]
oh yeah. let me close this.
