### ISSUE TITLE
Epic Games modding

### ISSUE THREAD

**Issue by Manoxone** [long-war-2/lwotc#1556]
Hi! i'm looking to install LWOTC on my epic games version of the game, so i dont use the steam workshop, and i'm kinda lost, i dont know how to make it work. Thanks in advance for the help, looking forward to trying this mod !

**Comment by rrnwang** [comment]
Should be the same as https://www.gog.com/forum/xcom_2/mods_in_gog_version/page1

You should not open it as an issue here. You should ask on [r/xcom2mod](https://www.reddit.com/r/xcom2mods/) first.

**Comment by Mitzruti** [comment]
the EGS version can't use cooked mods due to being a different version under the hood.
No cooked mods means no Highlander. No Highlander means no LWOTC.

unfortunately, the way to make it work is to buy the game on a different platform.
steam version is ideal for modding (was released there first, workshop and all that jazz). GoG works too if you dislike steam, but some hoop-jumping may be required.

**Comment by Tedster59** [comment]
Closing this one since Mitzruti is correct here, due to the WoTC Highlander LWoTC can't work with the Epic Games version.  I saw somebody was able to get base LW2 working for the Epic Games version, but I have no details.
