### ISSUE TITLE
Reaper cannot activate Shadow while in regular concealment

### ISSUE THREAD

**Issue by Iridar** [long-war-2/lwotc#1565]
If the Reaper starts mission in concealment, they will have a large detection radius, same as other soldiers. And they cannot activate Shadow, because they're already concealed. 

The solution is to allow using Shadow even in concealment. However, since Shadow is temporary, you will need to make sure the concealment is not broken when Shadow runs out if the Reaper was already concealed when Shadow was activated. I use a Unit Value in my Bounty Hunter's Nightfall ability for this.

**Comment by BlueMajere** [comment]
You'd have to double check with Grobobo to be sure, but I'm pretty sure this was done intentionally to prevent cheesing Lib4 missions.

**Comment by TwinuX** [comment]
Rather, it was done to prevent Stealthing any mission.
It's fully intentional that Reaper Shadow only works when the unit has lost concealment, otherwise it would be possible to avoid pods easily and complete missions without engaging enemy units (which is not intended). LW2/LWotC is not designed or balanced with stealth as being a valid way of completing missions.

The only way Reaper would be allowed to use Shadow from concealment would be if it broke concealment for the rest of the squad (including the Reaper) upon ability activation or expiration, and that was deemed too frustrating/confusing to be used.

**Comment by Iridar** [comment]
I see. Can't say I fully agree, but if it's intentional, then closing the issue.
