### ISSUE TITLE
Game crashes to desktop at the end of Advent HQ Assault (lib-5)

### ISSUE THREAD

**Issue by LyerLyer** [long-war-2/lwotc#1574]
Hallo everyone,

recently I did my first Advent HQ assault. As I complete the mission and receive the message from Bradford, the game just crashes to desktop. This is something that already happened to me in the past in the same campaign, but this time I am not able to load the save anymore: if I try to do so, the game starts loading and then crashes again to desktop.

Being an ironman campaign, I am afraid this means that the campaign is lost, which is a pity. As I understand this issue may be connected to the amount of enemies/corpses in the mission (they were 33-36). Is there any way out?

I don't really know how to attach the crash report :/ , if someone tells how to, I'll be happy to put it here.

thanks!

**Comment by Tedster59** [comment]
Not a LWOTC dev, but a long time player.  Unfortunately this is one of those "known things" that I don't think anybody has a good way to fix, and is one of the many reasons people recommend against using the game's ironman mode, and instead play "honestman" because stuff like this happens.  The "workaround" is usually to make a save right before killing the last enemy on these big missions, and reloading that.

**Comment by Tedster59** [comment]
Fixed with my standalone mod, or in the latest beta release.
