### ISSUE TITLE
standalone download package with all dependencies

### ISSUE THREAD

**Issue by goofyseeker311** [long-war-2/lwotc#1585]
there should be a compiled package for the gog version

**Comment by Tedster59** [comment]
Unfortunately, issues with the WoTC Highlander prevent it from working with the GOG version, so there isn't a good way to make LWoTC work with the GOG version unless that is resolved.  I recommend waiting for a Steam sale, the game plus DLC regularly go to 75-90% off.

**Comment by Iridar** [comment]
> Unfortunately, issues with the WoTC Highlander prevent it from working with the GOG version, so there isn't a good way to make LWoTC work with the GOG version unless that is resolved. I recommend waiting for a Steam sale, the game plus DLC regularly go to 75-90% off.

Are you confusing GOG with EGS? To best of my knowledge, GOG version works perfectly fine with all XCOM 2 mods, they just require manual "installation" into the XComGame\Mods folder.

**Comment by Iridar** [comment]
> there should be a compiled package for the gog version

You (and anyone else) is welcome to buy the game on steam, download the mods they want, and repackage them as they see fit. As long as they don't sell the mods or try to claim authorship, I doubt anyone would raise much of a fuss. But it's not LWOTC devs' responsibility and not a reasonable thing to demand or ask for.

**Comment by Tedster59** [comment]
Right, it's Epic version specific and not an "anything but the Steam version doesn't work" issue.

**Comment by goofyseeker311** [comment]
> > Unfortunately, issues with the WoTC Highlander prevent it from working with the GOG version, so there isn't a good way to make LWoTC work with the GOG version unless that is resolved. I recommend waiting for a Steam sale, the game plus DLC regularly go to 75-90% off.
> 
> Are you confusing GOG with EGS? To best of my knowledge, GOG version works perfectly fine with all XCOM 2 mods, they just require manual "installation" into the XComGame\Mods folder.

there is no clear installation instructions for gog version. also I do have the steam version also. were missing the gog version.

**Comment by Iridar** [comment]
> there is no clear installation instructions for gog version

https://www.reddit.com/r/xcom2mods/wiki/index/download_mods#wiki_how_to_install_mods_manually

**Comment by goofyseeker311** [comment]
its not clear

**Comment by Iridar** [comment]
What part specifically isn't clear to you? Most people who have the basic computer skills would get everything they need from the two example images alone.

**Comment by goofyseeker311** [comment]
I read it several times and could not understand what to do, so I think its the instructions that are not clear.

**Comment by goofyseeker311** [comment]
what alternative game launcher?

**Comment by goofyseeker311** [comment]
> > there is no clear installation instructions for gog version
> 
> https://www.reddit.com/r/xcom2mods/wiki/index/download_mods#wiki_how_to_install_mods_manually

why you link outside of github for such instruction? not clearly here, but split into the winds on the internet, peculiar.

**Comment by goofyseeker311** [comment]
> Unfortunately, issues with the WoTC Highlander prevent it from working with the GOG version, so there isn't a good way to make LWoTC work with the GOG version unless that is resolved. I recommend waiting for a Steam sale, the game plus DLC regularly go to 75-90% off.

I wait steam and online content delivery platforms to be gone off-line, very peculiar times indeed

**Comment by Iridar** [comment]
@goofyseeker311 
You don't seem to understand how this works. This is not a service. You are not a customer. We don't have to do anything for you. We don't owe you anything. We're all volunteers here, doing things we like because we like them. 

I want to help you, just because I'm a nice guy like that, but you're not making it easy, being all snarky and defensive, without explaining what specifically you're having trouble with.

So I ask again, which step of the instructions, specifically, are you having difficulties with?

> why you link outside of github for such instruction? not clearly here, but split into the winds on the internet, peculiar.

LWOTC GitHub repository is a place where people can collaborate on developing the LWOTC mod. Using steam mods with GOG version of the game is a general modding topic and it doesn't have anything to do with LWOTC or its development, so the instructions reside on a popular social network platform. /r/xcom2mods/wiki predates LWOTC by several years, so it's a relatively well-known place among people who want to mod XCOM 2.

**Comment by goofyseeker311** [comment]
you are making it all very hard for everyone involved, like you dont want anyone to be using what you develop here. just saying. no hard feelings, when we depart each other.

**Comment by Iridar** [comment]
Also, to be clear, I'm not a part of LWOTC development team and I do not speak for them. My words are my own.

**Comment by goofyseeker311** [comment]
one thing @Iridar I dont need your approval for my writings here.

**Comment by Iridar** [comment]
> if those instructions of how to use THIS are not here, where is the coherence? I'm not expected to find my way to some reddit post, no matter how op its been there. 

The instructions for using LWOTC _are_ linked on the [repository's main page](https://github.com/long-war-2/lwotc#installing-and-playing-the-mod). They don't cover the GOG version because LWOTC was not made for the GOG version. The GOG version does not officially support mods, only the Steam version does.

> at least a repository is assumed to hold (stand-alone) what is needed to fully run itself, no matter what else is in the internet. 

Not really. The GitHub is not the primary distribution platform for this mod, Steam workshop is, with Nexusmods being a distant secondary.

> ok if the current steam workshop issues prevent from this running with gog version then fine, but at least say so, openly cleanly, like the contrib did here just now.

You can run LWOTC with the GOG version of the game. You just can't get it from the Steam workshop, because Steam and GOG are competing platform and Steam workshop does not support any GOG game.

> again, if the official instructions dont mention the reddit post (why would it) I'm not to be required to have to go there.

LWOTC was made for Steam. You want to use it outside of Steam. If you want the mod to be more flexible, you will have to be more flexible too. 

I don't want to waste time on pointless arguing. If you want to get LWOTC working, I can help you. If you want to keep arguing, I will stop replying.

**Comment by goofyseeker311** [comment]
of course, because you are the law @Iridar

**Comment by Iridar** [comment]
https://i.ytimg.com/vi/KA3RY5f6i6k/maxresdefault.jpg

**Comment by goofyseeker311** [comment]
@Tedster59 alternative mod launcher with manually installed recent mods downloaded by hand from the steam workshop seem to work fine, with the highlander+alien mods, with the full gog xcom2 package. some weird first mission at the gate crash, tho, why? I will next try the .ini file manual loading without launcher method.

**Comment by goofyseeker311** [comment]
@Tedster59 can you tell what the "issues" with the highlander mod are/would be? game not launching at all?

**Comment by Tedster59** [comment]
I misspoke earlier and confused the GOG version of the game with the Epic Games version, which is different.  Highlander does not support that version and has issues with it.

**Comment by goofyseeker311** [comment]
nexusmods is a derp site. just saying.

**Comment by goofyseeker311** [comment]
the current 1.0.1 version does not include the image for alloy knife, in research, shows only "image text" placeholder, not an actual image.

**Comment by Tedster59** [comment]
Right now the 1.0.1 package is outdated, I'm going to get a proper version uploaded here as well.

**Comment by goofyseeker311** [comment]
ok. idk if you have fixed this, but somehow lightning hands does not allow double shot with light 
em up (3 shots in one turn by default), the turn ends right after the first normal gun shot after lightning hands.

**Comment by Tedster59** [comment]
I've never heard of this being an issue before.

**Comment by goofyseeker311** [comment]
testing side note (1.2.2): why do evacs activations work even if unit has ended turn at that position, but opening a box does not.
idk if this happens with opening doors. but at least mission objective boxes and secondary mission loot boxes open only on the next turn, if you end turn next to the box. this is not original xcom2/woc behaviour. evac working on end turn is original xcom2/woc behaviour.

is this behaviour coming from lwotc or any of the other included mods?
