### ISSUE TITLE
Drone Shock didn't do damage

### ISSUE THREAD

**Issue by torma** [long-war-2/lwotc#160]
Drones should do at least 1 damage with drone shock.

I had an isolated sniper while a drone came out.
The drone was damaged before it was able to get a drone shock off.
The sniper got disoriented but didn't lose any ablative health.

Save files at:
https://drive.google.com/file/d/1TN9tHV2FJIb3o0tkBnnfVt_y1krrbsh-/view?usp=sharing

Mod list (only listing additional mods):
[WOTC] New Target Icons
WOTC - Extended information
Evac All - WOTC
[WOTC] Additional Icons
[WOTC + Classic] Tacticalui Killcounter
Yet Another F1

**Comment by Favid** [comment]
I downloaded the Before save and the Drones are removing ablative armor as expected. Not sure if this has already been inadvertently fixed or I'm just getting "lucky"

**Comment by pledbrook** [comment]
It's definitely still happening. I'm wondering whether the shock is grazing and it's rolling down to 0 damage for some reason.

**Comment by Favid** [comment]
There is this in X2Effect_ApplyWeaponDamage.CalculateDamageAmount:
```
if (ApplyEffectParameters.AbilityResultContext.HitResult == eHit_Crit)
{
	WeaponDamage += CritDamage;
	`log("CRIT! Adjusted damage:" @ WeaponDamage, true, 'XCom_HitRolls');
}
else if (ApplyEffectParameters.AbilityResultContext.HitResult == eHit_Graze)
{
	WeaponDamage *= GRAZE_DMG_MULT;
	`log("GRAZE! Adjusted damage:" @ WeaponDamage, true, 'XCom_HitRolls');
}
```
GRAZE_DMG_MULT is 0.5, and it's possible to do 1 base damage with Drone Shock, so 1 * .5 = 0 damage since it's an int. I don't see anything that explicitly prevents you from dealing 0 damage, except in the case that the damage is reduced to 0 because of armor (in which case this is accomplished by reducing the value of armor for the calculation, not increasing the damage). 

I don't think this has anything to do with the Shield. I think this may also be a base game bug, but no one noticed because nothing has a base damage of 1 and grazes are more rare outside of LW2. Regardless, I believe this would require a Highlander change.

**Comment by pledbrook** [comment]
Unsuppressing `XCom_HitRolls` should confirm whether that's the case.

**Comment by pledbrook** [comment]
It looks like LW2 modified the base game's `CalculateDamageAmount()` so that it always dealt a minimum of 1 damage, even on a graze. I don't know whether this is important enough to "fix". You still get the disorient effect, which is the main thing. Grazing for 0 seems OK to me.

**Comment by pledbrook** [comment]
This would be dependent on [a highlander change](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1109).

**Comment by copyrite** [comment]
I self-assigned this to experiment if armor has any effect on zeroing the damage. From what I can tell, armored units too can take a graze for 0. With that loose end tied, I think we can call this a feature and close the issue.
