### ISSUE TITLE
Weapon env damage values being ignored?

### ISSUE THREAD

**Issue by TwinuX** [long-war-2/lwotc#1611]
LW2 and LWotC greatly reduced environmental damage values of weapons for both XCOM and ADVENT, to values low enough that they shouldn't destroy cover for a lot of the game.
However, direct hits on units using some forms of cover, such as the walls in subway maps, will often destroy and downgrade the cover at even the earliest stages of the game. Templars melee attacks also seem to draw a line between the starting point and target of rend, and break walls it passes through. 

Pretty vague and unhelpful, and no realistic idea of what's going on, but it seems like an unintended outcome given LW2's significantly neutered cover destruction mechanics.

**Comment by ReshiMael** [comment]
This is a combination of basegame issues, that may possibly be unfixable due to scale of effort required and native code.

1. Melee Abilities have their effects calculated at every tile the attacker passes through, and can cause bugs with certain abilities (one of the reasons why bladestorm is limited to once per unit) or weirdness such as the aforementioned weirdness with Rend.

2. Most types of XComDestructibleActors (Non-Interactive map objects that can be damaged) will automatically degrade and eventually destroy themselves once they take any amount of damage. If they have a low base toughness, they will quickly downgrade or break even from the slightest bit of damage. To fix this, every XComDestructibleActor in every map parcel and pcp would need to manually changed, which is a bit of a herculean issue.

**Comment by Tedster59** [comment]
Based on Reshi's comment, I doubt this is something I can do even  if I want to, as this is fundamental basegame code I can't really touch.
