### ISSUE TITLE
Timers and RNFs need to be stopped when chosen active.

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#181]
When chosen activate the mission timer keeps ticking down and rnfs still come in. Need to have both stopped while chosen active.

**Comment by pledbrook** [comment]
I think the timer issue is specific to Jailbreak as it uses old LW2 Kismet that doesn't have any knowledge of the Chosen.

The `UMS_LWContinuousReinforcements.umap` Kismet doesn't take into account the Chosen either. Vanilla reinforcement subsystems seem to just disable reinforcements for the entire mission if the Chosen are deployed (not just engaged). The better option for us may be to suspend reinforcements within the `LWCallReinforcements` code if the Chosen are engaged. Or perhaps just deployed.

**Comment by pledbrook** [comment]
I've added a configuration setting that excludes a configurable set of mission types from having the Chosen on them. This is mostly a quick fix for Jailbreak_LW which uses old LW2 mission code/timers/RNFs.

Timers for most missions should pause, but I think _UMS_LWContinuousReinforcements.umap_ needs updating to handle the Chosen. Either that, or the `SeqAct_LWCallReinforcements` action.

**Comment by TheReigningKing** [comment]
Is there a method to re-instate the reinforcement timers after the chosen leaves or dies?
I have been able to kill the Chosen, and then take my time because the reinf timer didn't start ticking down again.

In my actual opinion, the Chosen should be considered a lvl1 Reinf, and the reinf timer shouldn't stop, but maybe just reset.  The turn cap in LW2 has usually been the reinfs themselves rather than the mission timer itself

**Comment by TheReigningKing** [comment]
RNFs do not stop when paired with the Rapid Response DE and a Chosen is active. I'm on the dev 5 build

**Comment by Grobobobo** [comment]
Already fixed, chosen remove reinforcements and pause timers as intended.
