### ISSUE TITLE
Mind controlled units not being treated as "Friendly" by enemies

### ISSUE THREAD

**Issue by SydenInsomniac** [long-war-2/lwotc#210]
When friendly units are under the mind control effect.  The computer still shoots at them like they are an enemy.  So for instance unit get's mind controlled the next two units fire at mind controlled target.  Target dies what was the point of mind control?

In the base game when a unit is mind controlled it's treated as "Friendly" until the effect ends.  Have seen multiple instances of mind controlled unit running to cover next to an enemy soldier only to be instantly killed by a flank attack.  Not sure if this is a bug or intended.  

Also unconfirmed but it seems mind control targeting is being directed the same way as firing solutions.  I.E. the target with the least amount of cover is always the target for mind control.

**Comment by pledbrook** [comment]
Don't know about the targeting, but the mind controlled unit is supposed to be targetable by ADVENT. That's a LW2 change.

If you have a save file that demonstrates the targeting behaviour, please attach it.

**Comment by jmartinez989** [comment]
This is intentional behavior in LW2. Yes I know it might seem kind of counter intuitive for enemies to take control of your unit only to shoot it but the unit only stays controlled for 2 alien turns so the aliens will just shoot it so that they can possibly kill it before mind control wears off. This actually makes sectoids a big threat and is one of the reasons why flashbangs were made infinite.  Earlygame sectoids are a big deal in LW2 if you don't have flashbangs.

Only thing I have always found odd is that the unit that is being mind controlled can no longer take cover (at least that was the case in the latest LW2 build, not sure about lwotc).

**Comment by pledbrook** [comment]
Working as expected. We may revisit this topic as part of general balancing.
