### ISSUE TITLE
Remove "removes burning" from description of Hunker Down 

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#216]
Hunker Down doesn't remove burning in LW2, so that should be removed from the description of the ability.

**Comment by MiserablePileOfBugs** [comment]
I solved it by adding this:

`[HunkerDown X2AbilityTemplate]
LocFriendlyName="Hunker Down"
LocHelpText="Increase Defense by <Ability:HUNKERDEFENSEBONUS/>, and Dodge by <Ability:HUNKERDODGEBONUS/>. Only works in cover."
LocFlyOverText="Hunker Down"`

To C:\Program Files (x86)\Steam\SteamApps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Mods\LongWarOfTheChosen\Localization\XComGame.int

**Comment by yoshimo** [comment]
How about fixing it the other way round and remove burning by hunkering down?

**Comment by pledbrook** [comment]
Because it trivialises burning and I'd have to fix the enemy AI to hunker when burning in order to balance it.

**Comment by Anxoczt** [comment]
It should put out fires, given how now purifiers are part of the basic enemy composition. And yes, it should be programmed for the AI too.

**Comment by MiserablePileOfBugs** [comment]
I respectfully disagree. Not only because it would mean more work for the team (fixing the other bugs and restoring the graze band are more pressing matters imo) but also because it would make the technician really weak. If burning enemies for two turns can't be relied upon anymore, why should I ever bring a technician instead of an other class that has an infinite number of useful abilities like the faction classes?

For rockets? The grenadier is more reliable with explosives, can use four or more grenades per mission and can move before firing them.
For the smoke effect aka tanking? It's certainly useful but being able to kill enemies is better.

**Comment by Ankaridan** [comment]
> I respectfully disagree. Not only because it would mean more work for the team (fixing the other bugs and restoring the graze band are more pressing matters imo)

Removing burning by hunkering down was added with WOTC, so it's at least within the scope of the mod to examine the issue, but I don't think it needs to be changed. I almost agreed with Yoshimo, at first; with the addition of purifiers, fire is profoundly more common, which may be why hunkering down was originally given that function.

However, now that I think about it, to put out fire, we currently have: running onto water tiles, psi soldier aura, hellweave vest and medkits, yes? The fact that LW2 gives infinite medkits, rather than a created item, already solves this in my mind. We're basically trading hunkering down (burning) = infinite medkits.

**Comment by MiserablePileOfBugs** [comment]
I think I have the solution. Meet the new class: the Burning Ranger! Special abilities:

- Water lance: puts out any fire in a straight line of 6 tiles. Consumes both actions, ends your turn.
- Water bomb: deals 5 water damage on it's landing tile and puts out any fire in a 1 tile radius. Two charges. Ends your turn. Also very effective against fire elementals.
- Fire Axe: deals 8 melee damage. Kills all doors in one hit. 
- Immune to fire attacks and burning effects.
