### ISSUE TITLE
Rework covert actions

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#218]
Covert actions have a couple of problems:

 * They're not very interesting
 * They have very strong rewards (promotions, stats, XP)

They really need to fit better with LW2 strategic objectives. Here are my current thoughts:

 1. Rework the mission rewards by getting rid of regional income and maybe breakthroughs (and others?). Add in things like gaining bonus detection for the next supply raid/troop column (corpses!), discover Chosen weaknesses/strengths.

 2. Remove promotions and stats as additional rewards. Potentially keep stat increases as a bonus reward, but at high risk.

 3. Use covert actions to unlock WOTC missions. For example, Gather Survivors/Swarm Defense to get soldiers/engineers/scientists, Compound Rescue to recover spy that has information on a Chosen, etc.

The main goal is to make Covert Actions a mechanism for giving players some sense of control with regard to strategic objectives, be that resource gathering, knowledge of the Chosen, facility leads, personnel, or corpses.

**Comment by yoshimo** [comment]
I don't think they are boring or too rewarding.
Keep in mind that there are quite a few soldiers that you have to train and equip.
Its not necessary to remove small stat increases and promotions therefore.

The idea in point 3 to have additional CA missions as  gatekeeper to high reward missions ,small side quest chains ,is something worth pursuing though.

**Comment by torma** [comment]
I have not tested this yet but from previous experience with LW2+WOTC I agree with @pledbrook. I also generally like the ideas. 

1. I would keep the breakthroughs. Instead of gaining bonus detection they should just straight up reveal a mission: counter dark event, troop column, supply raid, find lead for landed UFO, rescue scientist/engineer/soldier (instead of rewarding one). Unlock facility. It should only reveal a mission with at least 3 days left for infiltration. Having the same rewards as POIs is fine for most cases. I would remove scientist/engineer/soldier, +1 contact from the rewards.
2. Just remove additional rewards.
3. In this case gather survivors and swarm defense should also be reworked to always contain a single VIP and rookies. Getting max level soldiers would just be OP. So gather survivors would always reward 2 rookies + VIP and swarm defense would always reward 1 rookie + VIP.

**Comment by Ankaridan** [comment]
1. See [Covert Action Missions](https://steamcommunity.com/sharedfiles/filedetails/?id=1123382166&searchtext=covert); I've been using it in my current test and so far it has functioned without issue (only a supply raid at this point). When sending soldiers out on these, the duration is long - ~12-14 days with engineer - and the risks are notably higher. They also are not guaranteed to be in the pool, as opposed to added to it: exception being rescue a capture soldier, which appears the month after the capture occurs.

2. I'd be happy to see promotions dropped, but I have a soft spot for the stat increases. In vanilla they are particularly strong because you field like 6-8 soldiers, but rosters in LW2 are substantially larger and subsequently stat increases end up being much more spread around. To my awareness, this is the only realistic way to improve a soldier's Will, as well, so rolling soldiers with 35 willpower is not as crippling. I don't see the stat increases making super soldiers, so much as trying to bandaid weaknesses. A lieutenant sharpshooter with 70 aim isn't a liability in a fight (or a military discharge) when you can spend a few months sending him out for training 2 or 3 times.

3. Also see [Plot Gated Chosen Missions] (https://steamcommunity.com/sharedfiles/filedetails/?id=1140251687&searchtext=gated); you cannot max out a hero faction influence or 'rush' the chosen at Tech 1 while they still have only troopers and officers. Progressing through faction influence and the stronghold quests requires that you progress through the story; influence 2 and the mission to find the stronghold needs the black site complete / codex killed, and influence 3 and the stronghold raid need the forge complete / psi gate mission. This ensures that Chosen actually remain viable threats through the entirety of a campaign.

**Comment by Ankaridan** [comment]
Replying to my own comment. Going from [the Covert Action](https://xcom.fandom.com/wiki/Covert_Actions) list, were the choice mine:

- Remove the sabotage mission.
- Remove intel, supply collection and region income missions.
- Signal Boost - instead of increasing available number of contacts, what about changing to reduce contact cost?
- I like the idea of Engineer/Scientist missions spawning a VIP recovery, ala [Covert Action Missions](https://steamcommunity.com/sharedfiles/filedetails/?id=1123382166&searchtext=covert). 
- Personnel Extraction has to stay.
- I see no issue with Tactical Education, Combat Preparedness or Teamwork Training.
- I see no issue with Tactical Advances or New Orders.
- Counterintelligence is -always- a high risk activity, which is warranted given its value at endgame. At least in vanilla WOTC, this became high priority based on which action the Chosen was undertaking.
- Generic recover alien loot is fine, but could be expanded upon. Can we gate covert actions behind research tech? Covert action to recover 2 mag rifles, covert action to salvage 1 coil sniper rifle, covert action to find a suit of Warden Armor, etc. Because vanilla blankets out the inventory upgrades and LW2 doesn't, this is an obvious area we can expand greatly into. 
- I do like the idea of covert actions to recover corpses.
- Taking cue again from [Covert Action](https://steamcommunity.com/sharedfiles/filedetails/?id=1123382166&searchtext=covert) missions, how about spawning a Force reduction mission in a random region?

**Comment by Kazanir** [comment]
Really love the idea of re-doing these to more closely mesh with the Long War strategic layer and had some initial thoughts here: https://github.com/long-war-2/lwotc/issues/116#issuecomment-495930769

Ideas for covert action rewards affecting the strat layer:

- Manipulate vigilance in a region
- Block retaliation missions in a region
- Generate some of the WOTC missions Paledbrook was mentioning
- Reduce detection minimum for incoming reinforcement missions and/or troop maneuvers, or reveal where the next ones will be
- Generate a Facility Lead
- Boost rebel XP gain or rebel equipment tier in missions

Some of these are probably better for early or late game, I'm sort of just spitballing.

As far as the promotions and skill rewards, I think this is an opportunity to create a catch-up system. If we can change the soldier slots that offer those rewards to have a _maximum_ rank (which goes up slowly as Force Level increases) then you have a way of boosting the power of lower-rank soldiers that are filling in for your dead and wounded as the campaign progresses. This fixes the abuse of promotion to get ahead of the curve and the idea that your end-game A-team is going to have 10 months of covert ops buffs on them, but gives us a catch-up mechanism in the same format as the WOTC system.

Another related thought I had was if we've considered the idea of slots for Rebel personnel on these, who would have the potential of getting captured, ambushed in rebel gear, etc. It's just an idea but I think it would be cool to really make these feel like they are part of Long War and it sort of thematically fits.

**Comment by torma** [comment]
@Ankaridan @Kazanir I still think stat rewards should be removed.
What you want to do is double down on soldiers rolling high stats to make them god like.
Soldiers with bad stats can be sent to havens. Low level soldiers can be sent to easy missions for "training".
Leaving in stat bonuses as a reward means, super soldiers:
You can have sharp shooters and rangers with base aim above 100.
You can have assaults and shinobies with 20 mobility.
Or make a corporal with 59 dodge like her (date is June 4th, 2035):
![20190620234125_1](https://user-images.githubusercontent.com/26032734/59884261-1cebed00-93b8-11e9-98fc-bf7108e557cb.jpg)

**Comment by Aurelicornus** [comment]
I would split the problem in two ways.
* I agree to remove the bonus stats from covert actions. They make super soldiers without need to do... nothing, no missions, no tasks.
* Remake the Faction HQ into training camps where a soldier can improve some stats after some considerable time (1 month?) for raise a stat of +1, or anyway "very little". Maybe this can help to improve those soldiers that have very low skills, the faction camps are only 3, and adding the long training time, this make very hard "stack" a lot of skills to the same guy.
* Better, one could cap the training bonus usable for any single unit (ex: no more than +5 points in each stat), removing the excessive staking. I believe this could works in conjunction with the PCS without breaking the system.
* Covert Actions would be interesting if they unlock some "new" missions that can be accessible only with the new game function. I think variants of the one already present in the game, but with different rewards, if possible richer or more interesting for push the player to invest in these.
- Improving weapons: Recover datas from a terminal, but maybe done with half of the team and without make blow the cover (Reapers could be very useful here), or the data are "wiped out" from the terminal.
- Acquire loot: Smash and Grab, but without blow the cover, and depending which loot is specified in the CA, you get supplies or alien resources, or maybe the "new" recover supply mission in WotC where you must touch the crates before Advent takes them, usually in a Lost city.
- Find the Chosen: another data recover from terminals, like Improving weapons/ another VIP (resistance or Advent) recover mission.
- Recruit faction hero: recover VIP mission (from Lost cities or from ADVENT), except the VIP is an Hero, maybe with an increased escort to eliminate.
- Some CA could be used for those maps where Losts are the only enemy present, like the recover VIP stranded in the abandoned city to save before the gun runs out the ammos.
- I would remove the missions that trains the soldier bonds/improve combat intelligence/ and such, except if one don't make up a mission that could fit in those themes...

And go on. I think the special missions fits better for CA, thinking they require some times before being unlocked, like the infiltration for the normal missions.
Maybe there is interests/time to create some entirely new ones? That would make the CA unique, but if time/resources are tight, I think would be ok make a variation of those already present in LW and recycle the new ones introduced by the expansion (recover the VIP in the Lost city).

> Ideas for covert action rewards affecting the strat layer:

I think these could be good special rewards for CA missions, and only if the player wins the mission. :)

**Comment by The13Inquisitor** [comment]
Insofar as additional stat rewards are concerned, I'd make that a Covert Action on its own. Super soldiers are fun, but what are people willing to let go to make them?

**Comment by cshen6** [comment]
Yes definitely needs re-work!! Covert used to be my second favorite feature of WOTC, not any more as it doesn't sync with other aspects of LW2. Thus I totally agree with point 1 & 3.

But not so sure about point 2 based on my 4-month in-game play so far:
Because covert action takes so long & there are so many missions going on in LW & we are in shortage of soldiers early on, getting rid of stat bonuses may make covert action even less attractive -- Whereas in vanilla I always loved these small bonus & send in soldiers whenever possible. In Lw2, I am now unwilling to send my good & valuable soldiers onto these actions, even if they have a nice +3 aim bonus! 

Again, this is simply because LW2 mission rewards are more attractive and important than covert action even with stat bonus. Infiltration takes 6 days, but most covert action takes longer than that.

Also, the ambush mission needs either re-work or taken out, this has always been the most boring / easiest mission type in WOTC.

**Comment by MiserablePileOfBugs** [comment]
It occurred to me that you can recruit multiple faction soldiers of the same type. Seems like an OP way to fill your barracks as they also arrive fully promoted. I think there should be a limit of 1 of each type as long as they are alive.

**Comment by The13Inquisitor** [comment]
The levelling up on arrival is no different than with any other type of soldier. At most, setting it so that Faction soldiers always arrive at Squaddie rank would be a better alternative.

Otherwise, it's balanced by the extreme rarity of said soldiers and the fact they can't be everywhere at once, due to infiltration.

**Comment by cshen6** [comment]
> It occurred to me that you can recruit multiple faction soldiers of the same type. Seems like an OP way to fill your barracks as they also arrive fully promoted. I think there should be a limit of 1 of each type as long as they are alive.

My understanding is you can get at most two faction soldiers from the first faction contacted, and one soldier only from the other two factions, per vanilla WOTC. So that is not really OP -- also other than reapers (with its obvious scouting advantage), templars and skirmishers are quite situational and not better (and I say quite useless) than regular soldiers. I will want one reaper per squad, but not the other two!

**Comment by rrnwang** [comment]
I would just like to add that you can be "ambushed by the chosen" before they are activated. 

Now of course there's no Chosen on that mission, just ADVENT troopers. But it might be a good idea to make that another possible way to activate the Chosens (if it seems the player is abusing not activating the chosens for more covert op missions.

**Comment by MiserablePileOfBugs** [comment]
Personally I would leave the promotion but limit it to sub SGT units. After all, I find that training fresh recruits can be tiresome even with **Trial by fire**.  

I also miss the old training center where you could station a young recruit to get some perks to increase it's chances to survive on the first missions.

**Comment by rrnwang** [comment]
You can get a Continental bonus that puts all Rookies trained in Guerilla Training Center(facility?) at Corporal when they finish. Possibly, the LW team should make sure that's a guaranteed roll for a continental bonus? Once force level gets high enough, sending out rookies on any mission is just having the rookie tag along, maybe throw a flash or grenade. Other than that, I don't trust them with aiming - usually just hunker.

**Comment by PodliKirill** [comment]
Maybe just give to the soldier some fixed amount of XP instead of promotion? It's good way to train newbies, but painfull for skilled soldiers. XP like 5 man very light mission will be enough IMHO.

**Comment by cshen6** [comment]
Promotion-wise, actually happy with officer ability "trial by fire" and its balance -- lw2 missions are many, and usually allows one newbie per mission in regions where advent strength is not strong. So the officer ability serves the purpose quite well so far in my play.

**Comment by tunbridgep** [comment]
The covert action that reduces the Advent Calendar (hehe) needs to go. It literally invalidates the thing

**Comment by pledbrook** [comment]
An implementation that's sufficiently OK for 1.0 was added with [this commit](https://github.com/long-war-2/lwotc/commit/14df5c508363bf09dc2af160afef82617757228a) (plus subsequent changes)
