### ISSUE TITLE
List of incompatible mods

### ISSUE THREAD

**Issue by Ankaridan** [long-war-2/lwotc#221]
Running through a list of mods to see how well they work:

### Incompatible (hard crash)

 * _LW2 Show me the Skills_ - Revived - immediate crash
 * _LW2 Tactical Suppressors_ - immediate crash
 * _WOTC World War L_ - crash on spawning new Lost units?
 * _LW2 View Infiltrating Squad_ - crash mid mission, error box blamed this mod??
 * _Upcoming days in hours_ - hard in armory / soldier screens

### Mods that do not function properly

 * _Always bleed out_ (I guess due to LW2 tampering with the bleed out chances)
 * _TLP: Unlocker_ - Beyond the basic weapons, it seems you cannot get the batch of weapons once you hit the mag tier.

### Mods that hurt performance but work

 * _WOTC Idle Suppression_ - technically mod functions as intended, but LW2 generally has a higher # of actors on screen at any one time, so the mod drains system resources very quickly.
 * _Allies Unknown_ (As it adds a new faction on the map, but for some reason it causes the game performance in battle to go down considerably).

### Mods that work with but have errors or issues

 * _WOTC Cost-Based Ability Colours_ - mod functions, but causes some icons to be blank
 * _RPGO_ - promotion screen issues (see post by Anxoczt) (PAL: This is because of issues with New Promotion Screen By Default. Once we get that working, this will not longer be an issue)
 * _Grimis loot mod (WOTC)_ - item spawn rate not working as intended

### Mods that seem to work without issue

 * _Cost-Based Ability Colours Non-WOTC_
 * _WOTC Show Health Values_
 * _WOTC New Target Icons_
 * _No Reveal Cinematics_
 * _Disable More VO_
 * _WOTC Advent Flashlights_
 * _WOTC Extended Personnel Info_
 * _Unrestricted Customization WOTC_
 * _I am the commander here_
 * _Less overwatch lockups_
 * _After max level advancement_
 * _Buildable Geths_
 * _Disable any class_
 * _Ballistic shields_
 * _WOTC Flawless_
 * _Soldier's development_
 * _Primary secondaries_
 * _WOTC dropship naration blackscreen fix_

### Mods that seem to be working (undergoing testing)

 * _WOTC Extended Information_
 * _Covert Action Missions_
 * _More Resistance Ops_
 * _WOTC Robotic Spectre_

### Unknown status (require more testing)

 * _WOTC Fair Lost Targeting_
 * _No rank up throttling_

**Comment by Anxoczt** [comment]
I might chip in with mods i am playing with, feel free to add them to your post.

Mods that damages performance but work:
Allies Unknown (As it adds a new faction on the map, but for some reason it causes the game performance in battle to go down considerably).

Mods that work with minor or inconsequential problems
RPGO
RPGO addons (biotics, LW2 classes etc...)
These major mods have only one "broken" thing and that is you cannot promote and pick new abilities if your soldiers get promoted directly in the scene where Firebrand opens the ramp and your soldiers form up, clicking on the promote screen does nothing, but if you go the armoury or even to the notification menu you can promote and upgrade your troops just fine

Mods that work but not as intended
Grimis loot mod (WOTC) - Bloats the dropped items... abit, like its not uncommon for a viper to drop like 8 items, not only that, they can drop alot of loot boxes, from time to time on black market i notice that i have 50 low quality boxes i could sell for supplies. Opening the boxes does work but you can only get basic items, even if the box offers you like exo-suit, it will give you kevlar armour instead, same with weapons.

Mods that just work
I am the commander here
Less overwatch lockups
After max level advancement
Buildable Geths
Disable any class
Ballistic shields
WOTC Flawless
Soldier's development
Primary secondaries
WOTC dropship naration blackscreen fix

Mods that dont work
Always bleed out (I guess due to LW2 tampering with the bleed out chances)
TLP: Unlocker - Beyond the basic weapons, it seems you cannot get the batch of weapons once you hit the mag tier.

Mods that maybe works as intended.
No rank up throttling - Since LW2 penalizes the XP from killing aliens, i guess i havent been in a mission where a single soldier could even in theory level up more than once so if this mod even works... thats a good question.

**Comment by Ankaridan** [comment]
Thank you kindly, I have updated my first post accordingly. Hopefully this will help bring more people in to test the Alpha, too.

**Comment by MiserablePileOfBugs** [comment]
These mods seem to work well in alpha 3 and 4:

- [WOTC] Hours instead of days
- Upcoming events in hours
- Evac all - WOTC
- Capnbubs accessories - WOTC
- [WOTC] Mod config menu
- [WOTC] Additional icons
- Smart overwatch all [WOTC]
- [WOTC] Quick soldier info
- [WOTC] Detailed soldier lists

More testing required:

- [WOTC] Gotcha again - Seemed to work at first but they were instances where I had soldiers get overwatched when I moved them on a tile for which the mod didn't display any OC icon. I desubbed/resubbed and it looks ok now but I prefer to wait a bit more to be sure.
- Instant Avenger Menus - WOTC - I had an occurrence where all the avenger's menus turned black. I'm trying to recreate the issue so I can see what provokes it.

**Comment by FallenKing947** [comment]
I played alpha 3 and 4 with stable working World War L. "Lost" sitrep still working on evacuation mission and I was met couple spawned Losts Brute with working "Burst" ability. But i not sure about other lost skins, they was disabled at mod config menu.
Also with enabled Fair Lost Targeting, some of lost horde tried to attack advent soldier

**Comment by pledbrook** [comment]
Thanks for doing this. I've moved the content to the [Wiki](https://github.com/long-war-2/lwotc/wiki/Mod-compatibility-(community-maintained)), so please make further changes there.
