### ISSUE TITLE
Heavy Ordinance Perk applying to Squaddies/Lance Corporal

### ISSUE THREAD

**Issue by Ankaridan** [long-war-2/lwotc#224]
Purchase perk on Grenadier at Corporal rank. Existing Grenadiers at a lower rank all gain the extra Grenade slot.

**Comment by Ankaridan** [comment]
Started new game, confirmed on second playthrough. Additionally, newly created Grenadiers will automatically have the additional Grenade slot.

**Comment by jmartinez989** [comment]
when you say extra grenade slot, do you mean that all grenadiers get an extra grenade in their grenade only slot or that all grenadiers get another slot altogether? In LW2 Grenadiers have 4 slots which 1 is reserved for grenades only. When you get heavy ordinance the amount of grenades you get from the grenade only slot goes to 2 instead of 1.

**Comment by Ankaridan** [comment]
Ah. Yep, I'm a dumbass. I've been playing WOTC with the LW2 Perk pack for so long I had things confused, evidently. With the perk pack you don't get the grenade-only slot without Heavy Ordinance. So not a bug.
