### ISSUE TITLE
Mind Control/Hack are easily abusable

### ISSUE THREAD

**Issue by ChrisTheThinMint** [long-war-2/lwotc#229]
(Mind)controlling enemies grants you a expendable unit that can easily be used as a bullet sponge and can also deal additional damage, while also removing that unit from the enemy lineup. Its an incredibly powerful effect that can be easily achieved by stacking will or hack debuffs, and some enemies are quite vulnerable to it while being perfect tanks. Also, enemy survivability scales faster than enemy damage, especially on higher difficulties. Once the late game rolls around, enemy damage doesn't even come close to being able to scratch some of the enemy units (Heavy MECs, Sectopods, Gatekeepers, Shocktroopers, Muton Elites).

Different solutions that i could think of and see as viable:

1) Make enemies less likely to or even unable to target mindcontrolled units. Problematic with permanent control as it lets the unit roam free.
2) Make (XCOM) mind control debuff the enemy, reducing/removing armor and defense and/or increasing damage taken, so that other enemies have an easier time when dealing with them. Possible drawbacks with this approach: 
- Unless the debuff is really strong enemies would still waste atleast one turn.
- Also, players might start using the debuff as a way to have enemies executed when they don't want to deal with them themselves.
3) Nerf mindcontrol abilities, for example by: 
- Reducing the duration of normal control to 1 turn and nerfing permanent hack to something around 3-6 turns (could factor in psi offense)
- Not restoring the charge of Full Override and Domination if the attempt fails.
- Increasing action cost or difficulty of control abilities.
- Making control perks harder to acquire on the trees (don't start with Haywire, move Full Override up, give Domination more prerequisities).

**Comment by Anxoczt** [comment]
If it was such a problem, why didnt Long War 2 addressed it ? And why did it even gave you more tools to do just what you describe ? (Like redscreen rounds).

Sounds to me like a pointless nerf just to make the game even more **artificially** harder if am honest.

**Comment by Ankaridan** [comment]
While I don't agree that there is an issue with Mind Control, I similarly don't see this as something that falls within the scope of this mod. The goal is to make LW2 and WOTC play nicely. What you've described is vanilla behaviour not only in Xcom2, but in the original Xcom, as well.

**Comment by jmartinez989** [comment]
Reopening this to continue the discussion. Would definitely like to talk balance on mind control. Hack I think is still debatable but MC is def still too strong.

**Comment by micahswab** [comment]
Controlling an enemy provides multiple very strong bonuses. To make controlling less universally beneficial, perhaps you could share action points between the linked units. The controller could sacrifice an action to move the controllee, or act on their own and leave the controllee stationary. Arguably, taking actions with the controllee is the weakest bonus controlling them gives you, so I don't think this would be a huge nerf. Instead of implementing an actual shared action point system, you could utilize the WOTC teamwork perk logic to grant an action to the controllee at the expense of the controller's. 
This would also make the sharing explicit so you wouldn't accidentally use an action without realizing it.

**Comment by SydenInsomniac** [comment]
But the blade cut's both ways.  Enemies can easily mind control your guys and use their abilities against you as well.  If you fail hacking a unit it gets a pretty large buff.

Ask yourself is it really too powerful or are you just save scumming so you always succeed?

My technical unit was mind controlled and wiped my entire squad with a flame thrower burst.  Yes it's useful but it's been part of xcom from the beginning.  Why change it?  If you think it's cheap don't use it.

**Comment by BlackRose39** [comment]
I like the idea of sharing action points between the user and mind controlled unit.

Otherwise, domination only has one charge and there is a dark event, "Barrier," which makes it harder to succeed with MC (but also helps Sectoids and Priest?). You do need time and investment to train a PSI soldier as well. A certain enemy has the ability as well.

I think keep MC as is, maybe think about implementing the share action points with maybe a new perk to keep the action points for both separately?

**Comment by allenhu0912** [comment]
Really? Domination sucks. By the time you actually have it, you're looking at missions where you're often fighting 15+ enemies at once. MCing an Advent goon doesn't do much because they die in 2-3 hits. If you're lucky you'll get a Muton Elite or Archon, but even then there's a chance to fail. On the other hand, the ability to mind control enemies with Insanity is quite strong, but that also only happens later on with maxed out gear, and I consider it payoff for all the investment into psi troopers early on.

Also, hacking is fine. Failing a hack on a Sectopod can screw you over badly, it's not something you can take for granted.

**Comment by wortkarg** [comment]
I think that it is not quite correct to consider these abilities separately from soldier classes. There are more and less useful abilities, but the classes are pretty well balanced. Is a MSGT psi op with Domination or a specialist with FO better as MSGT gunner? No, I wouldn't say so. They have their own strengths and weaknesses. The difference is, that gunners or rangers do direct damage and support classes do it through MC, and even then a gunner can do a lot more damage than a mind controlled elite muton and psi op together.

The main problem with MC is, that MC-ed enemies can be used as bait to draw fire from the rest of the squad (damage that they can deal is not that important). I like first two options from Chris. Our soldiers must be a high prio targets for the enemies and MC-ed enemies must have something like Rupture effect, so they can't distract enemies for long time (or lower defense/armor, because they can't protect itself good enough, if mind-controlled).

1) Insanity
Reducing the MC probability a bit is ok IMHO (or 1 turn cooldown).

2) Domination
Domination is only slightly OP, if at all. If the controlled enemy get lower defense/armor, it's balanced already.

3) Full Override
The first option can be converted in "shutdown till the end of the mission" and the chance of the the second option can be nerfed a bit (or not). Additionally all hack defense debuffs can be nerfed as well. Without debuffs the chance to control a sectopod is something like 60-65% for the first option and 45-50% for the second option (MSGT specialist with top items (105-115 hack + 65 from items)).
Debuffs:
Red screen rounds: -30
Arc Pulser: -20
Bluescreen Bombs: -25
The second option will give us only 69% in average with all debuffs applied and we not always have an assault with Arc Pulser, so without AP, it's only 64%. So even with current numbers the second option is not really OP, the problem with drawing fire is still here though.

**Comment by pledbrook** [comment]
Various aspects of mind control have been nerfed, particularly Insanity. Leaving any further work to LWOTC-R probably.
