### ISSUE TITLE
Xwynns' balance ideas

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#237]
Apparently xwynns had a bunch of ideas for LWOTC from back when Pavonis Interactive were discussing porting LW2 to WOTC. Here's what we got from him in Discord:

 * Have concealment last a fixed number of turns based on level of infiltration
 * Remove free-action abilities except for those provided by perks (no headshot, no auto reload, grapple costs an action)
 * Add two extra M tiers of enemies to match the 5 tiers of weapons
 * Make some consumables single use (as in one charge?)
 * Sitreps for equivalence of LW1 squad-wide foundry projects
    - There would be positive and negative ones
 * Also, SitReps for general difficulty scaling in place of or in addition to Dark Events
 * Use the trait system to put both positive and negative ones on people
 * Weight balance towards soldiers and perks over equipment
 * Use resource (say supplies or elerium) to speed wound recovery on chosen soldiers
 * Aim for rosters of 50+ soldiers rather than the 35ish needed for LW2
 * Balance around 3-4 hits being enough for a kill, strong enemies could kill in 2-3, while weak ones in 4-5. But the weak ones could inflict debuffs and/or provide other utility.
 * I probably would have removed Phantom entirely
 * Add new boss enemies, in the vein of LWR, i.e. bigger/tougher variants of drones, Generals or other units. Like the Hive Queen.
 * Use hordes of Lost as time pressure on the player, similar to reinforcements.

General points:

 * If I made lwotc the design goal would be 'engaging turn based tactical warfare'
 * "My main question for anyone who wants to design a lwotc, is what is the functional purpose of having the Chosen in the game"
 * Hard and persistent counters to things are really bad for tactical gameplay
 * What should differentiate how people approach combat is a mix of various enemies and maps and various player skills, such that it's a new experience every time
 * If you want combat variety, make sure the player can't bring the same classes (and perks) to every mission, and make the power of soldiers based mostly on perks and not items/gears, ie: lots of wounds and long recovery

**Comment by Aurelicornus** [comment]
> Have concealment last a fixed number of turns based on level of infiltration

I feel bad about this. In feel in Vanilla the gameplay is too quick that you have little time to plan a good attack with concealment, and usually is rewarding killing the aliens immediately in my case; the same tactics I employed in Xcom 2012 where the concealment weren't there remains more effective.
In LW 2 I had more use of it to plan the first attack, and delay the appropriate moment, thanks also because you aren't forced to drop it in every missions.

> Remove free-action abilities except for those provided by perks (no headshot, no auto reload, grapple costs an action)

I dislike this one. The free actions balances the matter you have an overwhelming quantity of enemies against you, and free you that couple of actions for keep them at bay. Both in Vanilla and LW I felt they fit in the flow of the gameplay.

> Make some consumables single use (as in one charge?)

Ain't sure much about this one. In Vanilla would have sense, you have need to upgrade your squad just one time, but in LW you need to upgrade each unit one by one. I felt my supplies burn very quickly in LW all time, if some basic stuff would be consumable too, would more "heavy" than enjoyable.
Is true that Xcom for DOS you needed to buy everything, even bullets and grenades, but you got a game economy that allows the player to support all those expanses, that in actual LW2 model doesn't happen. Supplies available to the player should be doubled in this case.

> Also, SitReps for general difficulty scaling in place of or in addition to Dark Events

Would be interesting if SitRep would be random modificators that are applied to a single region for some time (1 month or more). Each region can have different SitRep active and all mission done in those regions during that time will have the same SitRep.
That I think would be an interesting way to specialize some soldiers for some kind of events, or make special "strike teams" against particular conditions.

> I probably would have removed Phantom entirely

Bad. Phantom is intended to allow you to have at least a scout in squad for checking if there are enemies around, and let you plan a bit instead to guess if you will bump into a pod or not. Same for snapshot snipers, is an help to let them place in position.

> Use hordes of Lost as time pressure on the player, similar to reinforcements.

In many ways, is already that in Vanilla, just the gameplay is quick and kill them is (by purpose) very simple.
The most fun I had with the Lost is use them as weapon against Advent with the lure. The interesting thing with them is being able to manage their presence in a way they can be used against the aliens, despite they are hostile against the player. I would find interesting instead if there are more way to "manipulate" them, not just with the lure, instead to have just more of them to take down.

> If you want combat variety, make sure the player can't bring the same classes (and perks) to every mission, and make the power of soldiers based mostly on perks and not items/gears, ie: lots of wounds and long recovery

The problem I find in LW 2 is that is less "flexible" as design than LW1. In LW 1 you got more equipment with different effects at disposal for equipping the soldiers: light and heavy armor, the standard and battle rifle, Sniper rifle and Strike one, etc. You were able to have three secondary weapons too, depending from your strategies.
LW2 here "standarized" some things, where all classes have unique equipment, but are all the same. That's "flattered" a bit the classes, despite they have perks that specialize them much better than what were possible done in Xcom 2012.
I feel some parts of LW 2 should be redesigned as concept for remedy this thing, not just "adding" some stuff or just tinkering some stats; but at this point, would not much the same LW 2 that people waits.

**Comment by Grobobobo** [comment]
>  Have concealment last a fixed number of turns based on level of infiltration
Stealth as a way to take your time setting up for an ambush is fun and desired, there are better ways of fixing the stealth cheese. 

> Remove free-action abilities except for those provided by perks (no headshot, no auto reload, grapple costs an action)

Removing headshot would require a complete rebalance of lost, However I'm for removing auto-reload as it trivialises ammo management. Grapple costing an action would make light armor and skirmishers not very desirable, but could be okay with proper compensation. In general, I think free actions do have their place, even if they're slightly overused. 

> Make some consumables single use (as in one charge?)
Not sure what that even means, perhaps that you have to produce your own grenades and stuff? if so, LW2 has enough micro-management as is, That'd be completely unnescesary,

>Add two extra M tiers of enemies to match the 5 tiers of weapons
Yes please. 

> Sitreps for equivalence of LW1 squad-wide foundry projects
I don't get that, aren't breakthroughs/proving ground the equivalent of foundry projects? But more systematic sitreps are definitely a good idea.

>Also, SitReps for general difficulty scaling in place of or in addition to Dark Events
Definitely not in place, and permament Sitreps would make variety and ui a mess, but temporary dark events that produce negative sitreps are interesting.

> Use the trait system to put both positive and negative ones on people
Definitely sounds like a good idea, but not for the WOTC trait system. There was already a mod that gave soldiers random traits for long war, maybe take it from that?

>Weight balance towards soldiers and perks over equipment
I think the opposite makes for a more interesting tactical game, sometimes the stakes for losing an individual soldier are just too high, and invoke frustration rather than tension. Besides, i hate useless rookies. And LW2 already puts a big emphasis on abilities.

>Use resource (say supplies or elerium) to speed wound recovery on chosen soldiers
There's already that hyper something module, you can balance that for long ware.

>Aim for rosters of 50+ soldiers rather than the 35ish needed for LW2
Sure, especially with covert actions.

>Balance around 3-4 hits being enough for a kill, strong enemies could kill in 2-3, while weak ones in 4-5. But the weak ones could inflict debuffs and/or provide other utility.
Well, depends on a soldier, sparks obviously need way more. Regardless, I'm all for longer firefights in general.

>I probably would have removed Phantom entirely
Unless you intend for reapers to take over for scouting, that's not a good idea.

>Add new boss enemies, in the vein of LWR, i.e. bigger/tougher variants of drones, Generals or other units. Like the Hive Queen.
Sure.

>Use hordes of Lost as time pressure on the player, similar to reinforcements.
With some Lost rebalancing, why not?

>If I made lwotc the design goal would be 'engaging turn based tactical warfare'
What does that mean exactly? Moving away from puzzle-based alpha striking? Less emhasis on strategy layer and more on tactical layer?

>"My main question for anyone who wants to design a lwotc, is what is the functional purpose of having the Chosen in the game"
Here's my opinion on the chosen mechanic:
Personally, I'm not really a fan of chosen being focused on killing on normal missions. That leads us to 3 scenarios:
a) Chosen is weak - Like in vanilla, It asks us the question of why are they even there, besides free 10 ability points
b) Chosen is strong, but standard enemies are weak - With this, chosen are a nice suprise that gives flavour to otherwise weak mission, but the problem with that is the missions without them are boring now.
c) Chosen is strong and enemies are strong - That makes some already hard missions pretty much impossible due to the chosen power spike. And since their appearance isn't all that predictible, this can get really, really frustrating.
IMO the only way the chosen mechanics can be fun if they pose little tactical threat on normal missions, being almost purely focused on interrogation, capture, but make the chosen defence an actual penalty for letting them have their way.
By chosen defence being a penalty I mean a mission so ridiculously hard that 6 guys dead is considered a success.
If chosen are difficuilt to kill, they still can be a challange for easy missions, and on hard ones you can focus on the mission and let them interrogate at the cost of potentially getting buttfucked by them finding the avenger. That makes for interesting risk menagement.

>Hard and persistent counters to things are really bad for tactical gameplay
Yep. Stuff like mindshields for the warlock, combatives for meele are bad for that.

>What should differentiate how people approach combat is a mix of various enemies and maps and various player skills, such that it's a new experience every time
On strictly tactical layer sure, but that's really vague. 

>If you want combat variety, make sure the player can't bring the same classes (and perks) to every mission, and make the power of soldiers based mostly on perks and not items/gears, ie: lots of wounds and long recovery

I'm all for diffrent class builds and cycling of soldiers, but I'm not sure how emphasis on perks is supposed to accomplish that. Equipment is, in a way a perk system on its own.
