### ISSUE TITLE
Soldiers left behind on missions are being recovered

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#238]
[save_AUTOSAVE-_Campaign_43_Mission_111.zip](https://github.com/long-war-2/lwotc/files/3294139/save_AUTOSAVE-_Campaign_43_Mission_111.zip)

If the two SPARKs evac the mission above, the two unconscious soldiers are not captured, but return to the Avenger wounded.

**Comment by DerAva** [comment]
Adding a save from my campaign where the same thing happened (Ranger is stabilized and will be recovered instead of being captured).

[stab_saved.zip](https://github.com/long-war-2/lwotc/files/3294148/stab_saved.zip)

**Comment by awmbonke** [comment]
I just had this happen on a Smash and Grab mission. Two soldiers that were bleeding out were recovered despite them showing as having been killed in the mission summary right after extraction.

**Comment by pledbrook** [comment]
Using DerAva's save file, I couldn't reproduce this with the current development version. Assuming that it's fixed. If anyone encounters it again with alpha 6, then please reopen and attach another save file demonstrating the issue.

Also, the mod currently kills soldiers that get left behind. As far as I can tell from the base game code, only mind control results in capture. I don't know if original LW2 did something to make capture happen in more cases.

**Comment by pledbrook** [comment]
This is clearly still a problem. Evac from the following mission and see how an unconscious soldier materialises back on the Avenger:

[save_BUG Unconscious guy back on Avenger.zip](https://github.com/long-war-2/lwotc/files/3580822/save_BUG.Unconscious.guy.back.on.Avenger.zip)

**Comment by MalekDeneith** [comment]
Adding my save in case it helps in any way (zip contains save and list of mods in case they're needed to make it run). Like mentioned on reddit in my case it was a mind controlled soldier. 

Tried checking if it might be mod compatibility thing with two things that stand out on my list - Evac All and Loot Mind Control. The former doesn't seem to be the culprit since removing it didn't fix the problem, couldn't load the save without latter but since other instances of this bug were unconscious soldiers rather than mind controlled ones it's probably not the case either. Not much help, I know, but at least it rules out two minor possibilities.

[Mind Control Bug.zip](https://github.com/long-war-2/lwotc/files/3580838/Mind.Control.Bug.zip)

**Comment by pledbrook** [comment]
Ugh. I may wait a bit before I try that save file 😆 Too many mods I would need to fetch, and the save file crashes on load (after getting Even More Maps).

**Comment by BlackRose39** [comment]
@pledbrook It looks like, in my play through as of Beta 2, soldiers left behind are still magically appearing back on the Avenger after a **Recruit Rescue Raid.**

**Comment by pledbrook** [comment]
Good catch. I think I must have missed this one when I reviewed the existing mission types.
