### ISSUE TITLE
Insufficient missions awarding corpses

### ISSUE THREAD

**Issue by jws381** [long-war-2/lwotc#252]
I've started a total of eight of playthroughs on the most recent three releases, and in only one was I able to acquire enough Advent Officer bodies to proving ground the Skulljack in the first several months of the campaign.  I generally stopped playing if I got five or six months in without the Skulljack.  The early campaign needs more missions that award corpses or the number of Advent Officers present on such missions needs to be buffed.

**Comment by jmartinez989** [comment]
This is actually working as intended. The goal of lw2 and lwotc is to extend the length of the campaign by a good bit and one way to do that is to provide fewer missions that reward corpses.

The  main way you are supposed to get corpses in the early game is through rendezvous missions by having an adviser in your havens as much as possible.

One thing I will say is that the number of rendezvous missions that get detected does seem rather low and even when you do get one it is about 50/50 on having an officer so I think that can be looked into. Other than that I think that the current mechanic is working just fine.

**Comment by BTAxis** [comment]
In LW2 I never started rooting out the Faceless before I had at least one region liberated, because you have few enough rebels to start with as it is and as far as I know the spies still contribute to recruitment and intel jobs (although I could be wrong on this - haven management is obscure). Instead I got my corpses from supply raids, troop movement and the first HQ assault mission.

**Comment by jmartinez989** [comment]
> In LW2 I never started rooting out the Faceless before I had at least one region liberated, because you have few enough rebels to start with as it is and as far as I know the spies still contribute to recruitment and intel jobs (although I could be wrong on this - haven management is obscure). Instead I got my corpses from supply raids, troop movement and the first HQ assault mission.

that is one way to do it as well but in the state of the game as it is,  it seems that detecting those seems to be a bit harder than it used to be so you get a little more starved now than before.

Don't know if you have had better luck but in the last 2 campaigns I cleared I had spawned about a handful of troop columns and supply raids. So the issue I don't think it so much that there aren't enough missions that offer corpses but rather that the missions that do aren't spawning enough.

**Comment by Kazanir** [comment]
I agree that this is fine, but extremely opaque to new players and that a significant balance goal should be somehow educating players about the strategy layer. I have been regularly getting supply raids in 2 regions basically every month because I know how to set up the map such that they occur regularly, but a new player essentially has no chance of doing that without some significant education about the mechanics of ADVENT strength and movement. (This is all on the ADVENT's Agenda wiki page for LW2 but even that information isn't really a guide to the sort of stuff you need to do to be getting those missions regularly.) I'll go post this in the overall balance thread.

**Comment by pledbrook** [comment]
Probably won't get into corpse balance for a while, if ever.
