### ISSUE TITLE
Dark Event *Gone to Ground* don`t work

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#258]
After a few days black market was closed, shows searching on screen

![Blackmarket_01](https://user-images.githubusercontent.com/51829747/59852826-543aa980-9378-11e9-8966-1885b7df8576.jpg)
![Blackmarket_02](https://user-images.githubusercontent.com/51829747/59852827-543aa980-9378-11e9-8b80-5ab5b684543c.jpg)

[save_Black market dark event.zip](https://github.com/long-war-2/lwotc/files/3310598/save_Black.market.dark.event.zip)

**Comment by ansabalirai** [comment]
Given how much more critical the black market is in LW2 compared to vanilla, I wonder if we can just remove the DE altogether

**Comment by Kazanir** [comment]
Some of the other WOTC mega-events were dialed back to just 2-3 weeks duration which seems good to me so far; in my ongoing campaign I forgot High Alert was going on and nearly lost a Specialist to it but then it went off quickly enough that it didn't like shatter my progress or anything. Black Market seems like it should be similar of it is of a more limited duration, but if fixing it turns out to be hard then maybe we don't care and can ditch it.

**Comment by pledbrook** [comment]
I wasn't sure whether to keep the Dark Event or not. It is a WOTC dark event, so LW2 wasn't balanced around it. And it is pretty hard on players since the Black Market is so crucial to play. But then, Dark Events are *supposed* to hurt.
