### ISSUE TITLE
Intervention don`t work on smash N Grab

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#276]
After use commander ability *Intervention* its add 2 terns to timer, but next tern reinforcements still incoming.
[save_SmashNGrab_1.zip](https://github.com/long-war-2/lwotc/files/3326509/save_SmashNGrab_1.zip)

**Comment by jmartinez989** [comment]
Did you use the ability when reinforcements were already on their way or did you use it when you had 1 or 2 turns left?

**Comment by nightmaRok** [comment]
I use it at 1 tern left, also tested at start, after you been spoted use *Intervention*, timer up from 7 to 9, and in my turn its not 8 its 6. Also in "Smash N Grab" if you use *Jammer* reinforcements delayed correct, but after its cames two in a row. you can tested it on my save =)

**Comment by jmartinez989** [comment]
ok so intervention definitely has an issue.

as far as jammer goes, all that does is pushes the rnf drop to the next turn but also queues it on top of any other rnf dropping on the turn after that as well so that is why you see the drop of 2 pods when using jammer. In that respect jammer is working.

**Comment by wdanny69** [comment]
intervention is working properly now

reopen if there are still issues with it not working
