### ISSUE TITLE
Order Inside knowledge work 50/50

### ISSUE THREAD

**Issue by nightmaRok** [long-war-2/lwotc#288]
Order work on Expanded Magazine, Auto Loader, Laser Sight. Not work on Hair Trigger, Scope, Stock and dont know about Suppressor, but i think because in lw2 no orders it`s also dont work.

![Order_inside_knowledge](https://user-images.githubusercontent.com/51829747/60381492-36e39a80-9a5e-11e9-9df1-d86e5a883559.jpg)

[save_Inside_knowledge.zip](https://github.com/long-war-2/lwotc/files/3341645/save_Inside_knowledge.zip)

**Comment by jmartinez989** [comment]
This is because Scope, Stock, Hair Trigger and Supprerssor are technically different items that are not part of the list of items that insider knowledge works on.

We don't know if this resistance order will even be left in the game (among many others). Will leave issue open for now as we are still determining this.

**Comment by pledbrook** [comment]
Some of these are implemented as abilities. See `X2Ability_LW_GearAbilities`. The abilities created there could possibly be modified to take into account whether weapon mods are empowered or not.

**Comment by Grobobobo** [comment]
Frankly, I do not like the idea of enhanced attachments at all, especially the autoloader and the expended magazine.
