### ISSUE TITLE
many skills in training center are greyed out? (latest alpha 5 build)

### ISSUE THREAD

**Issue by captainbeastfeast** [long-war-2/lwotc#316]
I cant choose all the skills I want at the training center, only the xcom ones in the lower section. Is this intended? I like being able to pick a range of soldier skills, my tactical options are restricted.

This did not seem to be the case in the beta 1 build i tried a few days ago, I was able to pick any skills provided that I had enough points.

**Comment by jmartinez989** [comment]
so we changed it so skills in a soldiers primary skill trees are mutually exclusive so you cannot say have a sharpshooter with snapshot and DFA. You can however pick skills from the XCOM and pistol trees.

**Comment by captainbeastfeast** [comment]
Perhaps you could restrict certain skills and not others e.g rapid targeting and snapshot for sniper seems a bit silly. The training center is a bit lacklustre in this build, since xcom skills have varying utility and most my soldiers will never use a pistol.

Just my 2 cents, I realise balancing the training center may not be very straightforward.

**Comment by jmartinez989** [comment]
well we decided that soldiers being able to pick any 2 skills from the same rank is a little too strong so that is why they were made mutually exclusive. There are so many abusable combinations of skills that it is far better to just make them exclusive (among other issues).

That said we may tweak some of the AWC and pistol skills a bit. Pistols are actually a very powerful utility item when most or all of the skills are trained (like using redscreen rounds to to lower hack on a mec with things like lightning hands, quickdraw and fanfire and then hacking a sectopod). Pistols were definitely some of the more powerful utility items in LW2.

**Comment by ansabalirai** [comment]
yeah I personally side with @jmartinez989 on this. We have seen people do stupid stuff with DFA+snapshot (even though it has been nerfed now I think?) and anyway, LW2 classes were balanced around you picking (and skipping) skills as dictated by the development of a soldier's stats and barracks needs and I think that should carry forward in spirit here too

**Comment by jmartinez989** [comment]
That all said we may also adjust AP gains now that the AP events are gone. Well actually soldiers get more soldier AP now than they did before but we are also thinking of rewarding AP per mission completed. Should help to get a few more soldiers skilled up with all of the new AWC and pistol skills. Mind you we don't want every soldiers to be able to get all of those so that is why AP is being limited but there is definitely more tweaking that needs to be done.

Anyway this is not an actual issue so I am closing this unless I missed something

**Comment by rrnwang** [comment]
O.o

Well this is interesting. I just noticed this issue today after playing ALpha-5 for with NPSBD mod on.
I restarted my game because it was laggy as all hell, and that the game was imported from a previous save-game of Alpha-3. NPSBD will re-enable training all your AWC abilities, but will lag like a mother fucker. 

But honestly, there were some seriously broken combos you can pull off previously. Like Lethal (or AlphaMikeFoxtrot) + bring it on + (covert/shadow step, if you're lucky) + street sweeper + aggression + hunters instincts = instant 10+ dead enemies

**Comment by pledbrook** [comment]
Alpha 5 has New Promotion Screen By Default integrated. You should disable the separate mod.

**Comment by rrnwang** [comment]
Yes, I did so. That fixed my massive lag issue. I just wanted to drop a comment on this closed issue since I just ran into it yesterday and was wondering about it.
