### ISSUE TITLE
Consider removing innate defence

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#333]
Defence is a rather odd stat. What does it represent? To my mind, it's how difficult a unit makes it for a shooter to target them. That's why cover increases defence. It also makes sense in the case of smoke or anything else that blurs or otherwise impairs vision. But why does something huge like a Sectopod have defence that makes it hard to target?

On top of that, it's rather frustrating to keep track of each soldiers defence when positioning them to make sure they aren't too vulnerable. Eliminating innate defence would also remove this extra burden on the player and I don't think we would be losing something that makes the tactical gameplay that much more interesting (it's more frustrating in some cases).

A similar effect can be achieved through extra HP/armour/dodge.

**Comment by nightmaRok** [comment]
I don` know abaut removing innate defence, for me its bad, in late game aim on sectopods like always 95+ and with holo target you never miss, its not complicated to hit, its all abaut huge HP, and i think its very nice, becouse late game units must be stronger and hurder to deal with it.

**Comment by MiserablePileOfBugs** [comment]
I feel a bit conflicted about this. On one side, it's a real pain in the ass to manage as LWOTC only displays it properly on the soldier selection screen before a mission (thanks to the extended information mod!). In all the other menus, you have to click on the "toggle display" button so you can see it. Same shit on the tactical layer because you have no mean to display it permanently. 

On the other side, it's generally bad to remove a gameplay element without replacing it with something else. The defense stat also helps differentiating your soldiers and using it to your advantage in combat involves some skill.

Maybe we should consider replacing it with an other stat like resilience. Soldiers with high resilience may benefit from increased bleeding out chances, longer bleeding out timers and reduced recovery times from injuries. I also find it far more interesting than the binary defense stat: "shot hits you/shot misses you".

**Comment by jmartinez989** [comment]
Well from how I understood it innate defense was a bit overloaded because it seems that they (Firaxis) wanted it to mean 2 things. I think that they not only wanted it to represent how hard it was to hit something but also to represent durability. As in it was a stat meant to reduce incoming damage (seems that is why things like mutons and mechs have it for example).

I did always think that this was a bad design and it is especially egregious on Gatekeepers because not only do they have defense (and a lot of it) but they also reduced incoming damage by 3 when in closed state (honestly this mechanic for reducing damage makes more sense).

**Comment by pledbrook** [comment]
> ...and i think its very nice, becouse late game units must be stronger and hurder to deal with it.

Correct, and they have higher HP and armour for that. Innate defense makes very little sense thematically (except with something like a "distortion field" for example) and just encourages aim stacking. I don't really want LWOTC to be a game where folks believe the only stat that matters is aim (which is what it sounds like right now).

> On the other side, it's generally bad to remove a gameplay element without replacing it with something else.

Based on what? If a gameplay element isn't good, simply removing it benefits the game. And defence will continue to exist in the game, it's just a question of innate defence here. And using it appropriately does take some skill, but it's fiddly and requires you to always stay on top of who has what defence. It certainly gets stale quickly for me.

Anyway, I would like to replace innate defence on units that can't take cover with crit resistance as provided by the Nanoscale Vest and the Resilience ability. With a slight buff to health and/or armour, such units will be a bit more distinctive and less easy to take down.

**Comment by DerAva** [comment]
I'd say that there are two different issues here, and they should be handled separately: defence on XCOM soldiers and base defence on enemies.
Thematically, defence on enemies was always an indicator for me how hard it is to hit a vital part that actually does permanent damage to the unit. Yes, a gatekeeper is a huge target, but only shots that penetrate and actually hit the fleshy interior do damage to the unit. A shot penetrating the shell and then exiting again on the other side won't do much.  It also gives a big difference between the two lategame enemies, where the GK has this high defence value while a Sectopod is easy to hit, but has an even larger HP pool to chew through (and I'm fairly certain that Sectopods have no or only minimal deffence).

For XCOM soldiers: I can see the micro concern, but anecdotally that was never a consideration during a mission for me. The defence spread is so minimal that it doesn't really influence the decision making on whether you want your 3 def guy in the front or the 7 def guy. It does make defence PCS more interesting, though, as you might use them to make up for low/negative def scores and gives you the option to build a soldier with extremely high natural defence.

Finally, I'm fairly certain all units that can't take cover already have crit reduction based simply on the fact that they also can't be flanked.

**Comment by ansabalirai** [comment]
Fully agree with the points made by @DerAva. The only enemies that have really troubled me with stupidly high defense are Great Archons, Gatekeepers or maybe Superheavies. Sectopods do not have high defense AFAIK. 
For xcom soliders, it might be interesting to see how with the removal of the defense stat, whether there would be increased variability in dodge/HP or whether an additional stat like "thick skinned" can be considered (since resilience is already a -50 crit perk) to act kind of like how impact fields works. Would be a nightmare to balance though

**Comment by BTAxis** [comment]
> Anyway, I would like to replace innate defence on units that can't take cover with crit resistance as provided by the Nanoscale Vest and the Resilience ability. With a slight buff to health and/or armour, such units will be a bit more distinctive and less easy to take down.

At the risk of veering off topic a little, I'd like to address armour, which I've always found to be somewhat underwhelming in the grand scheme of things. I've never lacked for ways to swiftly shred it all off, and once it's off, it stays off, unlike defence. This to me makes it feel more like a few extra points of HP than the damage resistance mechanic it's supposed to be, and I consider speccing for armour on XCOM soldiers a losing gambit (as the aliens get lots of shred as well).

What I'm trying to say with the above is that in my opinion, armour doesn't really function as a means to make an enemy feel like a hard target while defence does, at least to some extent.

**Comment by captainbeastfeast** [comment]
It makes sense to me to remove inherent defence and replace it with a reworked dodge mechanic. A soldier or alien with a very high dodge (say 50 or higher) should be able to avoid attacks entirely (so the UI would say dodge 0 damage).

**Comment by cshen6** [comment]
Agree -- the best way is to probably set defense to 0 for everything involved; or use the defense stat in a different and more meaningful way in conjunction with dodge.

On the other side, after playing for so long I did get used to the fact that some soldier or aliens are simply a bit better / agile to evade the shot with a higher probability, as dodge stat only reduce damage in vanilla. And defense stat on xcom is usually quite low, so it is just a small stat to differentiate the soldiers.

**Comment by Anxoczt** [comment]
I agree, i dont like that soldiers have penalties against certain enemies who are tough already. While it makes sense that things like gatekeepers are hard to hit sufficiently to actually damage them (Although that wouldnt make sense for things like plasma weapons) i feel this is somewhat one sided since XCOM troops... well that reminded me what bout Sparks ? 
They would have to be buffed considerably (Alot more armour, immunity/resistance to shredding, ton more of HP) because else pretty much any attack made against them would be a easy hit, unhindered in any way and Sparks arent... what i would call a must pick in the first place. 

But either way, i say yes, let cover do the work for those that can use it and let those with tons of HP to get hit since they are made for that.

**Comment by SirMrMister** [comment]
> or use the defense stat in a different and more meaningful way in conjunction with dodge.

Just throwing an idea out there: Instead of innate defense, each XCOM soldier has their own innate graze band modifier (for when they get hit, not for when they shoot at aliens).

**Comment by Grobobobo** [comment]
Wayy beyond classic lwotc scope at this point.
