### ISSUE TITLE
Consider remove purifiers from reinforcements.

### ISSUE THREAD

**Issue by PodliKirill** [long-war-2/lwotc#340]
Just got purifier drop via reinforcements on my head. Overwatch kill - explosion - 2x6 hp wounded soldiers. Without reinforcement flares it's pretty bad experience IMHO.

**Comment by BlackRose39** [comment]
It would make for a more RNG terrible experience of having a bomb dropped on you without any warning and the player is unable to prepare for it in anyway as well as having the burden of choosing to overwatch or not, not mention having to take into account of mission critical VIPs/data cache, etc.

It's no different from a gatekeeper/sectopod forcing the player to fail a mission because it decided to "walk" over the objective. 

It's fair game with the flare visible and you would, for example, have to think twice about blade storming on that tile. Also, I think they tend to drop reinforcements near the evac flare since they're trying to intercept XCOM.

Otherwise, I think balancing this issue would be in order. My suggestion would be to adjust coding/scripting so that the purifer doesn't explode upon arriving first thing on the scene until its first real turn due to the possible messes/frustrations it can cause, unless someone can argue me about it being in favor of the player's control/power.

**Comment by Kazanir** [comment]
I think we want to remove Purifiers from reinforcements; this came up a few weeks back and that was @pledbrook's conclusion as well.

**Comment by BlackRose39** [comment]
Agreed, such a unit with this type of gimmick wasn't so from the original lw2.

**Comment by MiserablePileOfBugs** [comment]
I agree but not for the same reason. I think it's more often unfair to the aliens than to the player. It can make some missions even more trivial than they already are (like haven defense or rebel supply convoy).

**Comment by Anxoczt** [comment]
Or change that purifier is immune to overwatch for one turn once its deployed. This means player will have to deal with him anyway and most likely he will be forced to pull back troops so they dont get caught in the blast. Possibly forcing them to pull from a good position where they could fire at enemies.

**Comment by BlackRose39** [comment]
Or we could code for the purifier to not explode when it drops when it scampers.

**Comment by MiserablePileOfBugs** [comment]
> 
> 
> Or we could code for the purifier to not explode when it drops and scampers.

If it's feasible it would indeed be a good solution.

**Comment by pledbrook** [comment]
Should be fixed by above commit.
