### ISSUE TITLE
Unintended ini Configuration Regarding Alien Aim Adjustments when Soldier dies?

### ISSUE THREAD

**Issue by BlackRose39** [long-war-2/lwotc#363]
Greetings.

A while ago, I had looked at this discussion on steam:

https://steamcommunity.com/app/268500/discussions/2/1653297026038583838/

Just now, I wanted to disable aim assist, so I was checking out the XComGameCore.ini on disabling it. I had successfully alter the values on base wotc.

However, when I went to check on the long war folder to see if I could adjust them via the same ini file, I noticed something which reminded me of that discussion.

![aimalienbonus](https://user-images.githubusercontent.com/44072125/61822333-85dede80-ae16-11e9-9d03-f04401a6e9e0.PNG)

This is in the current long war 2 wotc build as of now, and is the same issue that someone has mentioned from the discussion link above.

So if a soldier dies, the aliens' next shot is guaranteed to hit regardless of difficulty (legend shouldn't be helping either side in terms of aim assist by default, but this current configuration is helping aliens on all difficulties after a kill) from what I understand. I wanted to bring this to attention if this was accidentally overlooked or if I'm not understanding something here.

**Comment by pledbrook** [comment]
This is intentional. The numbers make no sense unless you understand the code that handles the aim assist. You can't just disable it with a configuration option sadly, so the numbers in the INI effectively disable it. Stupid? Yes. But it's all we can do I think.

An alien's shot should not be guaranteed after a soldier dies in LWOTC. If you have evidence that this is indeed happening, please reopen the issue and attach save files.
