### ISSUE TITLE
Supply Raid Set Up Through Covert Op

### ISSUE THREAD

**Issue by Maebalzurakin** [long-war-2/lwotc#367]
After completing a Covert Op to set up a supply raid, the raid that is set up has several issues.

(Balance)  It will have a very low infiltration time.  Usually less than 24 hours.  It needs to be more so you don't have to face 20-30 enemy units.  Failing this 'bonus' mission can cause loss of the territory.

(Bug) After sending in a squad for infiltration, if you do not launch immediately and attempt to wait, the game will give you the 'important mission' notification.  It will then prompt you to send a second squad to that location.  Other strange things can happen.  If you do send a second squad, the fist one will get stuck in 'permanent infiltration' bug.  Further attempts to wait for the few hours that the mission gives you can cause the mission to fail without ever getting the 'must launch' notification and the failed mission can cause you to lose control of the territory.

**Comment by Maebalzurakin** [comment]
Does the game code generate a new supply raid, or is it making visible a supply raid that was already generated and counting down, but undetected?

**Comment by rrnwang** [comment]
I do not remember that "start your own mission" being a regular part of the LW2 mod. I do remember a  Covert Ops to set up your own missions being a part of a very popular other mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1123382166&searchtext=covert+ops

Frankly, the game is not balanced around that mod, and I do not have it installed. It might even be a conflicting mod.

Regarding your bug issue, I have never had it with Alpha 5. And I'm just starting plasma weapons now - so I've been playing relatively fine (bug-wise).

Regular "supply raids" missions that get generated are actually just "detected". They are supposed to have short time because they are supposed to be hard. All missions in all regions, other than the liberation missions you get, are generated at the beginning of each month. The number of haven members you have on "intel" determines you chances of uncovering those missions. All missions have an "intel" level which determines how easily they are detected. Their timers are pre-determined. In late game, with 13 haven members on intel (assuming you don't have faceless-es in there), I am easily getting supply raids with 8-day infiltration timer. 

The biggest rewards from the supply raids and troop column ambush are the corpses. If you want alloys, supplies, and elerium, go for Smash'n Grab missions: they give more.

**Comment by Maebalzurakin** [comment]
You are correct.  It turns out I had that mod loading.  Thank you for pointing that out.  It is disabled now.

While I can confirm that it is working, bug free, and is very beneficial in the first two months when intel is very low, after that it is something I never used.  I have 16/16 territories and I am getting swamped with 10x more mission opportunities than I can handle.

**Comment by rrnwang** [comment]
You're not supposed to do every single missions, though. I have 5 squads of pretty high-ranked soldiers, 4 squads of mid-ranks, and 3 more in the process of going through guerrilla training to be corporals. 

You're not supposed to be able to easily do supply raids. They also only give about 10-20 alloys and elerium; the biggest rake from them is the corpses and ~100 supplies. While smash and grab always gives ~30 alloys and Elerium if you get all the boxes, and ~70 supplies. Ever since WOTC added smash'n grab, your main source of supplies and alien material are going to be from smash'n grab missions.

Think about it. You're a insurrection group that just blew up a car bomb in front of a supply convoy of the governing regime. And you expect every soldier in the convoy to be completely off guard? No! They'd be highly on guard! 

If you're low on supplies, go liberate a region and then set everyone there to be on supplies, with an engineer advisor. If you need more recuits, do the same with that region, but with "recuit" and a high-rank soldier. (It's recommended in a play guide somewhere that you try to liberate your first region, in vanilla LW2, within the 2 months.

**Comment by Maebalzurakin** [comment]
Is there any point in having someone in a liberated region doing intel?  I don't think I have ever seen a mission generated in a liberated region.  They have not tried to take that region back yet.  Maybe intel would give you advance notice that they are coming?

**Comment by jmartinez989** [comment]
> 
> 
> Is there any point in having someone in a liberated region doing intel? I don't think I have ever seen a mission generated in a liberated region. They have not tried to take that region back yet. Maybe intel would give you advance notice that they are coming?

That is correct. Having rebels on intel in a liberated region can detect a pending invasion. What will happens is they will detect a supply raid in the liberated region that will start as 50% infiltrated (that's a bonus for a mission that was generated in a liberated region). You would do this if you suspect advent is going to launch an invasion soon from a neighboring strength 8 region.

**Comment by rrnwang** [comment]
You also continue to generate intel points in the liberated region, iirc.

**Comment by Grobobobo** [comment]
That Covert action was removed.
