### ISSUE TITLE
Civilian rescue rings disappear after first rescue

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#37]
On the main retaliation missions, approaching a rebel/civilian makes the rescue circles on the rest disappear, making it hard to see where the civilians are.

**Comment by tracktwo** [comment]
This was a bug in LW2 for quite some time. I don't remember exactly what fixed it, but the main place that looks relevant is in `X2TacticalGameRuleset.BuildLocalStateObjectCache` where the `UnitRadiusManager` is set up. In the base game it's hardcoded to only occur on missions with type "Terror". We extended this to instead use a config array of mission types, and added "Terror_LW", "Defend_LW", and "Invasion_LW", so that needs to be re-added to the CHL.

There was also a mod I made in `X2UnitRadiusManager` because vanilla apparently would disable the rings if the mouse cursor was too far away, so I made that configurable too. This code doesn't seem to exist in WOTC so that one likely isn't necessary.

I can't remember if just creating the radius manager was sufficient to fix this or not, but it was one piece of the puzzle. There's a kismet piece to this too that sets the rescue ring radius, but that only happens once on mission start. I think this is why they show up on mission start but suddenly disappear after a while. I don't know if the kismet one serves any real purpose since it doesn't respond to game loading and all the rescue visualization stuff is part of the pawns and so is outside the game state system.

**Comment by tracktwo** [comment]
A quick hack in xcomgame to restore the config works, but also requires a change in `X2UnitRadiusManager.Tick`. The radius manager will put rescue rings around any unit whose pawn has the neutral team. When civvies are rescued in LW2 their unit state gets a team swap, but the pawn doesn't, so the rescue rings stay on rescued civs. LW2 fixed this by testing if the underlying unit's team is neutral instead of the pawn's team. It could potentially also be fixed by also doing a team swap on the pawn too.

**Comment by pledbrook** [comment]
Should also check the new WOTC missions for rescuing soldiers/other VIPs. They have rescue rings that don't disappear and aren't Terror missions.

**Comment by pledbrook** [comment]
This is actually a vanilla bug that also exhibits on the Gather Survivors mission. And the rescue rings only disappear when you move a civilian you just rescued. Rescuing them doesn't make the rings disappear.
