### ISSUE TITLE
Game crashes after completing first mission

### ISSUE THREAD

**Issue by SkippieDippie** [long-war-2/lwotc#375]
After completing first mission, the load screen appears. However, after sometime the game just crashes.

Mods:
- Long War of the Chosen
- Highlander (the recommended one)
- Capnbubs' accessories

To recreate:
1. Start new campaign (Turn off "Tutorial" and "Lost and Abandoned")
2. Complete the mission

Notes:
- Long war 2 and Capnbubs accessories worked together perfectly without The War of the Chosen extension
- I already tried disabling Capnbubs' accessories, it still didn't work
- I will gladly give you the log if you tell me where I can find it
- Game version is Update 20181009

**Comment by pledbrook** [comment]
This isn't reproducible I'm afraid. Make sure you have unsubscribed from the community highlander on Steam, cleared out your Config directory, and also try moving your _Documents\my games\XCOM2 War of the Chosen\XComGame\SaveData\profile.bin_ file to a backup location (like the Desktop).

Is it definitely the LW2 Gatecrasher? In other words, do you start with 8 soldiers and it's a Troop Column/Maneuvers mission rather than a "sabotage monument" one?

**Comment by pledbrook** [comment]
The log can be found at _Documents\my games\XCOM2 War of the Chosen\XComGame\Log\Launch.log_.

**Comment by pledbrook** [comment]
Couldn't reproduce following the steps given. Almost certainly an environmental issue. Feel free to post the log here and follow up even though the issue is closed.
