### ISSUE TITLE
Advent MECs can bomb XCOM soldiers despite not having any clues about their position

### ISSUE THREAD

**Issue by TyborPL** [long-war-2/lwotc#386]
Advent MECs (blue and green ones) can target any XCOM soldier for bombardment even if those soldiers were far off and not in the line of sight of any enemy unit.

Got this happen to me a few times. Last one was when I was using two very fast shinobis to snach some crates on a smash and grab mission. The enemy pods were activated when I marked crates, then I split those two shinobis and dashed one to the evac that was prepared by a rookie left at the starting point, and dashed the second one a little bit around to lose line of sight. The first shinobi and the rookie evacuated during the next round (being seen by one enemy drone) and the second shinobi far out of sight dashed to the evac direction. On the enemy turn he was bombarded by a MEC despite no one could possibly seen him or have any clues about his position.

**Comment by jmartinez989** [comment]
This is intentional. The mec archer (green mech) and mech longbow (blue mech) are special super long range artillery mechs that can use their rockets from way out of line of sight. They just need to have proper vision of your units (another enemy has sight of you) and they can launch their rockets from just about anywhere. I don't even think there is a limit because I have been hit by their missiles from over 40 tiles away. Also their names are supposed to be a clue that they can do that.

**Comment by TyborPL** [comment]
The point is that they can fire at my soldiers even when no enemy has any vision of me. You can have your squad at the other end of the map and use Reaper as spotter for snipers. When the pod is activated by sniper fire, MECs can target my soldiers for bombardment even when whole enemy pod is just running around like headless chickens.

**Comment by PodliKirill** [comment]
The same is for priest stasis and viper poison. They can target you trought walls without LOS and any vision. Seems like many abilities can be activated without vision and even without LOS. They have to be activated and in range of abilities.

**Comment by TyborPL** [comment]
Looks like AI sees everything but is artificially handicapped to pretend that it is not. And because of a bug or lack of restriction some target abilities can be used even when it is against the general rules.

**Comment by jmartinez989** [comment]
> 
> 
> Looks like the AI sees everything but is artificially handicapped to pretend that it is not. And because of a bug or lack of restriction some target abilities can be used even when it is against the general rules.

So yeah I was mistaken in my last post. The mechs do not even really need line of sight to your units. The only requisite is that they be active. Once they are active the mechs will know where your guys are and can rocket them from anywhere basically. This works the same for xcom. You can shoot grenades or other long range weapons into fog of war where you know the enemy is and you can still damage them. Line of sight just makes it easier.

**Comment by Vulpertinger** [comment]
I know of instances of this happening in the early original LW2
https://youtu.be/mPV1fUCgbIQ?t=4m17s

It was supposedly patched out in the next Update 1.2, but I can't say if it really doesn't occur after that anymore.
"- Attempted Fix to Mec Micromissiles and Poison Spit targeting places with no visibility from anyone on alien side "

**Comment by rrnwang** [comment]
Regarding jmartinez989's comment, I have no real problem with this. However, there is still the teleporting alien bug! So sometimes, if you get super unlucky, you get the activated Archer and Longbow from across the map when 1 of their pod members get teleport-ed beside you.

**Comment by TyborPL** [comment]
> Regarding jmartinez989's comment, I have no real problem with this. However, there is still the teleporting alien bug! So sometimes, if you get super unlucky, you get the activated Archer and Longbow from across the map when 1 of their pod members get teleport-ed beside you.

Yes, I saw this one too...

**Comment by PodliKirill** [comment]
> Regarding jmartinez989's comment, I have no real problem with this. However, there is still the teleporting alien bug! So sometimes, if you get super unlucky, you get the activated Archer and Longbow from across the map when 1 of their pod members get teleport-ed beside you.

I had troubles with priests. When attempting to retreat you cannot hide beside walls/cars/etc - priest just do stasis through obstacles. Viper is the same - he can do poison. I've lost some soldiers during last campaign because of this.

**Comment by pledbrook** [comment]
One thing to bear in mind is that if any enemy unit can see any one of your squad, then they know where all the members of your squad are. Not saying that there isn't an issue here, but it's important to understand that basic fact in order to identify which situations are in fact bugs.

In addition, save files would make it much easier to track down and fix such issues, including the teleporting aliens one. Since I've never seen it, there's not much I can do to diagnose and fix it.

**Comment by rrnwang** [comment]
> In addition, save files would make it much easier to track down and fix such issues, including the teleporting aliens one. Since I've never seen it, there's not much I can do to diagnose and fix it.

My experience with the teleporting alien bug seems to be that the map spawns/moves more enemies to a location than the terrain is supposed to handle. LW is especially prone to it due to large pod sizes. When they teleport, they seem to always get teleported to where your soldiers start the map. Seems like a fail-safe of some kind...

**Comment by tracktwo** [comment]
The AoE targeting was fixed in LW2 with a pair of helper config options, see `RequireVisibilityForAoETarget` and `AllowSquadVisibilityForForAoETarget` and their uses in the LW2 sources. LW2 enables both of these flags.

**Comment by pledbrook** [comment]
Apparently LW2 implemented this as a highlander fix, so that's probably what we will have to do too.

**Comment by siath70** [comment]
I have had troops shoot my guys through high cover, Standing behind a wall two tiles back with all enemies on the other side of the wall.
On the reverse, I have had the ability to slash through a wall because I had sight from another soldier. The unit I could attack was behind a counter and behind a wall with no windows.
So something seems wonky with the LOS or valid attack system for both sides.

**Comment by aturaki** [comment]
as a  long side note to this bug, there is another annoying xcom2 vanilla bug that might add confusion to this bug.  Basically, if u have a unit hiding behind a 3+ tile full cover structure (car, wall etc..), the unit is in effect standing in the open without cover.  Enemies can therefore see the unit, and thus the AI knows where all ur units are.   There is another variation of this bug that involves running a unit through a closed door into a building that breaks LOS to all enemies.   In this scenario, the unit is also in the open without cover and visibile to the AI (even if u run the unit into some cover in the building).

**Comment by allenhu0912** [comment]
Not sure if related, but there's a similar issue with grenadiers. Even if no enemies can see you at all, grenadiers will happily shoot grenades at you around corners and up onto rooftops (and in one case, they broke the rules of physics and shot a grenade through a roof to someone standing on top).

**Comment by pledbrook** [comment]
Hopefully fixed with [this commit](https://github.com/long-war-2/lwotc/commit/b05b7c740754692be65b8babd4baf7e5f5ce6a5c)
