### ISSUE TITLE
Can the old supply outpost raid be added as a variation to resource seizing ?

### ISSUE THREAD

**Issue by Anxoczt** [long-war-2/lwotc#388]
After 75% of all crate raids are in Lost cities, where i cant use grenades, not even those that actually shouldnt be that loud (Like smoke or gas grenades). I do started to miss the old stockpile raid quite alot... where i go in, i make haste, kill everything and then try to get away with as much resources as possible before reinforcements arrive.

But i keep getting the lost cities constantly, for every non-lost city raid somewhere where i can use snipers i get 3-4 supply raids in those cities. Advent had all these years and still they have so many supplies there ?.

Lost cities are a problem on their own, not only its a dungeon where a pod can barge in to your position around every corner and this is very dangerous when they are on alert. You cant use grenades here and i do consider grenades to be very important in LW2, especially since most missions dont give corpses so its FFA with weaponry. But every grenade you use means more assholes to deal with later.

**Comment by TyborPL** [comment]
Same here, 90% of smash and grab is Lost city.

**Comment by BlackRose39** [comment]
Agree, I would enjoy seeing the original smash and grab mission implemented.

**Comment by MiserablePileOfBugs** [comment]
After playing LW2 so much, I actually prefer the new smash and grab because you have a lot more control over the mission. You can scout the map at your leisure and decide when the mission starts. And when you feel getting these last few crates isn't worth the trouble, you can evac on the spot.

The old S&G was too much of a RNG fest and fighting inside buildings sucks. Depending on the location of the enemies and the evac point, you could sometimes walk into a dead trap with no chances of escaping.

I agree that we should reduce the chances of getting this mission on a Lost City map.

**Comment by pledbrook** [comment]
It's tough trying to balance out the map selection. The base game seems a bit wonky in this regard anyway and it doesn't work well with the way LW2 spawns lots of missions, most of which you never detect or send troops on. That said, you shouldn't be getting the abandoned city map 75% of the time.

Anyway, we may try to resurrect the old smash and grab to add a bit of variety. Unfortunately it's non-trivial to port.

**Comment by Anxoczt** [comment]
My main grudge is the lost cities as they are deathtraps waiting to sprung. You cannot use grenades here and the maze architecture can turn to a deadly combination with enemies on yellow and red alert once the shootings starts.

I wouldnt actually miss the lost cities if they were rulled out of resource fetching altogether.

**Comment by BlackRose39** [comment]
#524 I think has already fixed this.

**Comment by pledbrook** [comment]
Added the old Smash and Grab a while ago.
