### ISSUE TITLE
Suggestion: equip technicals with rocket launchers and flamers

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#396]
I have found some interesting mods in steam workshop:
https://steamcommunity.com/sharedfiles/filedetails/?id=1775963384&searchtext=rocket+launcher
https://steamcommunity.com/sharedfiles/filedetails/?id=848571873&searchtext=flamer
Is it a good idea to integrate these to LWotC? Since those fancy XCOM gauntlets looks too unrealistic to me.

**Comment by Anxoczt** [comment]
I played the vanilla with that flamer mod.
An actual flamer that can hit people in cover with no perks and for full damage.

But alas, i dont think we should cram these in to LWOTC, they would turn Technicals in to gods of destruction. Rocket launcher pretty much negates their limited ammo (Since they could simply fill their inventory with missiles AND teammates could carry more) and flamer would make them in to a gods of DoT.

As great as it sounds, i think technicals are strong enough already with their alpha strike potential and ignition abilities, although i do feel that flamethrower is considerably inferior to the missile.

I would leave this to people themselves to mod it in if they want it.

**Comment by PodliKirill** [comment]
I disagree. Technicals in LW2 is fine. Good damage and AOE cower destruction abilities from rocket, but very limited amount of rockets - is ok. Ability to disable and damage through cower with flamer - with limited usage and aggression move because of short range - is ok.
But in LWOTC technicals is useless for me. Rocket has nerfed cower destruction ability, flamer should have good angle for damage in cower - both technical abilities is very situational and almost always is just useless. LW2 technicals with good cower destruction and good flamethrover is ok IMHO.

**Comment by Grobobobo** [comment]
Implemented in R with but beyond the scope of lwotc classic.
