### ISSUE TITLE
Sort out overwatch

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#4]
Overwatch was a little too strong in the original LW2 and could probably do with being weakened. It was a dominant strategy that allowed for the destruction of entire pods on the alien turn, often without any danger to the XCOM squad. It needs to either be less effective or more niche.

**Comment by pledbrook** [comment]
I think major issues are:

 * Cool Under pressure completely eliminates the aim malus _and_ allows for crits (which are more common for overwatch because the enemies are typically out of cover)
 * Cool Under Pressure makes Sentinel and Rapid Reaction both incredibly powerful relative to normal shooting, since you effectively get multiple "normal" shots often on flanked targets
 * Aim and crit stacking magnify the effects of the perks above

**Comment by pledbrook** [comment]
The new WOTC overwatch mechanics are making overwatch ridiculously weak right now. I'm seeing < 20% to hit, even from elevation. It looks like the calculations take into account cover, regardless of which tile an enemy moves to. I'm not sure that enemy overwatch suffers from the same problem, though.

This needs some investigation to work out what exactly is going on.

**Comment by MagSigeasol** [comment]
This WotC change has been discussed in detail in a number of forums. There is a mod that alters the behaviour back to the base game version, which includes the ability to step out of overwatch when at the edge of range. 

I believe the problem arises because the shot occurs in the tile the enemy commenced the move in, as opposed to the tile to which the enemy is moving. 

Note the aim malus should be operating correctly for the enemy. It changes the tactical game somewhat as you can use a soldier in high cover as a ghetto lightning reflex runner of overwatch shots regardless of pathing. It may require improving the group of overwatch abilities, or making a conditional one regarding improved shots against units in cover, though I have no insight on how simple that would be to code.

**Comment by ansabalirai** [comment]
I was not aware of the mod's existence to revert OW rules/behavior to vanilla. With many LW2 players hopefully switching to LWOTC, it might indeed need some getting used to. If the mod for reverting back to vanilla behavior works well and is preferred, it might be worth including in the list for integration in #67

**Comment by TheSwingman** [comment]
I think that if you spec into Overwatch, you shouldn't be punished for doing so. Mission timers on a lot of missions provide enough incentive against slowly crawling through the map and just using overwatch for most missions anyway. 

I dunno, if you're getting 20% shot percentages when you are at elevated positions, that's just too darn low.

**Comment by pledbrook** [comment]
So this issue is based on experience with high-rank overwatch specialists. They get a bonus to aim, plus crit, plus multiple shots on units that are typically in the open, plus hair triggers. They typically have 90-100% shots under these conditions, so setting up overwatch traps and drawing enemy units into them was just incredibly strong. Brokenly strong in my view. You could easily do HQ assaults without taking wounds using this approach. It's bonkers.

That said, WOTC behaviour on when overwatch triggers nerfs the technique to the point that overwatch is barely usable, so I definitely want to revert the behaviour back to how it was in LW2 before.

**Comment by ansabalirai** [comment]
@pledbrook That would certainly be a welcome change, although I wonder if Gotcha for WOTC would break or not? It is the one mod that I cannot live without since tile counting is stupid

**Comment by pledbrook** [comment]
Gotcha Again may already be broken with overwatch, considering a comment about its behaviour in the integrating mods issue. But yes, it did cross my mind. If that happens, I would seriously consider updating the mod, perhaps publishing it as a LW2 [WOTC] specific version.

**Comment by BlackRose39** [comment]
> So this issue is based on experience with high-rank overwatch specialists. They get a bonus to aim, plus crit, plus multiple shots on units that are typically in the open, plus hair triggers. They typically have 90-100% shots under these conditions, so setting up overwatch traps and drawing enemy units into them was just incredibly strong. Brokenly strong in my view. You could easily do HQ assaults without taking wounds using this approach. It's bonkers.
> 
> That said, WOTC behaviour on when overwatch triggers nerfs the technique to the point that overwatch is barely usable, so I definitely want to revert the behaviour back to how it was in LW2 before.

We could add back penalties for overwatch at inactivated enemy pods/from concealment. Is that what we should do for a start @pledbrook ?

This mod here, http://steamcommunity.com/sharedfiles/filedetails/?id=1132067065, "allows the normal reaction fire penalty to be applied to reaction fire shots fired from concealment." (But it also applies to taking shots at enemy pods wandering into an overwatch trap).

**Comment by pledbrook** [comment]
I'm confused. As I understand it, the reaction fire penalty is only removed for overwatch shots on reveal. In all other cases, the aim * 0.7 penalty still applies. The problem is that XCOM can get their reaction fire aim to very high percentages even _with_ the penalty.

**Comment by BlackRose39** [comment]
Apologies if the mod confused matters more, but mechanically wise, you're _concealed_, so the enemies don't initially know where the shots are coming from until they see you on reveal, so there's no penalties for XCOM taking shots on surprised enemies. After that though, it's fair game (penalties applies for now on) if you're not hidden.

The other thing we could do is increase the overall penalties of over watch shots (0.5 multiplier instead of 0.7, for example.) It might make the early game unmanageable, unless we change the hair trigger values so that the basic one makes it like early game, but the elite ones are reduced or compensated for the greater base overwatch penalties.

**Comment by allenhu0912** [comment]
I think current overwatch is mostly fine outside of alpha striking pods that walk into you. Maybe have overwatch deal half damage to yellow alert enemies. Also discourage ADVENT AI from trying to move unless it is flanked, if someone with high chance to hit is currently overwatching

**Comment by PodliKirill** [comment]
Overwatch is very random now. Your overwatch ranger can do 3 high crit chance shots - and can do 0 shots because of damage taking, suppression, etc. I'm using many overwatch specialist in the current run because i'm lucky with high aim specialists. But i have a loot of situations where just combat protocol is much more usefull. The same is with rangers - they can do 3 shots with rapidfire or gamble with 3 _potential_ shots by overwatch.
Overwatch is always a gamble. You can do a loot of damage - or do nothing.

**Comment by BlackRose39** [comment]
Now that I think of it, wasn't the "anti-beagle rush" suppose to counter this problem?

**Comment by scmantikor** [comment]
JL reverted the change firaxis made on the beagle maneuver and made it so that yellow alert would punish it

**Comment by PodliKirill** [comment]
Maybe remove 40% crit from flanking for the overwatch trapping not red alerted pods?

**Comment by pledbrook** [comment]
Leaving Overwatch as is for now. If there's a concrete proposal, we can create another issue. Currently this is just clogging up the issue list.
