### ISSUE TITLE
Specialist Full override cancelled out by Priest Stasis?

### ISSUE THREAD

**Issue by cshen6** [long-war-2/lwotc#406]
I see that Stasis from Priest can cancel out usual robot control & many other soldier effects in WOTC;
but I thought full override in LW shall give permanent control on robot that won't be cancelled out by anything.

However, I just did a network tower mission, where I succeed in full override on a robot, then the priest cast stasis on my specialist -- then the robot lost control and reverts back to the red enemy icon -- have to kill it the following turn, and I didn't receive the mec in resistance either.

**Is it supposed to work like that, or stasis should not cancel out full override??**

Another related issue for full override: the permanent controlled robot still can be targeted by own soldiers, it is a little annoying since I occasionally shoot them by mistake...

**Comment by jmartinez989** [comment]
As far as I know Full Override is basically the specialist version of Domination. Your specialist needs to have consciousness in order to keep the control of the mec just like how psi operatives and sectoids need to be conscious to be able to keep a unit mind controlled (though this is inconsistent with reanimation as it seems that even when in stasis units that reanimate something will still have control of said thing).

**Comment by Vulpertinger** [comment]
In the original LW2 Full Override remains if the Specialist dies or evacs, otherwise leaving with your Specialist would reverse the Full Override and that would be counterintuitive to what the perk is supposed be doing. I don't know how it behaves with other mental conditions, but it should be the same.

**Comment by jmartinez989** [comment]
> 
> 
> In the original LW2 Full Override remains if the Specialist dies or evacs, otherwise leaving with your Specialist would reverse the Full Override and that would be counterintuitive to what the perk is supposed be doing. I don't know how it behaves with other mental conditions, but it should be the same.

if that is the case then we may have to look into this. @cshen6 can you provide a save of this if possible for us to look at?

**Comment by cshen6** [comment]
> In the original LW2 Full Override remains if the Specialist dies or evacs, otherwise leaving with your Specialist would reverse the Full Override and that would be counterintuitive to what the perk is supposed be doing. I don't know how it behaves with other mental conditions, but it should be the same.

Yes! So far in LWOTC, Full Override is indeed always effective regardless of whether specialist dies or evacs, or any other mental condition already existed in LW2.
Since priest stasis was newly introduced in WOTC, I guess that may be why -- but the priest stasis is the only thing that nullifies it so far.

> if that is the case then we may have to look into this. @cshen6 can you provide a save of this if possible for us to look at?

I don't have the save file to reproduce this, since I encounter it just once last night & not sure whether that is a bug or not... but will save and upload one when I encounter this again.

**Comment by Grobobobo** [comment]
Fixed a while ago.
