### ISSUE TITLE
Suggestion about smash and grabs

### ISSUE THREAD

**Issue by siath70** [long-war-2/lwotc#409]
The smash and grabs on Lost maps are crazy.
The AI tends to spam grenades and the lost ramp up quickly.
Then add on top of that when the troops start dropping every other turn, it just gets stupid.
I had a match with 40+ lost and 30+ advent, there was just too much to shoot.
Put on top of that, the way lost maps are getting any crates it hard, I got 3, which was due to me not being able to run fast enough. No enemies soldiers with 16 moves and they couldn't get from one crate to the next in time.

My suggestions are:
1. Remove Lost maps
2. Make the advent pick up every three turns on lost maps

Then
Stop advent from spamming grenades, or reduce lost swarm pod sizes for lost maps. Would they not be just as careful about not calling swarms?

I don't need to get every crate, but on most missions I can get 50% of the crates usually.

**Comment by cshen6** [comment]
Totally Agree, Smash N Grab is difficult and tedious and hard to manage the time -- even not on lost maps! 
I am totally skipping Smash N Grab missions in LWOTC, does not worth the time at all.

Supply line raid & Troop Column raid are far better missions of same type -- they gave supplies & corpses & easier to manage.

I think it is better to either remove Smash N Grab, or add some very attractive post-mission rewards to it. Just like no soldier type in LW is useless or strictly inferior to others; 
there shouldn't be a mission type that is strictly inferior & no-one wants to do.

**Comment by ToastedAmphibian** [comment]
Huh, I have kind of the opposite experience with lost on smash and grabs. I intentionally call the buggers, mark the boxes, and then sneak off while the zombies and aliens shoot each other.

**Comment by cshen6** [comment]
Yeah that was my strategy in WOTC since lost was on map to start with --
and using reaper to scout the map can activate aliens & lost to fight each
other even before box marking.

Now lost only appears after aliens being alerted, I think, and there is no
corpse gain on Smash N Grab -- it is still easy to mark most boxes, get
some loot, and evac accordingly. But generally a difficult mission if I
were to try get all boxes & no-soldier injury on an ironman run -- it is
do-able, but this mission is just not as effective as supply raid & troop
column, in terms of mission time / consumed soldier resource / income.

**Comment by gen-martox** [comment]
that’s actually a mistake to fully scout the map as advent can only extract crates you have seen. Which version of lwotc are you using? On the newer versions I don’t find the mission that hard even with the lost.

**Comment by cshen6** [comment]
I am not playing Smash N Grab in LWOTC at all;
if they only extract scouted crates then that is a better deal.

In vanilla WOTC I am pretty sure they can extract unseen crates far away.

**Comment by jmartinez989** [comment]
Huh I have had the opposite experience with smash and grabs. I actually find it that scouting in as far as you can before activating is the best way to get all of the crates. Even with only 6 turns before rnfs I can usually get all of the crates before they even arrive.

The trick is to only mark crates when advent marks crates which leaves you with a dynamic of 1 turn of mostly just marking and one turn of mostly just fighting. When you scout in as far as possible before going loud you have a good chance of killing as many enemies  as possible before the mark phase. That way when the mark phase starts if you have killed all of the enemies you can mark as many crates to you  as possible.

I have been able to get 90%+ of the crates on every smash and grab that I have played. Of course this only works in low strength regions an mostly on extremely light smash and grabs (can also work on very light but anything higher than that and you will likely not be getting all of the crates unless you can kill everything super fast).

And as far as the lost go, I prefer those maps that they are on because then you can just purposely spawn them to make the aliens waste their time. All in all I think smash and grab is in a perfect spot right now.

**Comment by MiserablePileOfBugs** [comment]
@jmartinez989: 

I agree 100%. Smash & Grab is one of my favorite type of missions because of the required planning. Also watching the aliens getting swarmed by the lost is delectable.

**Comment by TheReigningKing** [comment]
You need to finish smash and grab missions before the timer finishes, so you shouldn't be seeing over like 15 enemies (based on 100% infiltration).

One thing I miss from LW2 is the loss of non-concealment.  Every mission starting with concealment is getting too similar as well.

**Comment by pledbrook** [comment]
I think the Supply Extraction mission is in an OK place, and there's the old LW Smash and Grab as well for variety.
