### ISSUE TITLE
Shaken soldiers can become haven advisers

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#461]
This makes no sense as Shaken soldiers are supposed to require time on the Avenger to recover. Haven advisers are not on the Avenger.

See my SSGT Grenadier in this save, who is currently Shaken and an adviser:

[save_BUG Shaken soldiers as haven advisers.zip](https://github.com/long-war-2/lwotc/files/3562459/save_BUG.Shaken.soldiers.as.haven.advisers.zip)

**Comment by ansabalirai** [comment]
I am perfectly fine with the change, but just wondering whether this is different from vanilla LW2? I think I remember being able to station shaken soldiers in havens. Not sure if they recovered while being an advisor since vanilla required the soldier to return uninjured and having gotten a kill in a subsequent mission to become unshaken.

**Comment by pledbrook** [comment]
You couldn't have Shaken soldiers in original LW2, could you? I thought it's a WOTC thing with mental states.
