### ISSUE TITLE
Rebalance XP on RNF-only missions

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#473]
RNF-only missions don't scale their XP award very well since it's scaled by alert, not by number of units.

**Comment by pledbrook** [comment]
Actually, RNF-only missions only awards slightly less XP than equialent GOp missions at the same alert level.

**Comment by Grobobobo** [comment]
Did we end up doing anything to it?

**Comment by wdanny69** [comment]
[line 689 in utilities_lw.uc

](https://github.com/long-war-2/lwotc/blob/c26ed030f300634ead462db37f64f380ff604dd5/LongWarOfTheChosen/Src/LW_Overhaul/Classes/Utilities_LW.uc#L689-L695)

handles xp that is built around having rnf instead of a pre set of enemies by emulating a preset count using a fixed amount (7) and the current region's alert level
