### ISSUE TITLE
Ever Vigilant activates pistol overwatch instead of rifle overwatch

### ISSUE THREAD

**Issue by Favid** [long-war-2/lwotc#496]
Give a Ranger Ever Vigilant and equip them with a pistol. When they take the overwatch shot granted by Ever Vigilant, they will use their pistol instead of their primary weapon.

**Comment by BlackRose39** [comment]
This is an intended vanilla behavior where a sharpshooter over watches with their pistol on Ever Vigilant which seems to be a similar behavior to one of the specialist's perks. If you read the description for the "Threat Assessment Protocol," it says that the sharpshooter will use their pistol instead of their sniper rifle. I think the reasoning was because of the two action points needed to use a sniper rifle. 

The logic behind this falls as this also happens with modded classes when they have a secondary pistol weapon regardless of if they have a rifle as their primary weapon. (Which only need a single action point to use). The only way for a primary weapon to be used as threat assessment is if they don't have a pistol whether it is in secondary or utility.

If we can override that behavior for both perks, whether with a new ini. file, and force primary weapons to be used for one or both perks, we can address this.

**Comment by Favid** [comment]
LW2 fixed this by making a Highlander change in XComGameState_Ability.EverVigilantTurnEndListener

Base game code:
```
OverwatchRef = UnitState.FindAbility('PistolOverwatch');
if (OverwatchRef.ObjectID == 0)
	OverwatchRef = UnitState.FindAbility('Overwatch');
```

LW2 modification:
```
FoundSlot = false;
SoldierAbilities = UnitState.GetEarnedSoldierAbilities();
for (k = 0; k < SoldierAbilities.Length; k++)
{
	if (SoldierAbilities[k].AbilityName == 'EverVigilant')
	{
		if (SoldierAbilities[k].ApplyToWeaponSlot == eInvSlot_PrimaryWeapon)
		{
			OverwatchRef = UnitState.FindAbility('Overwatch');
			FoundSlot = true;					
		}
		break;
	}
}
if (!FoundSlot)
{
	OverwatchRef = UnitState.FindAbility('PistolOverwatch');
	if (OverwatchRef.ObjectID == 0)
		OverwatchRef = UnitState.FindAbility('Overwatch');
}
```

**Comment by pledbrook** [comment]
Depends on [X2WOTCCommunityHighlander#685](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/685).

**Comment by pledbrook** [comment]
Veehementia ported Reliable Ever Vigilant to WOTC and that mod fixes this problem. I still want to fix it in the highlander, but it's less pressing now.

**Comment by bingo12345** [comment]
how about adding Reliable Ever Vigilant mod to recommended mod list?

**Comment by wdanny69** [comment]
since this issue can be addressed with the reliable ever vigilant mod, will close it
