### ISSUE TITLE
Continuous reinforcements appear erratically

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#50]
Sometimes reinforcements appear as multiple pods in one turn. Sometimes they appear in consecutive turns, even when there should be a gap.

**Comment by ansabalirai** [comment]
It seems this problem is much more prevalent. Using the logs, I noticed that the update reinforcement function (not entirely sure how that work internally) is called twice at the end of each turn, so the reinf bucket fills up almost twice as fast. The following line seems to appear twice in the log for each turn, whereas I think it should only appear once:
LWRNF: Turns Since Start: 

Note that it does not happen every mission, but I have not done enough missions to determine which ones it seems to always happen on. I would say this is probably a high priority to fix, since it can basically cripple your campaign.

P.S. I can paste the log from a mission if needed later

**Comment by pledbrook** [comment]
So I suspect this is down to an unexpected interaction between the vanilla mission Kismet and the continuous RNFs subsystem. `CheckForReinforcements()` appears to be called too many times, so that the internal turn counter for `XComGameState_LWReinforcements` is ahead of the actual turn timer. Which makes the reinforcements very aggressive.
