### ISSUE TITLE
Delay contacting new factions

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#515]
Although I understand that players enjoy having access to all the faction soldiers from the start, this involves some serious tradeoffs:

* It exacerbates the balance problem for a significant proportion of the early and mid games if faction soldiers are strong than normal ones (as most folks seem to like it)
* It makes the initial faction selection almost irrelevant
* It makes covert actions so much stronger because you have a greater selection to choose from for longer
* We lose a great option for differentiation between campaigns (related to second point)

We could just increase the rank requirements for "find the faction" covert actions, but I would prefer a more narrative driven approach: you can only contact them once you have contacted a region they operate in *and* have completed, say, Lib 2 to get their attention. This gives an addition incentive to expand, fits the story and you should still be able to get the second faction in the second month, third at latest.

This has the added benefit that the covert actions will be able to spawn missions in at least one contacted region.

**Comment by Anxoczt** [comment]
Understandable change although i have a feeling that RNG will shit on me by placing another faction in Australia when i am in Europe so reaching that will be impossible for a good chunk of the game.

Min/Max distance maybe ?.

**Comment by Hilera** [comment]
1º first mission
2º covert actions + rank
3º when appear 2nd chosen

**Comment by Phrozehn** [comment]
Please make factions take longer to contact! It allows us to use the time it takes to contact them be our effective cap, instead of a hard cap. It also means that campaign variety will be greatly improved, because one campaign I'll be Templar and Skirmisher heavy, but light on Reapers (More brute force maybe), changing gameplay significantly, vs a run where I contact Reapers first, and skirmishers last (More use of stealth). It's also significant that I'll only have one class for the first month or 2, vs having all three nearly from the get go.

I also like the idea of limiting our covert options this way as well. Again, great variety from capign to campaign. It seems like it's ALL upside in terms of game design.

My suggestions:

1) No hard cap: The effective cap is based on when we contact them and how long we have to rank them up. Sure we could get 5 templar, but how useful is that Seargeant Templar in Waterworld? By making it take longer to acquire factions we effective reduce the cap on the 2 we contact second and third. SO now our choice of priority is actually significant and impacting the whole campaign. Currently, our hard cap effectively meant nothing once we reach late game.

This way we get rid of a hard cap (bad design imo) by making it so that the later we contact a faction, the fewer we can fully train. It adds SO much more variety to a campaign, which is going to be super important for those of us planning to invest ANOTHER 1000 hours into Long War :) Phoenix Point will be doing something similar with their faction system. I love the idea of having to CHOOSE which special classes we'll have access to. It's another choice along the same vein as Mag rush vs Psi rush?

2) Hero units made more standard: Now my above suggestion also works better if we make hero units less... heroic... and more in line with other classes. I personally hate that a squad running a hero is just going to be better on average, because I included one unit instead of another (synergies and rank not considered). I don't like that a squad running a temp, a skirmisher, and a reaper is just going to be better on average than one running shinobi, assault, ranger, for example. I want my squads to be better because of the synergies I choose to incorporate, not because these 3 classes ae just better. It feels less like I'm making a choice about squad composition and more like a choice of which missions are lucky enough to just have it's difficulty reduced. Personally I prefer balancing squad rank and class distribution more than managing 3-5 premium soldiers that are better than the rest on average.

Hell, for me it feels like I'm actually being limited if I want to play optimally. I always want to make room for a Hero unit on any mission, unless I know it'll be easy. I want my squad's class composition to only be affected by the mission type, map type, and my wound timers. Not choosing which missions to deploy these units that just on average make the whole thing easier by virtue of just being stronger. The rank of my soldiers and their equipment should be the only thing telling me this unit is objectively better than others.


Recap: get's rid of hard cap, choices become far more important, and it effectively increases our diversity of squad compositions because we have a) more of the hero units while b) not feeling obligated to save them for hard missions.

Hope this wasn't too long. I'm very passionate about this project and love what you've done. I'd also love to donate if you guys have a Patreon!

**Comment by eraserman59** [comment]
I don't like the idea of having to contact the region of the resistance unless there's some limiter on distance just because that can be very rng. 

Personal narrative idea. Second group appears after either full liberation of a region or network tower assault. This represents the group approaching XCOM after XCOM goes loud. Third group appears either after a certain number of regions are liberated, or a certain number of golden play missions. This represents the third group revealing themselves when they believe that XCOM will really win this war.

**Comment by Grobobobo** [comment]
Already implemented.
