### ISSUE TITLE
The new Smash 'N' Grab is too rewarding

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#53]
Not only is it fairly easy to get most of the crates (partly because of better soldier mobility in LW2), but it's also a full sweep mission, which means you get corpses too.

**Comment by pledbrook** [comment]
The first priority should be to make this an evac mission and remove the sweep objective. Whether it should be a fixed evac or a deployed evac is up for debate.

This mission probably needs reinforcements as well, although I don't know when they should trigger. We could incorporate a timer with continuous reinforcements, or perhaps just launch continuous reinforcements a fixed number of turns after the aliens see XCOM.

Speaking of which, ADVENT should not be recovering crates until they see XCOM, not when XCOM loses concealment. It's stupid that crates start being recovered just because an XCOM soldier walked through a door and lost concealment, even with no aliens/ADVENT in sight.

**Comment by ansabalirai** [comment]
So, as I mentioned in Discord earlier, if the idea is to replace the LW2 equivalent of logistics/Smash and Grab, one way could be to just make it timed, with reinforcements dropping after a certain number of turns, every turn (just like LW2). It also makes some narrative sense since you are raiding a supply depot after all. That will also make it evac only, so no salvage. 
The other way could be to keep it as is, but XCOM will have to evac after the mission and reinforcements starting after you break concealment (so kind of like other destroy relay missions). 
In any case, the loot from the crates should be similar to the crates in the LW2 equivalent.

**Comment by pledbrook** [comment]
@ansabalirai Can you remember what the differences are between the old Smash 'N' Grab rewards and these ones?

**Comment by MagSigeasol** [comment]
Having played 2 of the new ones, the old version had a few key differences.

1) as discussed, reinforcement timer was immediately counting down upon entering, meaning speed was critical;
2) the loot was only obtained by a soldier picking it up and carrying to evac. 1 box per soldier, so you could end up in a situation where 4 soldiers could not take all 5 or 6 crates;
3) the crates would be known to Xcom at the beginning;
4) evac was fixed, usually close to where you come in, meaning it was get in, get the goods, and haul it back (fitting with the in and out theme;
5) as stated above, no corpses as it wasn’t a sweep;
6) current version is often a layout of an open base. Old version was usually a building and the goods were inside or on roof.
7) much smaller number of crates available.

Reducing crate numbers, reinforce countdown immediately, 1 soldier per crate, and fixed evac should balance the mission significantly. I would also remove the sweep element so that corpses were not recovered.

**Comment by ansabalirai** [comment]
As mentioned above, the main issue is the reinforcement timer and squad concealment. I kind of like your approach that the crates are not picked up by advent until xcom is spotted, but once spotted, reinforcements start ticking down. I guess the question is whether we want to utilize the WOTC style crate pick up or revert back to LW2 S&G? IMO, it would be better to use some of the features from WOTC, i.e. shared crate pickup and squad wide concealment, while keeping reinforcements, no salvage and fixed evac from LW2. Of course, it all depends on how hard it would be to implement

**Comment by pledbrook** [comment]
Right, difficulty of implementation is a significant factor at this stage. The whole reason this mission replaced the Smash 'N' Grab is because of the difficulty of porting the latter. There were various hacky elements to get it working.

What might be relatively easy to configure is the rewards (perhaps drop the PCS/weapon attachment rewards and reduce the resources). It might be relatively easy to reduce the number of crates, but it's worth bearing in mind that you're racing against ADVENT in this mission, so you could end up with very few.

Anyway, I need to look into the details of the mission to see how difficult it is to implement various options. At a minimum, though, I'll definitely make it an evac mission and remove the sweep objective. That fits with it being a guerrilla op, amongst other advantages.

**Comment by MagSigeasol** [comment]
Big fan of minimising effort and maximising reward. In this case, I would be inclined to keep the new version and adjust those elements most simple to adjust to bring the risk v reward ratio in line with the LW2 SnG missions.

I recall that SnG was implemented after the first release and was introduced as a means to assist in resource gathering. They were desirable due to the constant lack of resources at higher difficulties.

One benefit of the revealed start and the reinforcement timer was that there was no time or adequate means to establish a solid ambush on advent. I wonder if there is a way to delay Advent securing loot boxes for the first few turns, or otherwise perhaps just balance around the fact that, while a lot of boxes are available, you cannot expect to get many unless you put your soldiers at risk by dashing towards the crates. 

The number of crates could perhaps remain high if the loot per crate was reduced. I believe a fixed evac near the start would also increase the risk of the mission and require decisions on how hard and fast one wanted to go to obtain loot Reinforcements are almost mandatory on this as the sweep is too simple.

**Comment by Kazanir** [comment]
About to play through one of these. It's worth noting that S&G in 1.3 differed significantly from the normal LW2 reinforcement timer -- there was a relatively short turn timer compared to other missions, but reinforcements began immediately after it expired and aren't present before hand. This means you basically have those X turns to try to move up and clear the 3-4 pods and then boogey your soldiers in to grab the crates for the last couple turns, or while fighting off reinforcesments as you get to the fixed evac. Being able to see the crates through Fog of War helped here also.

**Comment by ansabalirai** [comment]
Even if we keep the current format, the current rewards are basically equivalent to a supply raid with 10-15 enemies, including bodies) and should be reduced. Due to concealment, I have been able to scout all chests and basically sit on crates within moving distance of other crates to tag as many as possible on the turn I break concealment. Have managed to get 10 crates 2 out of 3 times. I wonder if increasing the number of crates advent marks in a single turn is possible?

**Comment by Ronar1** [comment]
Current rewards definitely are too much. On Legendary, the player can consistently get like 10ish crates per mission which translates to roughly double the amount you got from the previous smash and grabs. Corpses definitely shouldn't be offered. Either scale down the rewards from each crate or reducing the number would be the easy implementations. The numbers that make most sense would be half crates or half rewards. Can be different on other difficulties, I don't know how those ones will be.
