### ISSUE TITLE
Certain aliens are too aggressive

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#533]
This may be my personal bias, but I'm seeing ADVENT troopers intentionally walking into a flank, on their turn, to take a shot on one of my soldiers in cover.

The most obvious example is that I flanked a Naja with my Assault, and the Naja simply took a shot at him. In LW2, Najas are guaranteed to prioritize moving out of a flank over almost everything else, including (iirc) taking kill shots on uncovered targets

**Comment by nightmaRok** [comment]
Its like LW2 works, yellow alert pods can shot and easy kill some one at thair turn.
https://www.ufopaedia.org/index.php/Mechanics_(LW2)

In Long War 2, enemy vigilance is more complex than in vanilla.

Green Alert Mode
Green alert level is most commonly the beginning of a mission when a squad is still in concealment. Advent has no idea that XCOM has infiltrated and as such, is on low alert. A pod activated on the alien turn in this state may take defensive actions (each unit has a percentage chance that scales with difficulty) such as hunkering or overwatch on activation, but will not make any offensive moves. In other words, they will not get a chance to take a free shot at XCOM.

Yellow Alert Mode
An enemy pod at Yellow alert level is not activated yet. However, it is aware of XCOM activity in the area due to sound from rocket/grenade explosions, gun shots, yelling civilians, or by finding the corpses of dead allies. Pods at this alert level will move toward any suspicious sounds they hear. If a pod is activated on an enemy turn, they may take opportunistic shots at XCOM or perform other such actions as they scamper for cover. Patrols in yellow alert run instead of walk, and may take certain actions (such as a Sectoid reanimating a corpse) even when not activated. You can use sound to create a diversion and draw pods away if you are attempting to stealth a mission or draw pods into your overwatch traps.
See the Sounds subpage for details.

Red Alert Mode
This is an activated pod.

**Comment by TheReigningKing** [comment]
@nightmaRok He's not talking about activations, he's talking about active pods that are putting themselves in disadvantaged positions to shoot at his soldiers.

In LW2, you could "hack" certain types of enemies by causing them to move rather than shoot. One specific example is the Naga b/c they required 2 AP to shoot and flanking them made them move first.

**Comment by pledbrook** [comment]
I would need a save for this. Najas have moved away from being flanked in my games.

**Comment by ansabalirai** [comment]
I assume you are not running any AI mods. I have seen some of them change AI trees for enemies to prioritize killshots rather than run away from a flank (which makes things a lot more refreshingly interesting IMO)

**Comment by allenhu0912** [comment]
I think you're right, but it's really difficult to judge when a killshot by the alien is possible, unless you have a knack for memorizing damage ranges incl. dark event upgrades for all the different tiers of enemies. Aliens should definitely prioritize shooting the guy they can OHKO, but they shouldn't walk into or stay in a flank to do so

**Comment by pledbrook** [comment]
Not sure this is still relevant, especially as various AI tweaks have already been made.
