### ISSUE TITLE
Integrate the Chosen

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#54]
This is the biggie. The Chosen should probably be properly integrated into the mod at some point, since they are the titular part of the WOTC expansion. Plus some folks like them.

Some options:

 * Rescale them so that they don't die so quickly considering how much stronger LW2 soldiers are than their vanilla counterparts
 * Limit them to certain types of missions (like the Alien Rulers)
 * Scale their chance to appear inversely with infiltration
 * Make their strongholds challenging in the vein of XCOM:EW eXalt HQ raid

An important decision to make concerns when the Chosen should be activated. Proposals:

 * After the first liberation
 * After Blacksite
 * From the start

Other notes:

 * Chosen can be excluded from mission sources, via `ExcludeChosenMissionSources` under the `[XComGame.XComGameState_HeadquartersAlien]` heading in _XComGameData.ini_
 * The decision on whether to add a Chosen to a mission is made by `XCGS_HeadquartersAlien.AddChosenTacticalTagsToMission()`

**Comment by ansabalirai** [comment]
Ah, so that is why I have not encountered them in two months.
In my opinion, it is ok for them to appear in timed missions, but the chance is based on squad composition. Scaling their stats is whole different ball game, but we need to be able to play with them to figure out if it is really easier to handle them compared to WOTC. I wonder if there can be a way to know beforehand if chosen will appear in this mission (like it does in WOTC), or whether it would be too OP.
In any case, it would be fun to have them in the mod and if it does not fit the theme or work well with infiltration, maybe there can be an option to remove them from the game later on.

**Comment by yoshimo** [comment]
For timed missions, didn't the base wotc game pause the timer ticking down when a chosen entered the scene?

**Comment by pledbrook** [comment]
Yes. And that should be reflected in most of the Guerrilla Ops in the port at the moment.

**Comment by pledbrook** [comment]
Idea from Skarlightcrimson: have a covert op or mission that recovers intel on a Chosen's weaknesses.

**Comment by SirMrMister** [comment]
On top of that, you could reward killing them  on a regular mission with guarantiing they won’t appear again for some time while they regenerate (you can always argue hat when you assault their citadel the sarc is operatin in non-sustainable overdrive). This palliative measure sounds fitting to Long War.

I do like the idea of correlating their appearance rate to lack of infiltration. I’d also really like if LWOTC could eventually integrate https://steamcommunity.com/sharedfiles/filedetails/?id=1619292810 with the items rebalanced accordingly, to further make each campaign slightly less predictable.

**Comment by ansabalirai** [comment]
Regarding the idea to integrate the chosen award variety mod, the rewards are quite interesting but seem a bit OP. I guess making the chosen suitably tougher such that assaulting their stronghold would be akin to exalt hq raid (and you are very likely to lose someone) can maybe balance it out, but I would suggest it as a low priority for now if that is alright

**Comment by SirMrMister** [comment]
I agree in that I cannot comment in the balance of every item in that mod, but my point was more on the idea of it: Having there be multiple unique reward items for felling each chosen, but limiting those you get per campaign to one or two chosen (heh) randomly from each chosen's list.

Balancing would come later, but I'd like to know if others are also fans of the idea. If anything, item-specific balance would become less of an issue due to the non-guaranteeness of each item, which would also help hinder class balance disparities when you are not guaranteed an OP only for your snipers.

**Comment by yoshimo** [comment]
I think the idea of that mod is good although i currently don't see why it is necessary to merge it into LWotC? What is different compared to installing that mod on its own and making sure it works together?

**Comment by ansabalirai** [comment]
I think the motivation was to scale chosen difficulty correspondingly alongside the rewards, so there is a risk/reward balance. At least that is what I think the general theme of incorporating an existing mod specifically within this project is. But ofc it is up to @pledbrook to decide ultimately :)

**Comment by pledbrook** [comment]
The general aim of "integration" is to get a mod or feature working within the context of Long War 2 in terms of code, gameplay and balance.

How that integration is implemented is a secondary concern, but my current rules of thumb are:

 * If a mod needs patching, it's merged/bundled with LW2
 * If it works as is and is something everyone should be using, then it gets added as a dependency ("required" on Steam I think)
 * If it's something a few people would like, then we potentially make changes to LW2 to support it, but don't make it required.

So, that's "bundled", "dependency", "supported". Make sense?

**Comment by SirMrMister** [comment]
I'd further split "bundled" in "bundled because code needs integration for compatibility" (call it "integrated") and "bundled because though it works as-is it needs rebalancing for LW2" (call it "incorporated"). In this case (unless there i a code conflict I don'g know of) it should be in "supported", with possibility of "incorporated" for finer LWOTC-specific balancing.

**Comment by SirMrMister** [comment]
I’d also suggest brainstorming into how to implement the chosen into LW2’s ADVENT Strategy process, but that should be worth opening as a different issue.

**Comment by frigle** [comment]
I think it will be better to integrate them after first region. Because it will be good for ENT. They are (Chosen) to big for little rebellian group, but after first region, they will see the the Danger of Advent. 
P.S. sorry for misstakes, I'm not from native speaking country. 
P.P.S. Great job, I'm exited to help with my favorite mod

**Comment by yoshimo** [comment]
Playing the wotc game itself it is less of a threat when a chosen appears than when i encounter one of dr. valens test subjects.
The gap between both surprises is too wide  already imho. I think Chosen should be a little bit stronger and valens creatures a bit less deadly.
I think we should keep the chosen around longer by making their hideout more demanding to discover while toning down their progression of knowledge

**Comment by The13Inquisitor** [comment]
Not sure how feasible it'd be, but would making the Chosen a Second Wave option be viable?

Like, give you the option of having them or not? Or use Lost and Abandoned as the trigger for them?

**Comment by jmartinez989** [comment]
> Playing the wotc game itself it is less of a threat when a chosen appears than when i encounter one of dr. valens test subjects.
> The gap between both surprises is too wide already imho. I think Chosen should be a little bit stronger and valens creatures a bit less deadly.
> I think we should keep the chosen around longer by making their hideout more demanding to discover while toning down their progression of knowledge

In LW2 the rulers are already super nerfed. In LW2 (and by proxy lwotc) they don't take an action after you take an action, they only get a chance at getting an action. If you have the frost bomb you can freeze them and then just kill them. I've already done that to all of the rulers.

I definitely agree that the chosen need to be buffed a bit, at the very least they need some more health since XCom tends to hit harder in lwotc.

**Comment by pledbrook** [comment]
@The13Inquisitor Potentially. Simply enabling the Lost And Abandoned mission should already activate the Chosen. But I think it might be hard to balance the game for both with and without Chosen. Perhaps the benefit of having the Chosen active could be access to the hero factions.

**Comment by yoshimo** [comment]
If you wanted lw without chosen, you could always go back to pavonis original addon and the base game. I wouldn't put playing without them as an option.

**Comment by pledbrook** [comment]
That's unfair as it completely ignores the massive performance improvements in WOTC.

**Comment by The13Inquisitor** [comment]
> That's unfair as it completely ignores the massive performance improvements in WOTC.

My thought process exactly.

On the opposite end of the spectrum, for masochists looking for a real challenge, a SWO that turns off the Hero Factions but keeps the Chosen active would probably go over well.

Mutual exclusivity has its charm but having the Factions and Chosen able to be independently turned on or off has its appeal as well:

Like, if you wanted a challenging campaign with just the Chosen or a campaign that was all about catharsis and a whole lot of payback with the just the Factions.

Just food for thought. Agreed the Chosen could do with a buff though.

On a related topic, maybe tune their spawn rate to once a week each?

**Comment by yoshimo** [comment]
Yes it is, but i needed you to say it. Giving reasons for certain design decisions is important.
I think we should focus on balance with Chosen primarily and after that see if it falls apart without chosen.
Yes lw2 before wotc had bad moments, when you get stuck under the avenger after a mission.
I feel the need, but the focus should be WITH chosen in terms of dev priorities.

**Comment by The13Inquisitor** [comment]
Fair points. 

Thought it went without saying though, so my bad for not elaborating.

**Comment by Aurelicornus** [comment]
I buyed the expansion only some time ago and I didn't played it deeply, but my thoughts:

* Rescale them so that they don't die so quickly considering how much stronger LW2 soldiers are than their vanilla counterparts.

Some tweaks sounds fine, if not needed, to put at par them like other units with the mod.

* Limit them to certain types of missions (like the Alien Rulers)

Absolutely. LW2 has longer turn limit, but really I don't want see them in some missions where you have the crushing hurry to move into evac zone. I would avoid to put them in Vip rescue, Vip extraction and Jailbreak missions. Timer here is very tight, and the Chosen makes me lose a lot of time for deal with them; for the game setting, the backgrounds of these missions usually are "small windows of opportunity" where the Resistence can strike, therefore is hard that the Chosen can plan an ambush in these situations.
Maybe some of these recovers could be traps of the chosen to lure Xcom uncovered, but in this case I would put these chances very low, maybe tied with the "trap missions" if the players performs very well against Advent: chances that you meet here should be very low for gameplay purposes for me.
The recover objects and hacking Advent terminal missions could have a slightly more chances to see a Chosen: in these missions once you complete the main goal the timer stops, leaving you enough time to deal with the Chosen, and the main pressure for the player is prioritize finishing the main goal than fight them. However I would stop reinforcements in these missions as long the Chosen is in the field, because in these recover missions the reinforcements sent after completing the main goal are very quick, and the player can be unfairly overwhelmed if the Chosen are around. However I think some can like the challenge, and I would put an option to turn on and off the Advent reinforcement while Chosens are active in a mission in a Second-wave fashion option. 

Instead I would like see the Chosen present in Haven assaults instead, like in Vanilla. In one playthrough the Assassin let herself flanked by Haven militia, and beaten to death by them, hilarious :D

* Scale their chance to appear inversely with infiltration

Sounds a very good idea and in style with LW2 mechanics, but I would like suggest to implements the details above: some missions should have anyway a lower chance that the Chosens go in the field for avoid to stack overwhelming the players.
Maybe is better put the chance the Chosen appears in these mission as Second Wave option? Editing the .ini seems fine thought, but I believe not everybody feels fine to deal with codes, and if possible the Second wave options, if possible, could meet the needs of these users for tweak the gameplay experience.

* Make their strongholds challenging in the vein of XCOM:EW eXalt HQ raid

Sounds fine for me. WotC offers a lot of opportunity to upgrade your soldiers that an revised "HQ" assault would be a challange without overwhelming the player with extreme odds (meaning "you can win this one if you are really well prepared").

* An important decision to make concerns when the Chosen should be activated. Proposals:
    After the first liberation
    After Blacksite
    From the start

After the first liberation sounds the better choose. First, you had the time to build a good rooster of fighters that have enough perks to deal with the Chosen, like have already contacted the three factions (and their units in your rooster), some equipment like the Alien Hunters weapons, the Spark, etc. From gameplay standpoint, if the Player have the resources to win the Liberation mission, it has the resources to fight the Chosen.

Have the Chosen active from the start I think stacks an odd too heavy for the player, if I think them buffed with the Long War gamestyle. The Blacksite mission is done after a "lot of time" in Long War 2, and at that point the Player, if is very active with missions and research, can be very foward to the tech tree (Tier 2 equipment and DLCs missions already completed) and soldier training that the Chosen aren't threatening anymore.
The first Liberation seems for me a good point in terms of gameplay balance and experience.

**Comment by Aurelicornus** [comment]
> For timed missions, didn't the base wotc game pause the timer ticking down when a chosen entered the scene?

Indeed I would keep this behavior, for gameplay balance and experience. The Chosen are the player's nemesis and being pushed to deal with them AND evac at the same time is a bit anticlimatic for my gameplay experience: I like see the Chosen encounters like duels, and I dislike interrupted duels. :D
However I think this detail could be turn on or off with a "second-wave options" for those players that wants an additional challenge in the play (timers ticking while Chosen are in field).

**Comment by Aurelicornus** [comment]
> A Idea from Skarlightcrimson: have a covert op or mission that recovers intel on a Chosen's weaknesses.

That's sound very good, and improves the utility of Cover ops other than recover loots and buffs your soldiers. ;)
Also, maybe adding a Cover ops that detect if a Chosen is preparing to show up in one of the mission for some weeks, with a warning in Sitrep notes (like done with the Lost, Psionic storms, or other mission modifications) if possible.

**Comment by Aurelicornus** [comment]
> On top of that, you could reward killing them on a regular mission with guarantiing they won’t appear again for some time while they regenerate (you can always argue hat when you assault their citadel the sarc is operatin in non-sustainable overdrive). This palliative measure sounds fitting to Long War.

I like this detail, is very fitting to LW2 that introduces "cooldowns" to other gameplay elements. 
If possible, maybe the delay until their next time could be tied to the same variable that governs the Avatar project speed: more damages you are able to deal to Advent and more you are able to slow down the Aliens in other areas, both the Avatar projects and the Chosen regeneration, because they must divert resources to repair the damages you have done. I think is a good reward for the players that are able to play well the game.

**Comment by The13Inquisitor** [comment]
> > A Idea from Skarlightcrimson: have a covert op or mission that recovers intel on a Chosen's weaknesses.
> 
> That's sound very good, and improves the utility of Cover ops other than recover loots and buffs your soldiers. ;)
> Also, maybe adding a Cover ops that detect if a Chosen is preparing to show up in one of the mission for some weeks, with a warning in Sitrep notes (like done with the Lost, Psionic storms, or other mission modifications) if possible.

There's already a mod for that, I believe. The cost of it's rather expensive in terms of resources, if I recall, not to mention risky.

**Comment by Aurelicornus** [comment]
> I’d also really like if LWOTC could eventually integrate https://steamcommunity.com/sharedfiles/filedetails/?id=1619292810 with the items rebalanced accordingly, to further make each campaign slightly less predictable.

Sounds a good idea, not only for adding variety, but also fits the reward to each unique playstyle. :)

**Comment by Aurelicornus** [comment]
> > > A Idea from Skarlightcrimson: have a covert op or mission that recovers intel on a Chosen's weaknesses.
> > 
> > 
> > That's sound very good, and improves the utility of Cover ops other than recover loots and buffs your soldiers. ;)
> > Also, maybe adding a Cover ops that detect if a Chosen is preparing to show up in one of the mission for some weeks, with a warning in Sitrep notes (like done with the Lost, Psionic storms, or other mission modifications) if possible.
> 
> There's already a mod for that, I believe. The cost of it's rather expensive in terms of resources, if I recall, not to mention risky.

Do you have a link? Do you think is good for a possible integrations?

**Comment by Aurelicornus** [comment]
> > That's unfair as it completely ignores the massive performance improvements in WOTC.
> 
> My thought process exactly.
> 
> On the opposite end of the spectrum, for masochists looking for a real challenge, a SWO that turns off the Hero Factions but keeps the Chosen active would probably go over well.
> 
> Mutual exclusivity has its charm but having the Factions and Chosen able to be independently turned on or off has its appeal as well:
> 
> Like, if you wanted a challenging campaign with just the Chosen or a campaign that was all about catharsis and a whole lot of payback with the just the Factions.

Agree. I think the better choose is leaving the player how they would like play the game. My suggestion is add a Second Wave option where you can turn on-off the Chosen and the Factions, leaving the player what they like play in the campaign (similar to "United Humanity" Second Wave option in Long War for Enemy Within, that disables Exalt).

**Comment by The13Inquisitor** [comment]
> > > > A Idea from Skarlightcrimson: have a covert op or mission that recovers intel on a Chosen's weaknesses.
> > > 
> > > 
> > > That's sound very good, and improves the utility of Cover ops other than recover loots and buffs your soldiers. ;)
> > > Also, maybe adding a Cover ops that detect if a Chosen is preparing to show up in one of the mission for some weeks, with a warning in Sitrep notes (like done with the Lost, Psionic storms, or other mission modifications) if possible.
> > 
> > 
> > There's already a mod for that, I believe. The cost of it's rather expensive in terms of resources, if I recall, not to mention risky.
> 
> Do you have a link? Do you think is good for a possible integrations?
> Resource intensive I think is right, after all they are the player nemesis and they should be a challange... tweaking them for WotC is another thing thought.

Right here: https://steamcommunity.com/sharedfiles/filedetails/?id=1132573074&searchtext=Reveal+Chosen+Weakness

**Comment by SirMrMister** [comment]
Alterd-Rushnano just released [[WotC]LW2 Chosen Perk Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=1763061909), which implements some of LW2's perks as possible strengths for the chosen. I think flat-out integrating that mod is a good step towards Longwarizing the Chosen, at least variety-wise.

Summary of the new possible chosen strengths:
● Infighter
"Chosen Gain 25 dodge against attacks within 4 tiles."

●Will to Survive
"Chosen take damage reduced by 1 when attacked through in cover. "

●DepthPerception
"Chosen Gain 5 aim and reduce Xcom's'dodge by 25 when at a higher elevation than your soldier."

●HardTarget
"Chosen Gain 3 dodge per soldier thay can see, up to a maximum of +30."

●Bring Em On
"Chosen Gain +1 damage on critical hits for every two soldier thay can see, up to a maximum of +8."

●Tactical Sense
"Chosen Gain 3 defense for each soldier thay can see, up to a maximum of 15 defense."

● Lone Wolf
"Chosen Gain +10 aim and +10 defense when 7 or more tiles distance from any advent and alien" 

●Aggression
"Chosen Gain +5 critical chance for each soldier thay can see, up to a maximum of 30."

●CombatFitness
"Chosen Gain 4 aim, 1 mobility, 2 HP, 4 will, and 4 dodge."

●Overprotection
"When Chosen is deadly damage, the Elder appears immediately and protects them in a stasis state." (= same as Sustain)"

The mod also makes some other chosen-specific changes, but the extra strengths are the good stuff I'm mentioning for now.

**Comment by pledbrook** [comment]
Done.
