### ISSUE TITLE
Launching the mission early

### ISSUE THREAD

**Issue by Onji24** [long-war-2/lwotc#540]
The doesn't appear to be a way to launch the mission early.

**Comment by pledbrook** [comment]
I think your installation may be broken considering the issues you've raised. Do you have screenshots? Have you followed the [troubleshooting guide](https://docs.google.com/document/d/1EEZqmzCQQoprh3sDFZQZyiuyRE8I_lsA7Z8pHTSRuzU/edit?usp=sharing)?

**Comment by cshen6** [comment]
That was exactly the same issue I had when I first installed back to Alpha stage-- it is because the highlander was not properly installed, i.e., the steam workshop highlander was still in effect, not the downloaded highlander.

Make sure: 
1. steam highlander is un-subbed; 
2. delete DefaultModOptions.ini under: Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\XComGame\Config
(if it still does not work, delete the whole config folder)
3. delete everything under: Documents\My Games\XCOM2 War of the Chosen
4. verify file integrity via steam so these deleted file/files get re-installed. 
5. follow the other steps to install LWOTC and Highlander into the mod folder, and start game twice.

That shall fix all the strange behaviors.

**Comment by Onji24** [comment]
Thank you for the help all works now as it should!
