### ISSUE TITLE
Reaper's Precision Shot uses 2 AP on T1 weapon (Vektor Rifle), and 1 AP on T2 weapon (Temnotic Rifle)

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#548]

**Comment by nightmaRok** [comment]
I test it and its work fine, on T1 and on T2 rifle precision shot end turn, only thing i can see its chance to reveal 10% and on Temnotic Rifle blue icon not yellow

[save_Reaper_precision_shot_T2_1.zip](https://github.com/long-war-2/lwotc/files/3619963/save_Reaper_precision_shot_T2_1.zip)

![Reaper_precision_shot_01](https://user-images.githubusercontent.com/51829747/65022947-8e492680-d93a-11e9-9d57-7b06306b0b86.jpg)
![Reaper_precision_shot_02](https://user-images.githubusercontent.com/51829747/65022948-8e492680-d93a-11e9-8593-73b53848398a.jpg)

**Comment by pledbrook** [comment]
Yes, the 10% reveal is a thing. Very weird. @jmartinez989 Do you know if Precision Shot is supposed to cost 2 AP on Reapers? It's very hard to take if it does, because Reapers are almost always moving and don't have the advantages that Sharpshooters have in shooting through cover. On the other hand, a 1-AP cost makes it a very strong perk considering the crit damage.

And thanks allenhu0912 for picking up the discrepancy between Vektor and Temniotic rifles. I had noticed the 1-AP cost on my Reaper but hadn't made the connection to the tier for the gun.

**Comment by allenhu0912** [comment]
I think 10% reveal is a bug. Basically the game does not recognize Precision Shot as an attack with your weapon. IIRC, if you try to call for evac or hack an objective with a Reaper, there is a 10% reveal chance. Attacks, on the other hand, have 50% reveal chance on first try.
