### ISSUE TITLE
Locked On Bug

### ISSUE THREAD

**Issue by ToastedAmphibian** [long-war-2/lwotc#576]
Seems like having another xcom member take an action in between the two shots cancels Locked On bonus. In the attached save, Frosty is Locked On to the viper due to an OW attack. If you take 2 shoots immediately, both get the locked on bonus, but if you have any other xcom member attack, OR trigger the muton's overwatch, she loses the bonus. Happens if you take the shot before her first shot, or her second shot, so Light Em Up does not seem to be the cause.

[save_Locked On Bug.zip](https://github.com/long-war-2/lwotc/files/3637205/save_Locked.On.Bug.zip)

**Comment by eraserman59** [comment]
What is happening is that Locked on is not tracking the shots of the soldier with locked on, but rather just shots in general. 

When I tried your save, I had the gunner shoot the other viper that frosty could see, and the locked on bonus transferred to the second viper

In my attached save there is a resistance member with locked on as a perk due to promotion. If you look at the info preview of his shots, you'll notice he does not have any locked on bonuses (which makes sense, he didn't shoot last turn and instead threw a grenade). Take a shot at the 4 hp enemy with a random soldier ( I used the one behind the car) then check the info preview again. You'll notice he has gained the locked on bonus, even though he has not fired to gain the bonus.

[save_Locked on save.zip](https://github.com/long-war-2/lwotc/files/3650198/save_Locked.on.save.zip)
