### ISSUE TITLE
Greater Resolve is bugged and lets your soldier be in two places at the same time

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#584]
![20190921174128_1](https://user-images.githubusercontent.com/54481962/65379509-2c205680-dc97-11e9-8b81-2c3d748997dd.jpg)

I sent the soldier called Svetlana to infiltrate this mission while she was lightly wounded. Upon recovery, she is able to infiltrate another mission at the same time.

**Comment by BlackRose39** [comment]
Hmm, probably the unit's state of readiness reset/refresh when she or he was healed. (code/script wise)

I'm not against removing "Greater Resolve," (I'm assuming since you're were able to send a lightly wounded solider) so we just need to inspect the code to account for the new states that WOTC introduced that LW2 obviously doesn't address. 

In this case, check and modify in the coding if the soldier is doing something while "light wounded." That way, when they heal (during infiltration), the game doesn't put them as "ready," when they're infiltrating. (Being healed triggers them as being ready in the game coding, I'm assuming).

**Comment by pledbrook** [comment]
Weird. Greater Resolve is supposed to be disabled. You haven't messed with the config have you? Here's the entry in LWOTC:

```
[ResCard_GreaterResolve X2StrategyCardTemplate]
Strength=99
```

**Comment by allenhu0912** [comment]
No

**Comment by pledbrook** [comment]
Ah, I think I see the issue. This was a continent bonus, right? If so, that ignores the `Strength` and can activate regardless.

**Comment by allenhu0912** [comment]
Yes
