### ISSUE TITLE
Whirlwind not giving bonus move after using Slash

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#593]
Currently only seems to work with Fleche

**Comment by pledbrook** [comment]
This should work with any melee ability and only if the ability hits.

**Comment by Favid** [comment]
Some additional issues with Whirlwind:
- There is no text description for the passive icon that appears in tactical
- Currently does not have a per turn activation limit. In LW2, it could only activate once per turn, and we should make it work the same in LWOTC

@pledbrook I'm considering just using the LW2 implementation, which uses a custom X2Effect_Whirlwind. The Momentum ability the LWOTC implementation was built on doesn't account for soldiers having single action melee attacks, and would require each melee active ability to be updated for support, instead of just working for all melee abilities.
