### ISSUE TITLE
Make Pistols useful again

### ISSUE THREAD

**Issue by eraserman59** [long-war-2/lwotc#597]
Currently, Pistols are pretty much useless, which is a pretty big nerf to Xcom. This is because their skills directly compete with the XCOM additional skills, and as such there is almost never a time you actually want to spend your ap on the pistol skills, especially since pistol skills cost so much ap. This means that you never actually care to build pistols, and that some interesting strategies (fanfire redscreen to allow easy hacking) have been effectively removed. An average CI soldier will end with only 35 ap, and even a savant wouldn't be able to get all the pistol skills even though in base LW2 every soldier could get all the pistol skills with enough time in the tube. (12 * 7 = 84, all pistol skills costs currently add up to 105 ap yikes)

There are two options I see.

A) revert to a tube training system like LW 2 did. I don't really like this idea because a pistol tube would be free time wise compared to the AWC tube, which you needed for the other additional skills, and would effectively be giving the player the ability to just grab a pistol user whenever.

B) Make most pistol skills be very cheap. The way I see it, pistol skills come in 2 categories. Good always (Lightning, fanfire, faceoff) which are strong enough skills that just having them is worth bringing a pistol for, and Only good for with heavy pistol usage/investment (the others). The good abilities are already gated by soldier rank, so I would suggest making the total cost of pistol skills be around 45-50 ap, with the majority of the cost being fanfire, faceoff, lightning hands, and maybe quickdraw. Return fire, clutch shot, and gunslinger should all be significantly cheaper because those skills are primarily only going to be used on someone who has actually gone down the pistol tree. Target is 45-50 because an above average soldier ends with 42 soldier AP, so they could grab all of the tree if they had a bit of help from Xcom, while a savant could grab 2 xcom abilities in addition to the full pistol line seems like a good spot. 

Personal suggestion for AP costs:
Return fire, Clutch shot: 1 ap 
Gunslinger: 3 ap
Quick draw: 5 ap
Lightning hands: 10 ap
Fanfire, faceoff: 15 AP

Remember that pistols are still fighting with grenades, armor, and plating for an item slot, and to truly be effective a pistolier often needs an ammo. The classes that normally take ammo (sniper, ranger, gunner) don't want pistols (sniper is often out of range, ranger and gunner just shoots with his rifle). Furthermore, while 1 ap is cheap, it does mess with a lot of breakpoints (ex picking up return fire on an average CI soldier would prevent them from taking an Xcom ability for an additional level, on above average it means at SSGT you'll only have 29 instead of 30 ap, etc). Finally, you've already nerfed pistol skills by putting them in a set order, while in base LW 2 it was possible to roll fanfire in one of the earlier spot even if it was unlikely. Fanfire is nice, but fanfire at MSGT without any additional abilities to make bringing a pistol worth it means it loses to the Xcom abilities in ap prioritization.

**Comment by Fallguy55** [comment]
I am more in favour of the pistol training tube. I feel like more time sinks for your soldiers adds more strategic depth and economic sacrifice to think about.

**Comment by Thrawn007** [comment]
Here are my thoughts on the topic.
I'm assuming that XCOM skills are going to settle in at 10/20/40 costs for tier 1/2/3 skills with 4 T1, 2 T2, and 1 T3 skill available per soldier.  Each soldier will earn a total of 35/42/49/56/63 AP depended on Combat IQ.

#1 - Pistol skills should be cheaper than XCOM skills overall.  (Although 1 AP seems too far extreme)
#2 - I think randomizing pistol perks just like XCOM perks should be a goal.
#3 - Adding additional perks to the tree will give a little bit more variety, so I'd recommend we consider that.

Based on these items, I'm suggesting that we divide pistol perks into 2 tiers to be randomized.  Soldiers would get Tier 1 perks at their first 4 ranks, and Tier 2 for their last 3 ranks.
Tier 1: Return Fire, Clutch Shot, Gunslinger, Quickdraw
Tier 2: Lightning Hands, Fan Fire, Face Off

For tier 1, I'm really liking 4 as the cost.   Why?
#1 - All soldiers of even the lowest combat intelligence can afford their first 4 pistol perks, and they even get to build up some AP at the same time.  At 5 cost, is would be exactly 1/2 of a tier 1 Xcom perk, but I'd argue you will almost always find a tier 1 XCOM perk that will be more valuable than the 2 pistol perks, so this gives a couple points to spare.
#2 - A gifted or above soldier can afford 1 XCOM Perk and 1 Pistol Perk by 2nd Rank, and 2 XCOM Perks and 2 pistol perks by rank 4.  This gives a number of different possibilities.  (A 5 AP cost for a tier 1 pistol perk would come up short, a these break points for a gifted soldier.)
#3 - An above average combat intelligence soldier  (42 AP) at full rank would have a choice of 4 T1 XCOM perks, 2 T2 XCOM Perks, or 1 T2 XCOM perk + 2 T1 XCOM Perks.  With the 4  cost T1 Pistol Perks, this soldier could trade 1 T1 XCOM perk for 3 T1 Pistol Perks, or could Trade a T2 XCOM for a T1 XCOM and 3 T1 Pistol perks.  This gives us lots of unique build options for soldiers, which I believe is a huge plus.

For tier 2, I'm really leaning towards 12 as the cost.  Why?
#1 - Total AP for full Pistol build is 52.  This is attainable by both Genius and Savant soldiers, and Gifted soldiers would only need 3 global AP to finish this build.
#2 - A standard combat intelligence soldier with 35 AP could still get 2 Tier 2 skills and 2 T1 skills with no global AP, or with just 1 global AP they could get all 3 Tier 2's, or 2 Tier 2 and 3 T1.  These soldiers couldn't take their first T2 until rank 6 if they took all T1's as they opeed, or by skipping a single T1, they could pick up a T2 at rank 5.
#3 - This sets the cost of tier 2 pistol skills as more costly than T1 XCOM, but cheaper than T2 XCOM.  I think this is the right place, it's just a matter of where.  12 gives better math options than 15, and I don't believe it's likely these skills have the same game breaking potential as many XCOM skills, although they are more consistent due to the small pool.

I think randomizing the pistol skills is good, but I think even a few perks added the pool would be good so that any single skill is not guaranteed.
Tier 1: 
Commisar - Pistol shots against allies who have been mind-controlled by enemies have +50 to hit, cannot be dodged, and automatically kill the target if a hit occurs.
Trick shot - pistol shot that ignores cover
Leg Shot - A special shot that will reduce enemy mobility, and potentially immobilize them. Deals half damage and cannot crit. Mobility reduction lasts 1 turn.

Tier 2 - 
Coup de Gras - Special shot that does 300% bonus damage  stunned, unconscious or panicked enemy at close range. Always hits.  
Magnum - Your pistol attacks get bonus Aim and deal additional damage.
Liquidator - Killing an enemy with your pistol doesn't cost an action. (I think htis one needs some balancing to make it work...this is the stock version from Shadow Ops.  Depending on balance, might be better in T1.)

Adding this list (of already existing skills we could steal), we would have soldiers get 4 of 7 tier 1, and 3 of 6 tier 2, getting rid of the guarantees.  I'm sure there are a few other perks out there that would fit well including once designed for primary or secondary that could be copied to pistols.  Building out to 12 and 9 would be desirable.

**Comment by ToastedAmphibian** [comment]
Commisar? Who would spend a single AP on that ever?

Only times I think I have felt a reason to bother with pistols in LWOTC was for dealing with lost. With the removal of Headshot, they are definitely going to need some kind of buff.

**Comment by Thrawn007** [comment]
Commisar is more interesting than "blank choice" and it's already in the game.

Coming back to this.  One of the main discussions on the topic in Discord is having a dedicated pistol slot.  If that happens, it takes away the opportunity cost of a pistol vs grenade decision.    4/12 would likely be too cheap if this were to happen.  They should likely be closer to 10/20 at that point.  Maybe 8/16, but I haven't done math analysis on what that would mean overall.

**Comment by Fallguy55** [comment]
I am firmly against a dedicated pistol slot. The trade off for a grenade is far more interesting from a strategic perspective. At the moment though, pistols (without proper pistol perks that can be reliably unlocked) aren't a good pick. I would always take a grenade, some armour or some ammo over a pistol, without hesitation, because a soldier is not likely to get more than 1 or two pistol perks available to him through sheer luck of the draw.

**Comment by tunbridgep** [comment]
I really like the idea of a pistol tube. Maybe "Sidearm Training Regimen" in the GTS. Each time in training would allow you to choose from 1 of 3 random pistol skills.

**Comment by Thrawn007** [comment]
> I would always take a grenade, some armour or some ammo over a pistol, without hesitation, because a soldier is not likely to get more than 1 or two pistol perks available to him through sheer luck of the draw.

I'm on the same side as you regarding pistol only slots.  However, a full set of pistol perks is available.  Pistol perks are completely separate from the 3 tiers of XCOM perks.  (You have to scroll down for the 5th row of perks.)

**Comment by Grobobobo** [comment]
Already implemented.
