### ISSUE TITLE
Adjust will recovery to more reasonable values

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#60]
At the moment, it takes 16 days to go from almost Tired (67%) to 100% will. Just to get from Tired to not Tired takes 8 days. And from almost Shaken to not Tired is 12 days (8 + 4 for the minimum will to be Tired).

It's also important to note that going from Tired to Ready still leaves a soldier with 16 days to recover the remaining will! This just doesn't work for the frequency of missions in Long War 2.

**Comment by pledbrook** [comment]
Around 8-10 days to recover from minimum Ready will to 100% should work OK. Soldiers shouldn't be getting into yellow territory from one mission, and they should probably be able to manage a cadence of 1 mission every 8-10 days. 16 days is definitely over the top.

I'm not sure if an 8-day penalty for Tired is a bit too punitive. And the penalty for Shaken is 14 days.

I still need to verify that this is indeed how the will recovery works.

**Comment by pledbrook** [comment]
@ansabalirai Does the above sound reasonable and match your experience of the will recovery?

**Comment by pledbrook** [comment]
Actually, it works weirdly. If the soldier is tired, their will recovers up to the maximum will% to be tired, and then when the recovery time is eventually up, their will goes back to 100%. There's no gradual progression from 66% will to 100% will.

After a little thought, I'm going to try these values:
```
WillRecoveryDays[eMentalState_Shaken]=(MinDays=15, MaxDays=20)
WillRecoveryDays[eMentalState_Tired]=(MinDays=8, MaxDays=14)
WillRecoveryDays[eMentalState_Ready]=(MinDays=0, MaxDays=10)
```
It's not much different on the Shaken and Tired front, but does significantly increase the rate of will recovery for the Ready state.

**Comment by ansabalirai** [comment]
Yes, after making my own ini adjustments, I also notices the jump in will when going from tired to ready. I will try the setting you proposed above, but we can only get meaningful data over the course of an entire campaign (I am currently at a conference and will not be back until the next weekend :( )
One more thing is how will recovery works with haven advisors? I am not sure if stationing tired/shaken people as haven advisors still allows them to recover. In my test, I was not able to see since I needed the haven advisor for a mission, so had to take him out again. Could be worth checking

**Comment by pledbrook** [comment]
Haven advisers should recover will normally, just as soldiers that are infiltrating. Unless they end up on a retaliation mission or a rendezvous.

**Comment by pledbrook** [comment]
I'll close this for now. If testing suggests that the settings need changing, we'll reopen the issue.
