### ISSUE TITLE
Enemy units are randomly positioned upon loading a save

### ISSUE THREAD

**Issue by LazarVell** [long-war-2/lwotc#604]
Their position is the same for the purposes of shooting/using cover etc. but their model is randomly jerked to a position on the map, sometimes below the textures even. I am including a save and a screenshot where you can easily understand the issue.
![GitHub LWOTC save 1](https://user-images.githubusercontent.com/55764689/65548694-3a32d900-df1c-11e9-938a-1cbb63bb6b08.png)

[save_This guy chillin.zip](https://github.com/long-war-2/lwotc/files/3649378/save_This.guy.chillin.zip)

**Comment by spur-gh** [comment]
I've encountered this issue except it's not just the models that can go missing. If i have 3 targets for a character, then save and reload i'll rarely only have two targets until another action is taken. I haven't found any consistency since even reloading the same save again can fix the issue sometimes.

**Comment by copyrite** [comment]
Closing as a base game bug. It is however more frequent with LWOTC.
