### ISSUE TITLE
Advanced and elite purifiers' fire grenade only has 1-tile radius.

### ISSUE THREAD

**Issue by Sinkingeye** [long-war-2/lwotc#607]
I find out this as in one operation,I mind controlled one purifier and discovered that its grenade's radius was as same as the one LW 2 XCOM soldier used.
Although players are sure to be happy about this,it also make purifier AI refuse to use its grenade,which make this ability almost useless.
So my suggestion is:increase the purifiers's fire grenade blast radius,just like the one used by Advent heavy grenadiers.

**Comment by Dragon-32** [comment]
Could this be related to how Firaxis created Purifier's grenades?
[Purifier Grenades Fix](https://steamcommunity.com/sharedfiles/filedetails/?id=1371195713&searchtext=purifier+grenade) on the Workshop.

**Comment by nightmaRok** [comment]
I think its because Purifiers have LW2 grenades, If its possible ill prefer to set up purifiers grenades at vanilla range. Give 2 saves from vanilla and LWotc Purifiers.

[save_purifiers_test.zip](https://github.com/long-war-2/lwotc/files/3651662/save_purifiers_test.zip)

![001](https://user-images.githubusercontent.com/51829747/65587773-1492e780-df8f-11e9-97bc-c03eb58c1ab0.JPG)
![002](https://user-images.githubusercontent.com/51829747/65587775-1492e780-df8f-11e9-9110-ab42b45c3a08.JPG)
![003](https://user-images.githubusercontent.com/51829747/65587776-1492e780-df8f-11e9-9931-527b5a74bbd4.jpg)
![vanilla_001](https://user-images.githubusercontent.com/51829747/65587883-41df9580-df8f-11e9-842c-9b8613c46201.jpg)
![Vanilla_002](https://user-images.githubusercontent.com/51829747/65587885-41df9580-df8f-11e9-8fc5-25f6de77b0cc.jpg)
![Vanilla_003](https://user-images.githubusercontent.com/51829747/65587886-41df9580-df8f-11e9-966c-c77b4d4e0beb.jpg)

**Comment by ansabalirai** [comment]
Adding onto this thread for discussion related to purifiers, would it be too much work to just give them technical style flamethrower aiming (which goes through high cover) so that they actually are a threat? I am guessing that if I have to ask, the answer probably is yes, but still I feel like that is the only foreseeable way to make them threatening. Even with currently ridiculous aim inflation, they act kinda stupid

**Comment by Grobobobo** [comment]
They no longer have a grenade at all.
