### ISSUE TITLE
Add laser and coil tier faction primary weapons

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#613]

**Comment by Anxoczt** [comment]
Wouldnt it be easier to tie this in to a breakthrough ? Like if you research laser weapons, a new research project will pop up with breakthroughs for x faction weapon that could add bonus stats similar to what would upgrading a tier do.

**Comment by Sinkingeye** [comment]
The problem is that 3D models have to be created for these laser/coil tier weapons, so we need someone who has modeling experience.
And if that's not the issue, SPARK also need to have its own laser and coil tier weapon.
Lastly, adding breakthrough is debatable, since it means faction heroes will get their new weapon without costing supply/alloy/ellerium with the cost of 6-day research time, which change the game's difficulty level.

**Comment by nightmaRok** [comment]
For now need just this tier no matter how model looks, if some one can create models and setup effects welcome. In my experience you want faster have magnetic because 3-4 damage on skirmisher and reaper in mid game so low.
