### ISSUE TITLE
Faceless not transforming on seeing XCOM on Rendezvous

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#63]

**Comment by ansabalirai** [comment]
So, first off, this implicitly means that rendezvous mission generation is working, since I did not get it in the 2+ months that i played. Also, I think this a LW2 bug in general and you can actually shoot them as civilians to trigger them. I think it seems to happen when you get LoS on a lone faceless and no other pod (which is generally a little further back). In any case, I don't think this is fundamentally an issue with the port itself

**Comment by pledbrook** [comment]
Ah, good to know, thanks. That scenario definitely sounds like it matches the one I encountered.

**Comment by BlackRose39** [comment]
I believe it also depends on difficulty as well. I think they might not reveal themselves as often, or with certain conditions disabled on rookie.
