### ISSUE TITLE
Rebalance the Lost

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#632]
Suggestions:

 - [ ] Move the Lost turn to between XCOM and Aliens/ADVENT
 - [ ] Disable Headshot
 - [ ] Change Lost targeting to 50% XCOM, 50% Aliens/ADVENT

The first of these removes a weakness of the aliens in which the Lost soak up their overwatch shots. The second makes the Lost more of a threat to the XCOM squad, while the last one makes it a bit fairer to compensate. So now the danger is that XCOM _and_ the aliens/ADVENT will be overrun.

**Comment by allenhu0912** [comment]
I feel this just makes bladestorm shinobis mandatory for these missions

**Comment by Thrawn007** [comment]
I think these 3 changes together will change the feel of lost, making them a bit more of a legit threat, but not overpowering.  As a package, I think this will improve the lost in gameplay, and is simple

**Comment by yoshimo** [comment]
i don't like the removal of headshots. i liked that design idea.
Bring expanded magazines and counter the threat of too many lost before you can reload.

**Comment by Grobobobo** [comment]
1st and 3rd are a given, but I'm not sold on the headshot removal. Will definitely need to be tested.

**Comment by Anxoczt** [comment]
I rather want the headshot mechanic to be as it is, or atleast if it has to go away for the Lost attraction mechanics to be changed considerably or some new soldiers interactions.

- Gunners with combatitive perk could be upgraded that it works like a semi-bladestorm against the lost, or that they can parry more than one melee attack from the lost.
- Technical flamethrower should kill Lost instantly because you are wasting a charged item against potentially endless enemy type.
- Stun gun should kill lost instantly or do massive damage to them
- Lost attraction mechanic should be more tolerant towards LW2 larger incentive to use explosives and that most missions dont give corpses. Some explosives should make more noise than other. A rocket should do way more bang than a regular grenade.

One addition idea is to make suppressors more important in this kind of a mission, non suppressed fire could help attract the lost so its not just the explosives you have to worry about. But that would be quite painful early in the game so a number reduction of the Lost would be needed.

**Comment by Fallguy55** [comment]
I believe that the Lost and the headshot mechanic go hand in hand, so removing them would be a severe loss. 

I also believe that changing lost targeting to 50% is a poor idea as it gives you, the player, a strategic tool to overrun the aliens extremely easily with much more limited risk. It's that way now, in that you can run a calculated risk to draw more lost to a fight to disrupt the aliens, but with the lost targeting XCOM the majority of the time, the risk is significantly greater. It's a tradeoff. 

Moving the lost turn to before the aliens is a very good idea to start with, but with the lost targeting aliens more often, and aliens no longer able to headshot the lost, the lost will make the aliens too easy. 

I think the answer to this may be to simply increase the HP of the lost that are brought in, so headshots aren't quite as prevalent or add the boomers back, or both. I would also like to see the spawn rate of lost go way up. Lost are summoned at a consistent rate, so make that rate quicker, so that you cannot time alien engagements between the lost waves quite so reliably. Also, increasing the spawn points, making the lost spawn in multiple places, rather than just one location, and possibly increasing the numbers that spawn based on the number of soldiers in the fight, or even based on the number of soldiers, + the number of active aliens.

**Comment by eraserman59** [comment]
I think a likely result of this is that the lost become too powerful, especially early game before you get things like bladestorm. Perhaps if pistols were more accessible. 

I will note that moving lost to before XCOM means overwatch is now useless if there are list on the field for XCOM, though I guess that's better because the player decides while the AI can't really recognize that the list exist. 

Perhaps instead of removing headshot entirely, make it so it only takes 1 action point instead of being a free action? Seems like a better spot to prevent the lost from being cleaned up by one high ranked soldier. 

Then again, this change does buff flamethrower technicals since lost on fire are useless and they're normally bunched up anyways.

**Comment by PodliKirill** [comment]
Some expirience from my current run.
1. Lost + smash'n grab - i have problems with crate extraction. Pretty hard to deal with lost, but with carefully planing - it's pretty doable.
2. Lost + dark event on random map. Had several missions with lost - and all of them is easy. I've used lost as tanks and they works perfectly.
3. Lost + ambush. Easy mode. Just hide beside high cover, one move back + shot incoming losts and slowly shot down advent by snipers. Throw grenade when lost is almost dead. This is realy cheat, i made 31-33 enemies ambush even without lazers and skilled soldiers. Without headshot, this mission is a loot easier for me.

But this is possible only if you know, what you're doing. Some less skilled players can have a loot of troubles with lost without headshot.

**Comment by stefan3iii** [comment]
+1 vote for keeping head shot. Lost in general are a very unique mechanic, that puts stress on your ability to manage reloads. Would be a shame to lose that. 

If lost missions are too easy it'd be better to find some other way to balance them. For example, maybe the lost spawn point is biased towards the team that spawned them (usually Xcom).

**Comment by BlackRose39** [comment]
@pledbrook Just a quick question, what do you make of "between the eyes" resistance order? Has that been resolved yet and if not, are you considering disabling it?

**Comment by pledbrook** [comment]
I don't have a strong opinion either way. If people want to use up a Resistance Order slot for it, why not let them? I do think it makes Lost less interesting to deal with, so maybe it will be removed. Resistance Orders seem to vary dramatically between almost useless to pretty overpowered. They probably need an overhaul for LWOTC.

**Comment by Thrawn007** [comment]
Between the eyes is a lot less effective without headshot.

Perhaps the resistance order should be the vehicle to enable headshot?

**Comment by nightmaRok** [comment]
This order still work if you do graze or do not enough damage to Lost

**Comment by MrNiceUK** [comment]
Yeah, the true power of between the eyes was the combo with headshot and pistols... since while the unlimited ammo of pistols is brilliant against lost with headshot, a fair amount of lost aren't guaranteed to be dropped by a single pistol shot normally...

**Comment by insufferablesmartypants** [comment]
Just got jumped during a covert op.   Both my soldiers running from Advent in an abandoned city, and that's where I discover that Headshot has been turned off.

The mission was idiotic.   Hoping to find a mod or figure out how to turn it back on again.

**Comment by pledbrook** [comment]
Was that an ambush? I'm considering just disabling them, since they're pretty much just "run for the exit" missions. If you're lucky, you can avoid the reinforcement pod. If you're unlucky, you'll probably lose one or more of your soldiers. Same if the Lost appear: you just run.

**Comment by Swarbs1982** [comment]
I find the reinforcements and lost very easy on those missions.

Reinforcements generally drop right on top of the starting position, so you can get a predictable elevated OW shot at them and then finish them off with any special abilities on your soldiers, or just move to flank after they scatter. Lost are also very easy - I usually find there's only regular lost spawning in the swarms, with only 8 mobility, so you can easily dodge around them and kill them over a few turns.

Any advent in the area are usually patrolling singly, so easy to deal with if you run into them whilst fighting the lost. Particularly as they will usually go for the lost anyway if you are in cover.

Imo the only argument for disabling them is that they are generally very easy and predictable to do.

**Comment by insufferablesmartypants** [comment]
@pledbrook 
It was an ambush.  I know Bradford says "Break cover and run for the exit!" but I normally just fight my way through, nice and slow.   I wait for the Advent guys to drop - If you run, they magically know where you are and and will follow so I like to kill them early.

Lost swarms of 6 showed up every 3 rounds, which wouldn't have been any big deal but I only had 2 guys, and one of them was a sharpshooter with only a sniper rifle and no pistol, making most of the killing the responsibility of my shotty soldier.  1 kill per round against 6 guys plus Advent, with reinforcing lost every 3 rounds was just silly.

I hate to exploit ladders and pipes (or doors), so I just reloaded the mission after I figured out how to re-enable headshot.

In retrospect, I guess I could have just sprinted and hoped for the best, and adapted to this new development, but what I remember most about that first mission is that it just wasn't fun, and that's what's going to stick with me.

**Comment by Swarbs1982** [comment]
With experience, taking sharpshooters on a covert with ambush risk is generally a bad idea, unless you have DfA and a decent pistol, or snapshot and high aim. Or three guys on the mission. In general if you are going to run an ambush risk with only two guys, always make one of them a ranger or technical, so the multi shot and flame can deal with the lost.

That said, those missions are quite uninspiring imo, so there is an argument for not having them. Once you learn how to do them, and the soldiers to take when there's an ambush risk, it's pretty much just rinse and repeat.
