### ISSUE TITLE
dev build-0004 tygan not contributing to research after acquiring scientists

### ISSUE THREAD

**Issue by scmantikor** [long-war-2/lwotc#651]
research gets "paused" when scientists are assigned to havens. As per paledbrook, assigning scientists to havens counts as 2 scientists being removed from research which results in the effect below

![image](https://user-images.githubusercontent.com/55502272/66147879-46b4e100-e642-11e9-8562-6852752480f6.png)
![image](https://user-images.githubusercontent.com/55502272/66147885-4c122b80-e642-11e9-8799-6d650d79131e.png)

tried changing research it still wont progress 
![image](https://user-images.githubusercontent.com/55502272/66147895-5502fd00-e642-11e9-93cc-9958106e0f15.png)

added save
[save_IRONMAN- Campaign 1576.zip](https://github.com/long-war-2/lwotc/files/3687245/save_IRONMAN-.Campaign.1576.zip)

**Comment by pledbrook** [comment]
This is happening because the science score contribution of scientist haven advisers is being deducted twice. So in this particular case, the base science score is 20 (10 from Tygan, 10 from the two scientists). The 10 from the two scientists is deducted twice, resulting in -20, giving a grand total score of 0! Hence why research is paused.

The double deduction is because the base game is filtering out scientists on covert actions (which includes haven advisers) and then LWOTC is filtering them out because they're in staff slots that aren't Lab research stations. The fix is for the latter to ignore scientists on covert actions.
