### ISSUE TITLE
Reduce alloy and elerium rewards from supply extraction

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#660]
These missions provide an overly generous supply of alloys and elerium, particularly in the early game. Not sure what to aim for yet.

**Comment by Anxoczt** [comment]
All crates, mid game resource gain from one particular raid
![20190809141925_1](https://user-images.githubusercontent.com/50877085/66261106-01222080-e7c8-11e9-92ad-7ebfecf40837.jpg)

I dont want the gain to be touched that much in the early game. These missions can go sour really quickly and to get all crates you need to be really good. Player should be rewarded if he manages to get all of them. Although i agree a slight general reduction of them could be plugged in. Thinking about 35% reduction. Or maybe these supply crate hunts could give more supplies rather than elerium or alloys and the old smash and grab could instead give more of these alien resources. It also makes sense, whatever is Advent lifting from old cities arent going to be alien alloys and elerium. But in their stockpiles, thats where their own stuff is.

**Comment by TheReigningKing** [comment]
I would put the basis at these missions to only get around 8-10 of these crates rather than all 12.  When playing on Veteran, I can get 12 b/c I basically task one soldier to just pick up crates, but on higher difficulties you'll have shorter infiltration timers and therefore less soldiers on each mission.

**Comment by MrNiceUK** [comment]
Could compare supply extraction and supply raid, and consider how many crates extracted should be considered comparable to a successful supply raid with no destroyed supplies...

**Comment by nightmaRok** [comment]
In mid game on supply extraction 10-12 enemies, from 12 crates i got 87 supply 28 alloys 31 elerium

![002](https://user-images.githubusercontent.com/51829747/66265427-f34bba00-e81e-11e9-89c5-0406ec6f4945.JPG)

On Supply raid what hard to detect and required 100% infiltration 22-24 i got 111 \ 18 \ 18 , so supply extraction definitely gives you more alloys and elerium

![001](https://user-images.githubusercontent.com/51829747/66265470-b8965180-e81f-11e9-8ce5-fab344185862.JPG)

 I think need to nert supply extraction
