### ISSUE TITLE
Integrate near-essential quality-of-life mods

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#67]
This is a list of quality-of-life mods we should consider integrating with LW2:

 * [X] ✅ [Improved Camera Updated WOTC](https://steamcommunity.com/sharedfiles/filedetails/?id=1138296118)
 * [X] 📦 [Perfect Information](https://steamcommunity.com/sharedfiles/filedetails/?id=1140739830) ([Extended Information](https://steamcommunity.com/sharedfiles/filedetails/?id=1183444470&searchtext=extended+information) can be used to provide full Perfect Information-like info)
 * [ ] [Rebel Job Selector](https://steamcommunity.com/sharedfiles/filedetails/?id=873749733)
 * [X] 📦 [View Infiltrating Squad](https://steamcommunity.com/sharedfiles/filedetails/?id=897020660)
 * [X] 📦 [Show Infiltration Percentage](https://steamcommunity.com/sharedfiles/filedetails/?id=888102133)
 * [X] 📦 [LW2 Information Display](https://steamcommunity.com/sharedfiles/filedetails/?id=925598042&searchtext=vigilance)
 * [X] ✅ [Evac All](https://steamcommunity.com/sharedfiles/filedetails/?id=1126395106)
 * [ ] [Instant Avenger Menus](https://steamcommunity.com/sharedfiles/filedetails/?id=1124410215)
 * [X] ✅ [Gotcha Again](https://steamcommunity.com/sharedfiles/filedetails/?id=1124288875)
 * [ ] [New Target Icons](https://steamcommunity.com/sharedfiles/filedetails/?id=1384631824)
 * [X] ✅ [TacticalUI Kill Counter](https://steamcommunity.com/sharedfiles/filedetails/?id=749138678)
 * [X] ✅ [[WOTC] Additional Icons](https://steamcommunity.com/sharedfiles/filedetails/?id=1127409511)
 * [ ] [Show Health Values](https://steamcommunity.com/sharedfiles/filedetails/?id=617015579) (or similar)
 * [ ] [Customize UIEventNotice](https://steamcommunity.com/sharedfiles/filedetails/?id=885278302)
 * [ ] [Upcoming Events](https://steamcommunity.com/sharedfiles/filedetails/?id=1125698656)
 * [X] ✅ [Yet Another F1](https://steamcommunity.com/sharedfiles/filedetails/?id=934236622)

✅ = Works as is
🔧 = Requires patching
📦 = Bundled

Some of them may need patching and bundling. Others could just be dependencies.

These are already supported/integrated:

 * robojumper's Squad Select
 * Detailed Soldier Lists

**Comment by yoshimo** [comment]
Having features and fixes spread across multiple mods is difficult.

Rebel Job Selector & View Infiltrating Squad & Show Infiltration percentage in Squad Select should be integrated in LWotC itself,
i agree.  These probably will break by porting to WotC and will need rework anyway.

With the rest it is difficult, some are no longer maintained, some do not really need maintenance.

I'm not sure if it is a good way of solving the problem but maybe it should be done like
https://steamcommunity.com/sharedfiles/filedetails/?id=1581142050 (Various Options)

Combine all "fixes" into a community-fixes mod and combine the quality of life features into a community-qol-mod.  Things you don't need can be turned off there.

This way even the people that don't want LongWar will still benefit from better maintenance and less conflicts between various mods. Gotcha&PerfectInformation are a good example for unsolved problems in combination with Peak from Concealment

**Comment by ansabalirai** [comment]
It might also be worth noting specifically which of these work as is (such as evac all) and which ones need patching (based on discussion in #54 ). Moreover, while I like the idea by @yoshimo , the problem is that some mods actually do change gameplay even if they are classified as QoL improvement, i.e. rebel job selector, peak from concealment, etc., so not sure if bundling those together with "true" QoL mods is the best option. I wonder if a spreadsheet would be a good idea to manage and classify all such proposed mods for better classification and prioritization?

**Comment by yoshimo** [comment]
Peak from Concealment is a game changer absolutely. The focus is more that the other two , which have problems with it, seem stale these days. So if they were part of a quality of life "highlander" it would be easier to fix interactions.

**Comment by Dragon-32** [comment]
FYI, the WotC version of "Upcoming events in hours" is [Upcoming Events](https://steamcommunity.com/sharedfiles/filedetails/?id=1125698656).

**Comment by pledbrook** [comment]
Thanks, I've updated the entry in the list above.

**Comment by GitWadeanthony** [comment]
I think [New Target Icons](https://steamcommunity.com/sharedfiles/filedetails/?id=1384631824) should be added, its not a 100% needed but it is very nice to have. I have been playing with it so far and haven't seen any issues. 

WOTC - Extended Information also doesn't seem to have the issue Prefect information has where the aim is always 0% over enemy icons.

**Comment by pledbrook** [comment]
My only concern about Extended Information is the alleged performance issue on Mac/Linux.

**Comment by ansabalirai** [comment]
Also, I am not sure if extended information takes grazes into account

**Comment by yoshimo** [comment]
If we make a table what infos would we need?

-  Name of the mod
- Link to the mod
- category
- Quality of life
- bug fixes
- little enhancements
- vanilla/wotc
- maintained?
- working with lwotc yet? (good, partially,not at all)

**Comment by SirMrMister** [comment]
[Tactical Information Overhaul](https://steamcommunity.com/sharedfiles/filedetails/?id=1630804593) seems to a merge of Additional Target Icons plus its own more involved implementation of Numeric Health Display (two modifications usually incompatible as they alter the same .ini file), but I'm not sure if it includes the extra icons from New Target Icons.

**Comment by yoshimo** [comment]
Additional Icons, nothing about target mentioned there.
If we stick to the Lost, which we should, i suggest [Lost Autofire](https://steamcommunity.com/sharedfiles/filedetails/?id=1126356484)
Where would be the best place to start this collection? The issue and then a wiki page?

**Comment by ansabalirai** [comment]
One mod that seemed to have been missed in this list and is a lifesaver for LW2 slogs is Quick End Turn. I am not sure if it was updated for WOTC, but having to go through 30+ turns on an HQ with 8+ soldiers individually is near impossible

**Comment by yoshimo** [comment]
I think Overwatch All/Others does this very well

**Comment by ansabalirai** [comment]
@yoshimo Does it also do steady weapon in case of a stock equipped? In my experience, the solider who cannot OW just hunkers down even if they have a stock. I need to double check this

**Comment by pledbrook** [comment]
Overwatch All _only_ does overwatch as far as I can tell. It definitely doesn't mention the reloading, steady, etc. that Quick End Turn does.

**Comment by SirMrMister** [comment]
[Free Reload Anytime](https://steamcommunity.com/sharedfiles/filedetails/?id=1124843260).
Makes free reload from auto loaders a separate reload action, allowing you to save free reloads for later when you have action points to spare.

Incidentally, I found this comment on an old reddit post, which gives an idea (just the idea though) worth considering if you'd prefer it to Free Reload Anytime's behaviour:

> Given that they're often mags taped together, it'd be nice to make it an active ability that makes THIS reload a normal one but slots in the quick change mag so the NEXT reload will be free.
Rather than making it something you can use on a whim, you'd have to decide in advance when you think you'll need to activate it

**Comment by pledbrook** [comment]
Another option would be to remove auto-loaders from the game :smile:

**Comment by ansabalirai** [comment]
> Another option would be to remove auto-loaders from the game 😄

Plz no, I want rangers and gunners to be at least somewhat relevant

**Comment by yoshimo** [comment]
So as a course of action i think we should
wait for the showstoppers and major bugs to be fixed , then hope that @pledbrook integrates the 3 lw specific qol mods intro lwotc (even if the title changed in the mod itself) and then sit down and collect, discuss and catetegorise the rest and then decide how to proceed.

**Comment by SirMrMister** [comment]
Counter-argument: Besides the 3 LW-specific ones, I think it should also be a priority to include one of the ones giving data that might help in debugging - the equivalence of XCOM:EW’s Perfect Information and More than Perfect Information, and an extended F1.

**Comment by yoshimo** [comment]
How well do the perfect information mod and its successor work with lwotc? For alpha bundle, later depend on them

**Comment by pledbrook** [comment]
Perfect information can't be integrated as is because it shows 0% to hit over the enemy icons. I want to test Extended Information on Mac before committing to that, as the mod page warns that there's a potential performance issue on Mac and Linux.

**Comment by bazik123** [comment]
i dont think i understand the motivation of including QOL mods that dont need changes to work. by doing this you are limiting the ability of people to chose some less popular mods that are conflicting with those you happened to choose.

(FWIW i am mostly using same mods you chose, but I dont see any real benefit of not having people install those that dont require changes separately)

**Comment by SirMrMister** [comment]
Thing is, while your argument is absolutely correct, most of them do indeed need changes to work, both with LWOTC AND with each other.

After all, if ALL the changes LWOTC were to do to a particular .ini file were related with integrating a certain QoL UI mod, then if you want to use a different mod ibstead that also changes that file it won't matter wether LWOTC ibtegrated the first mod or not, as it'll be replacing the whole file regardless.

**Comment by pledbrook** [comment]
> ..., but I dont see any real benefit of not having people install those that dont require changes separately

The benefit is for those people who aren't comfortable with or don't want the hassle of installing many different mods. This is partly guided by the joy I had at seeing Long War Rebalance integrating a bunch of QoL mods that would make the game more pleasant and I wouldn't have to mess around getting them myself.

Of course, allowing folks to use their own preferred mods is desirable too. But it's mutually exclusive with the convenience of "bundling" mods into one.

There may be a reasonable compromise, although I don't know the mechanics of how it would work: set up a second mod that is simply a collection of mods that we think are desirable for all players. That would limit the number of mods people need to install to two.

To be honest, I don't know how mod dependencies ("required mods") or mod collections work. It may not prove as convenient as I hope. But we'll tackle that when we get there.

**Comment by yoshimo** [comment]
In terms of enhancing the lwotc experience with companion mods, we might want to have a look at
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/32 later

**Comment by pledbrook** [comment]
Those fixes are listed for going into the highlander anyway, which we depend on. Not sure if there's much point adding them to this mod.

**Comment by yoshimo** [comment]
Not for this mod, but future related work. Highlander doesn't fix itself

**Comment by yoshimo** [comment]
I think [https://steamcommunity.com/sharedfiles/filedetails/?id=1289686596] ([WOTC] Cost Based Ability Colors) was also a nice QOL addition

**Comment by pledbrook** [comment]
@yoshimo That mod does conflict somewhat with LW2's own colour coding.

**Comment by yoshimo** [comment]
I don't remember how LW did it, was it doing the same?

**Comment by pledbrook** [comment]
Similar. Green for free action. Yellow for abilities that required two actions. I don't think it distinguished between turn-ending actions and non-turn-ending actions though. That's something that would be nice.

**Comment by pledbrook** [comment]
I tried Extended Information! on Mac and it just crashed the game. That rules it out as a dependency.

**Comment by pledbrook** [comment]
What are people's experiences with Gotcha Again? Does it work as is?

**Comment by GitWadeanthony** [comment]
Gotcha Again has some bugs with line of sight for overwatch shots. Sometimes it will say that you won't pull overwatch and you do and other times it says will pull an overwatch and you don't. A lot of this pretty obvious if you will or wont pull an overwatch if you have been playing a while. 

Haven't had any issues with line of sight for hack targets.

**Comment by yoshimo** [comment]
> I tried Extended Information! on Mac and it just crashed the game. That rules it out as a dependency.

Does it crash without lwotc too?

**Comment by ansabalirai** [comment]
I can confirm that instant avenger menus has been working for me without any issues. Extended information works but it sometimes shows a different percentage when the shot is taken than what it shows in the preview. Since graze band is disabled, I am not sure what else could be causing that

**Comment by pledbrook** [comment]
@yoshimo Didn't try it. I may have a go. It's a bit of a pain switching between them though, and I'd have to start a vanilla campaign 🤢

**Comment by vandervalkg** [comment]
Yes [WOTC] Cost-Based Ability Colors clashed with LW2's built-in coloring of actions (in Gatecrasher, both nades were blacked out, but could still be used), so this one should not be used with LW2.

I had a crash after Gatekeeper when I clicked to promote one of the sollies, I guessed it was due to [WOTC] New Promotion Screen by Default, but the fault repeated itself even after I disabled the mod in the AML and loaded back up.  I even clicked continue to go straight to the Avenger, then tried to view soldiers and it crashed there too. I also had the following mods enabled:

Stop Wasting My Time - WOTC
Remove Missing Mods for WOTC

No Reveal Cinematics
Tactical HUD Shot Bar
[WOTC] Gotcha Again
[WOTC] Quick Soldier Info
Instant Loot
Confirm Free Reload - WOTC
Quicker Reload - WOTC

**Comment by pledbrook** [comment]
@vandervalkg The blacked-out ability icons could indicate a problem with the core game classes (the highlander). That would probably also explain the crash on promotion.

Double check that you don't have another highlander mod (such as subscribed X2WOTCCommunityHighlander) active. And make sure the one you have selected is the one packaged with the alpha.

**Comment by vandervalkg** [comment]
Oh, I thought on the download page you said that we could use the updated Steam version of Highlander?  I already deleted the version that came with LW2[WOTC] zip file. Do you have a separate download link for your version of it, so I don't have to download the whole 2 GB again?

**Comment by vandervalkg** [comment]
Ah, I think I found it!  https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/ will work better than the current live Steam version?

**Comment by pledbrook** [comment]
@vandervalkg No, you need the one that comes with the alpha-2 release. And each alpha will likely have a new highlander version due to the number of game fixes that require highlander changes.

The only other option is to build the highlander yourself from https://github.com/long-war-2/X2WOTCCommunityHighlander

**Comment by yoshimo** [comment]
[https://steamcommunity.com/sharedfiles/filedetails/?id=1207741138)] (WOTC Show Tech Path)
is quite nice. Maybe this would fit the bill for a future QOL bundle too.

**Comment by Aurelicornus** [comment]
My impressions:

> Perfect Information or Extended Information

I feel them like a cheat mode, because I like play without know everything of my enemy, and guess what they could do by what they does in game.
I would keep this function off in the base game, but introduce it as Second Wave options like in Long War for Xcom 1, that has the same.

> Rebel Job Selector
This one seems handy, maybe I will test it out. :)

> View Infiltrating Squad
I'm not using it, but seems a good improvement. I will check it out, but I think is better if is a Second Wave options that those who dislike it can turn on/off.

> Show Infiltration Percentage
I like the idea, but not where the info is placed in the equip screen (I dislike that covers the rightmost of my soldiers...!). Is handy, but I believe should be put as Second Wave options for those who don't like know everything.

> LW2 Information Display
If I'm not wrong, the Alpha 3 has already something similar. I think is fine, but is another I think is good leaving toogleable with a SW option maybe.

> Evac All
An essential that should have been present also in the Vanilla! ;)

> Instant Avenger Menus
I have no issues with the standard menus. My suggestions is again to put this one as Second Wave option for those who like/need it.

> Gotcha Again
Sounds handy, but they are like the "target preview" option in vanilla, and some players would like the challenge to play without helps or assistants. I would not put it as default, but toogleable for those who want use it.

> New Target Icons
I would avoid this mod because it includes also icons for other units that are not present into Long War 2, and I think is better restrict these add-on only to the assets that are included into the mod (both for safety for compatibility or bug tracking).
Maybe is possible a "lite" version that includes only the icons used by LW2, and cut off the unused ones?

> TacticalUI Kill Counter
If I'm not wrong, Long War for Xcom 1 has a similar function (or was put with an extra mod, I don't remember right), however I would not activate it for default, but leaving it as a gameplay option to activate for those who likes it. As said, some players like don't know everything, and understand some details from how the game behave (for example, if you have kill all or most enemies depending how much long is the computer turn). Know the number of enemies left can spoil the fun for some players (like me ;) ) or spoil the surprise to have still enemies actives when you thought to have killed them all.

> Show Health Values

I think the best is Numeric Health Display:
https://steamcommunity.com/sharedfiles/filedetails/?id=1126938196

> Customize UIEventNotice
Sounds useful for those who want/needs tweak further the gameplay experience. ;)

>  Upcoming Events
I feel is a good eyecandy, approved ;)

> Yet Another F1
I believe this should be essential and present in the main Mod, because the Vanilla info screen is really lacking of... everything. The only way to see the stats during the play is hovering the cursor over the soldier name, but you have only an overview of the basic stats, while is missed a window that lists stats and perks like Xcom 1. On Long War 1, I used also Enhanced Tactical Info for a complete summary of what the unit can or cannot do, that I feel essential: https://www.nexusmods.com/xcom/mods/554/

**Comment by Kazanir** [comment]
- LW2 Information Display will be integrated via pull #200 
- Upcoming Events appears to work as-is

**Comment by Kazanir** [comment]
- Gotcha Again also seems to work as is.

**Comment by BTAxis** [comment]
> If I'm not wrong, Long War for Xcom 1 has a similar function (or was put with an extra mod, I don't remember right), however I would not activate it for default, but leaving it as a gameplay option to activate for those who likes it. As said, some players like don't know everything, and understand some details from how the game behave (for example, if you have kill all or most enemies depending how much long is the computer turn). Know the number of enemies left can spoil the fun for some players (like me ;) ) or spoil the surprise to have still enemies actives when you thought to have killed them all.

By default though it only shows the number of enemies you've killed, which is information you would have anyway if you simply kept count. It does not show the number of enemies on the mission until you build the Shadow Chamber (again, by default), in which case you again already have that information because the Shadow Chamber tells you. That does put it squarely in QoL territory in my opinion.

**Comment by ansabalirai** [comment]
Would love to have at least the "Show infiltration percentage" when sending out a squad. Would eliminate a lot of Alt-Tabbing to put numbers in the infamous Xavier spreadsheet to find if you make the cut. 
I have the local code ported from vanilla LW2 working on my machine in case it might help. Cannot seem to build LWOTC and integrate it within though.

**Comment by robojumper** [comment]
Probably worth integrating: [Better Squad Icon Selector](https://steamcommunity.com/sharedfiles/filedetails/?id=848382778)

![preview](https://steamuserimages-a.akamaihd.net/ugc/105107289908677998/FCDDB382218B76E938BA36BDD162704C6DE98E2C/)

**Comment by zyxpsilon** [comment]
As suggested on Discord (LWotc channel) & adding here for _clarity_...
Mission Notification/Icons & custom Intro-Splasher Images;
----
![image](https://user-images.githubusercontent.com/23318465/79475354-930bb100-7fd5-11ea-87e3-5718b1ede16a.png)

**Comment by pledbrook** [comment]
We've integrated most of them. Closing this issue as mostly done. Will open separate issues on a case-by-case basis if we decide it's worth integrating more.
