### ISSUE TITLE
Should faction soldiers have hack score growth?

### ISSUE THREAD

**Issue by allenhu0912** [long-war-2/lwotc#674]
Kind of inconsistent with non-faction soldiers where only shinobis and specialists have it. I would kind of understand Reapers having innate hack score growth, but not psionic fanatics or former advent clones

**Comment by Maebalzurakin** [comment]
It would be nice for reapers to have it for skull mining.  Also Skirmishers, imo, should have a native skull jack ability.  You see them use their claw as a skull jack in their intro scene.

Personally, I just use this mod....
https://steamcommunity.com/sharedfiles/filedetails/?id=1337050242

I have found it to be 100% compatible with LWOTC and it allows stats to grow organically with use instead of getting magical jumps on leveling up.
