### ISSUE TITLE
Issues concerning of unlocking higher tier weapons

### ISSUE THREAD

**Issue by UMebius** [long-war-2/lwotc#677]
To kick this off, I do realize that LW2 mechanics require manufacturing each upgraded weapon with additional materials in the "Build Items" section. Here are some issues I'm concerned of:
I installed some weapon mods, most of them feature auto-upgrading to next tier (since they're made for vanilla WOTC), so I kinda saw it coming that new tier guns won't be unlocked automatically. 
However, there's this Republic Weaponry mod that popped up 3 sets of identical guns at conventional tiers ever since the beginning of the game. I'm thinking that maybe its designed for the vanilla CV MG + BM tiers purpose, but none of them auto-upgrade to next tiers after unlocking Magnetic Weaponry. I cannot use additem console command to bring out the weapons either.
Apart from [WOTC: Resistance Firearms] mod, I can't bring out other mods' higher tier weapons through console command and they won't even show up in "Build Items" section. Any ideas on how to retrieve them ? Thanks.

**Comment by Grobobobo** [comment]
LW2 kills all schematics, so you'll need to make these seperate weapons in the config.

**Comment by pledbrook** [comment]
You should be able to use INI entries [like these](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Config/XComLW_Overhaul.ini#L441) to configure the weapons so they can be built.

Alternatively, you can [configure certain schematics](https://github.com/long-war-2/lwotc/blob/master/LongWarOfTheChosen/Config/XComLW_Overhaul.ini#L309) so that they are not disabled by LWOTC.
