### ISSUE TITLE
Evac with Ranger and weapon Reload buttons on gamepad doesnt work!

### ISSUE THREAD

**Issue by lordarter** [long-war-2/lwotc#682]
Hello everybody.
i have folowing issue:
on my gamepad Logitech F310D doesnt work Reload Weapon button (X) - not big issue and
Evacuation with Ranger (RB) - extremelly important ISSUE!!! cause every second mission requires evac.
i want to let you know that my gamepad perfectly works in original XCOM2 War of the Chosen and it is very-very comfortable to play this game using gamepad so i was sadly surprised when noticed that those 2 buttons doesnt work in LWOTC, although even with Long War installed and activated if i load my savings from original WotC - all buttons works perfectly.
another related issue which might helps you to fix this problem or mb to someone who has the same issues is this:

1. when its time to evac i do save the game and exit to main menu (cause by unknown reason it is not possible to change controller while you re in game)
2. so from the main menu i go to controller settings and - again it is not possible to change controller without restarting the game completelly, but i found a bag
3. you push LB which starts showing you list of game authors, escape it with (B) button
4. now you can change controller to mouse
5. save settings changings and exit
6. go load your save
7. push (P) on keyboard to call Ranger evac
8. save the game
9. exit to main menu
10. go to controller settigns - you cannot change controlle again (dont worry)
11. push Authors button then ESC it
12. change mouse to gamepad
13. (X) to save and exit
14. load game
15. play...but only till next mission with evac required.

#679 

**fix that please please please!**

**Comment by aikomiko** [comment]
Trying LWOTC beta 2 with the XBOX360 controller, my results so far RE: controller specific issues:

1. The controller "X" button for Tactical reload not working issue seems to be connected to the LWOTC mod setting check box "use base game Tactical HUD"... depending on the selected setting the controller "X" button scrolls to the next ability page, instead of 'weapon reload'.

2. on Squad Management screen, controller directional right-left does not allow free selection of all the columns.  Also there are (apparently) unreachable buttons in Squad Management when using the controller.  I'll raise a separate issue regarding unreachable game buttons with the controller since this occurs multiple places for me (which may just mean I'm showing my ignorance!).

**Comment by aikomiko** [comment]
The console command "LWForceEvac" might help with problems getting evac underway
https://www.ufopaedia.org/index.php/Console_Commands_(LW2)

**Comment by pledbrook** [comment]
Evac can now be placed by pressing right stick.
