### ISSUE TITLE
Integrate SitReps

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#71]
Randomly-generated SitReps for missions are currently disabled. We need to decide whether to enable them and if so, what SitReps to keep or change.

**Comment by yoshimo** [comment]
Do we have a list of possible sitreps and their effects ?

**Comment by pledbrook** [comment]
It should be possible to grab them from the XCOM 2 WOTC SDK. I can do that at some point if no one gets to it before me.

**Comment by Tylon01** [comment]
This is from the XCOM WIKI for possible sitreps

- **Automated Defenses** - "Intel suggests a high concentration of robotic enemies at the mission site."
     Enemy types are limited to MECs, Codices, ADVENT Turrets, Spectres and Sectopods.
- **Show of Force** - "Intel suggests a large number of ADVENT troopers present, under ADVENT only leadership."
     Enemy types are limited to ADVENT humanoids, MECs, and Sectopods.
- **Savage** - "Intel suggests a high concentration of beast-like enemies at this mission site."
     Enemy types are limited to Faceless, Chryssalids, Berserkers and Stun Lancers.
- **Psionic Storm** - "A high concentration of psionic energy is in the area of the mission, suggesting a high number of psi-capable enemies."
     Enemy types are limited to ADVENT Priests, Sectoids, Codexs and Gatekeepers.
- **The Lost** 
     In addition to ADVENT enemies, the mission map also contains The Lost.
- **The Horde** - "Area is abandoned by ADVENT, leaving only large numbers of The Lost."
     Enemy types are limited to The Lost.
- **Location Scout** 
     Entire map is revealed, making all enemies and all parts of the map visible.
- **Low Profile** 
     Only soldiers of rank Sergeant and below may be selected for the mission.
- **Surgical** 
     Squad size is limited to 3 soldiers.
- **Shadow Squad** 
     All soldiers on the mission gain a single charge of the Conceal ability. This is a separate ability from 
     the Ranger's Conceal and the Reaper's Shadow, despite granting the same effect.
- **Resistance Contacts** 
     Map contains several civilians; Supplies are rewarded for each civilian contacted (by moving a soldier 
     next to them).
- **ADVENT Supply** - ADVENT forces have stockpiled extra materials in storage chests near this site.
     Causes chests to appear around the mission area. A soldier can gather their contents (Supplies) by 
     clicking on the chest while adjacent to it.

**Comment by Dragon-32** [comment]
DefaultGameData.ini
```
[XComGame.X2SitRep_DefaultSitReps]
SitReps="Surgical"
;SitReps="Fireteam"
SitReps="LootChests"
SitReps="HighExplosives"
;SitReps="Ambush"
;SitReps="ChemicalLeak"
SitReps="ResistanceContacts"
SitReps="TheLost"
SitReps="TheHorde"
SitReps="StealthInsertion"
SitReps="LowProfile"
;SitReps="LowVisibility"
;SitReps="Juggernaut"
SitReps="ShadowSquad"
;SitReps="BlackOps"
SitReps="LocationScout"
SitReps="ShowOfForce"
SitReps="PsionicStorm"
SitReps="Savage"
SitReps="AutomatedDefenses"
;SitReps="Advanced"
;SitReps="Phalanx"
;SitReps="Waves"
SitReps="InformationWarSitRep"
SitReps="PrivateChannelsSitRep"
SitReps="MentalFortitude"
SitReps="DarkEventBarrierSitRep"
SitReps="DarkEventDarkTowerSitRep"
SitReps="ChallengeNoReinforcements"
```
Copy and paste from XComGame.int of the in-game descriptions:

> [Surgical X2SitRepTemplate]
> FriendlyName="Surgical"
> Description="The squad size on this mission is limited to 3 soldiers."
> 
> [Fireteam X2SitRepTemplate]
> FriendlyName="Fireteam"
> Description="The squad size on this mission is limited to 2 soldiers."
> 
> [LootChests X2SitRepTemplate]
> FriendlyName="ADVENT Loot"
> Description="ADVENT forces have stockpiled extra materials in storage chests near this site."
> 
> [HighExplosives X2SitRepTemplate]
> FriendlyName="High Explosives"
> Description="This combat zone has a high density of explosive material.  Caution advised."
> 
> [Ambush X2SitRepTemplate]
> FriendlyName="Priority Objective"
> Description="ADVENT will defend the mission objective with multiple reinforcements."
> 
> [StealthInsertion X2SitRepTemplate]
> FriendlyName="Stealth Insertion"
> Description="Any mission timers will not start until the squad breaks concealment."
> 
> [ChemicalLeak X2SitRepTemplate]
> FriendlyName="Chemical Leak"
> Description="High incidences of poison clouds and acid spills have been reported in this combat zone."
> 
> [ResistanceContacts X2SitRepTemplate]
> FriendlyName="Resistance Contacts"
> Description="Undercover civilians present in this combat zone can be contacted to gain valuable rewards."
> 
> [LowProfile X2SitRepTemplate]
> FriendlyName="Low Profile"
> Description="Due to heavy ADVENT surveillance, only soldiers of rank Sergeant or lower are allowed on this mission."
> 
> [LowVisibility X2SitRepTemplate]
> FriendlyName="Low Visibility"
> Description="Adverse conditions in this combat zone will significantly reduce the sight radius of XCOM soldiers and enemies alike."
> 
> [ShadowSquad X2SitRepTemplate]
> FriendlyName="Shadow Squad"
> Description="All soldiers on this mission will gain a single charge of the Conceal ability."
> 
> [Juggernaut X2SitRepTemplate]
> FriendlyName="Juggernaut"
> Description="Squad size is limited to a single soldier, but advanced intel will grant this soldier the ability to react to every enemy action."
> 
> [BlackOps X2SitRepTemplate]
> FriendlyName="Black Ops"
> Description="If every visible enemy unit is killed before the XCOM turn expires, XCOM will regain concealment."
> 
> [LocationScout X2SitRepTemplate]
> FriendlyName="Location Scout"
> Description="We have advanced intel on the mission site and will be able to observe all enemy movements."
> 
> [ShowOfForce X2SitRepTemplate]
> FriendlyName="Show Of Force"
> Description="Intel suggests a large number of ADVENT troopers present, under ADVENT-only leadership."
> 
> [PsionicStorm X2SitRepTemplate]
> FriendlyName="Psionic Storm"
> Description="Energy signature at the mission site suggests high levels of Psionic enemies present."
> 
> [Savage X2SitRepTemplate]
> FriendlyName="Savage"
> Description="Intel suggests a high concentration of beast-like enemies at this mission site."
> 
> [AutomatedDefenses X2SitRepTemplate]
> FriendlyName="Automated Defenses"
> Description="Intel suggests a high concentration of robotic enemies at this mission site."
> 
> [Phalanx X2SitRepTemplate]
> FriendlyName="Phalanx"
> Description="Enemy units are gathered in a large group around the mission objective."
> 
> [Waves X2SitRepTemplate]
> FriendlyName="Waves"
> Description="Expect continual waves of enemy reinforcements until the objective is completed."
> 
> [TheLost X2SitRepTemplate]
> FriendlyName="The Lost"
> Description="The Lost are known to be present in the surrounding area. Caution advised."
> 
> [TheHorde X2SitRepTemplate]
> FriendlyName="The Horde"
> Description="ADVENT have retreated from this area, leaving only large amounts of the Lost."
> 
> [Advanced X2SitRepTemplate]
> FriendlyName="Advanced"
> Description="Reports indicate highly advanced enemies but in reduced numbers." 

For info, RealityMachina's [Restored SITREPs](https://steamcommunity.com/sharedfiles/filedetails/?id=1123082397) restores some of the disabled ones (see its Workshop page)

I think these are adjustments made to missions because of Dark Events, Resistance Orders etc. Not Sit Reps _per se_:
```
SitReps="InformationWarSitRep"
SitReps="PrivateChannelsSitRep"
SitReps="MentalFortitude"
SitReps="DarkEventBarrierSitRep"
SitReps="DarkEventDarkTowerSitRep"
SitReps="ChallengeNoReinforcements"
```

**Comment by pledbrook** [comment]
I'm slightly OK with the ones that change the makeup of the enemy pods, although I'm not a huge fan. The explosives one might be interesting as well. Low Visibility should change the way a mission plays in a meaningful way too. Others just seem gimmicky.

One option we could consider is applying positive SitReps (like Location Scout) for overinfiltration and negative SitReps for underinfiltration.

**Comment by ansabalirai** [comment]
I like the latter idea, i.e. chance based positive/negative sitreps based on level of infiltration. However, this would mean that the sitrep would be generated when the mission is launched, not when you send in a squad to infiltrate? This also raises the question of sitreps which limit squad size/composition and whether they are considered as a positive or negative sitreps?

I will create a new tab in the spreadsheet I shared for #72 for handling sitreps

**Comment by pledbrook** [comment]
My current preference is to drop sitreps that limit squad size and/or composition. I think they interfere with the current infiltration mechanics. Do they affect number of enemies too? Anyway, not interesting or fun in my view.

**Comment by SirMrMister** [comment]
The Juggernaut seems like it could be pretty fun, but potentially unbalanced in any direction, but still fun.

The ones limiting enemy composition could become more positive if you got to choose among them once you achieved overinfiltration (AKA you have time to wait until the enemy patrol is of a comosition your squad is suited to fight and then strike).

I do like all the ones involving enemy battlefield conditions.

If at the end LWR's Pods Trigger On LoS of Pod's Activation ends up not being incorporated into the final product, then that same feature could become a negative underinfiltration sitrep.

**Comment by RichardOsburnTriC** [comment]
Also the Lost are only ever spawned because of Sitreps so as they are disabled I have yet to come across any mission involving the Lost

**Comment by Jia3Huo4** [comment]
Seconded. Is it possible to have Sitreps for the Lost or at least Lost missions?

**Comment by Hound714** [comment]
The More Sitreps mod can help with testing balancing issues. It works for now, however, pledbrook is right, there are times where it can create an OP situation others (most of the time) it can create the Kobayashi Maru...

**Comment by Hound714** [comment]
Fireteam limiting sitreps are unwinnable late game (This was most of my RNG).  Shadow squad is a little OP, especially if you are deploying soldiers already with this ability.  The sitreps that focused the pod composition on a particular archetype and "waves" didn't seem to work (prob because you guys disabled the sitrep and there is a conflict somewhere).  I had alot of fun with the few missions that spawned with the lost or the horde, only issue was the turns took forever, also the normal advent spawned with this sitrep.  The explosion one was cool (only got it once), placement is random. I wish I had taken a screenshot of Phanlanx (had to reenable this sitrep), it was 45 dudes doing laps around a building, I needed 4 scorpion tanks, an orbital strike and 7 ninjas just to get through the front door.  Never got Blackops, lowprofile, or location scout. Hope this helps, I'm on a mac so I cant help much.

**Comment by Ankaridan** [comment]
I am very much in favour of applying SITREPs to over/under infiltration. I would think it simplest to apply a percentile randomness: 100-120%, x0.1 chance +sitrep, 120-140, x0.2, etc. It gives some slight incentive to say 'Hey, I can launch now, but no sitrep... or I wait another day and see if conditions improve and I get a better one?' Similarly, pushing closer to 100% to reduce or eliminate daunting SITREPs.

I like the enemy composition and battlefield variety but dislike squad size/juggernaut, and low profile. I mostly dislike Shadow Squad. I think the really interesting (+) SITREPs are the civilians and Advent Supply. Those could be expanded - rather than straight supplies, find and recruit additional resistance members? Find local informants for intel batches or reduce contact costs. An Advent mole operating inside their administration offers a Facility Lead if found.

How about: 

SITREP - a scientist VIP is being transferred via vehicle convoy and passing through the area at the same time!

SITREP: reduced mission timers due to ongoing advent air support, or evac delayed d/t inclement weather

Or even neutral ones that change the face of combat: SITREP: an ongoing advent parade/speaker address/whatever has resulted in large numbers of civilian population in the area - watch your fire!

There are grand opportunities not just to add paint jobs to a mission, but use SITREPs to expand mission objectives (optional) as bonuses. Similarly, .

**Comment by ToastedAmphibian** [comment]
'Show of Force' would make sense in late game missions in regions with low advent strength.

Showing up to break some nobodies out of prison in a region with no xcom activity to find that those 2 guys are being guarded by a 4 Muton Centurions, 3 Sectoid Commanders, 2 Archons and a Gatekeeper is a little hard to figure conceptually. Late game it's like all advent have been replaced by High ranking aliens and super robots, even in places where it makes no sense.

**Comment by pledbrook** [comment]
Initial implementation done with [this commit](https://github.com/long-war-2/lwotc/commit/8dbda18c535001de5cfbd895239f7dd96d9ece80)
