### ISSUE TITLE
Rebalance Reaper (specific changes from beta 1)

### ISSUE THREAD

**Issue by pledbrook** [long-war-2/lwotc#719]
* Use standard XCOM row abilities

Perks:

Rank | Stealth | Saboteur | Marksman
----|----|----|----
SQ |  Shadow  | Claymore | Ghostwalker
LCPL | Lone Wolf | Distraction | Bloodtrail
CPL | Target Definition (1) | Remote Start | Needle
SGT | Sting | Shrapnel | Deadeye
SSGT | Silent Killer | Highlands | Soul Harvest
TSGT | Covert | Homing Mine | Precision Shot
GSGT | Disabling Shot (2) | Hit and Run | Banish
MSGT | Shadow Rising | Serial | Annihilate

1. Target Definition effect lasts for 2 turns once unit is out of sight of Reaper (or XCOM, whichever is easier to implement)
2. Disabling Shot is a new perk that on crit, stuns target unit (for configurable number of turns). A non-crit results in disoriented. Works on any target.

**Comment by Grobobobo** [comment]
Overall pretty good, much better than the previous one, the only standouts are: 

Target Definition - Not making it permament is healthy, but makes the perk really bad.

Distraction - Worthless

Soul harvest - Barely does anything in practice, most missions are over after 4 reaper rifle kills

Annihilate - You rarely gonna care about what's gonna happen to other targets after you banish, I never cared about this perk at all

Otherwise the perk tree does offer some nice choices. LCPL is weak overall, but i guess that's fine.

**Comment by gen-martox** [comment]
Distraction isn’t bad but could be changed to give another bonus on top of going back in to shadow, something like disabling weapons, or something

**Comment by HarmlessOrange** [comment]
I think Hunter's Instinct should be removed from XCOM row for Reapers. That +2 damage on flanked enemies is ridiculous. I could clear half of the map with just one Reaper, without losing concealment.

That was Very Light mission.

**Comment by Grobobobo** [comment]
So, here are my suggestions:

- Give distraction some other bonus, (2 turn detection radius reduction on claymore kill, can throw claymore 2 tiles farther etc, disabling weapons would be a nightmare to code), 

- Replace Target Definition with Tracking from the shadow ops perk pack, with slightly reduced radius

- Swap soul harvest with shrapnel

- Since it's against banish and hit & run, disabling shot should stun on hit, maybe a longer stun duration on crit?

- Anihilate now allows banish to crit (You've gotta give it something to compete against serial and shadow rising)

**Comment by gen-martox** [comment]
Making distraction disable weapons makes more sense for the reapers and it wouldn’t be that hard to add as there is a mod already that adds that https://steamcommunity.com/sharedfiles/filedetails/?id=1453846846

I over looked hit and run the first time I looked, so they really need it? I think implacable makes more sense but meh not that big of a difference

**Comment by Grobobobo** [comment]
That disables the weapon on the claymore placement, which is lame.

**Comment by Grobobobo** [comment]
That disables the weapons on the claymore placement, which is lame.

**Comment by allenhu0912** [comment]
Annihilate allowing crits with Banish is insane, it would allow Reapers to basically carry entire lategame missions by themselves. Use Banish on the first pod you meet, re-enter Shadow and murder the second pod with double Claymores, mission is pretty much over

**Comment by Grobobobo** [comment]
In no way will 6 shots wipe a pod, especially with Muton elites, Mecs, gatekeepers and sectopods. Same with double claymores, 16 won't even kill a rocketeer.

**Comment by allenhu0912** [comment]
> In no way will 6 shots wipe a pod, especially with Muton elites, Mecs, gatekeepers and sectopods. Same with double claymores, 16 won't even kill a rocketeer.

With death dealer and stacked crit chance you absolutely can wipe rainbow pods and even football squads minus the berserkers. Centurions are not an issue and elites should probably die to two shots. You can also wipe quite a few pods with double claymores, you have to be creative though (such as going after squads with purifiers, or utilizing fall damage). Even if it's not instant squad wipe for them, a bunch of ~5 hp enemies is not too difficult to deal with as you'll still get the kill even if you roll a graze or two

**Comment by Grobobobo** [comment]
Now, where exactly will the new death dealer be on the tree?

**Comment by allenhu0912** [comment]
I see, in that case it's fine
