### ISSUE TITLE
Indirectly nerf combatives

### ISSUE THREAD

**Issue by Grobobobo** [long-war-2/lwotc#736]
Currently, combatives can completely shut down certain enemies by having your soldier put next to them. While reliable counterattacks are fine, they shouldn't shut down enemies completely.

Let's start by giving the bayonet a 3 turn cooldown, so the muton will be forced to shoot after a meele. Hive queen and berserker will need something as well, but that's for later.

**Comment by Anxoczt** [comment]
I disagree.
If it was that serious, Pavonis would have changed that way back and WOTC didnt added any new melee enemy aside from Lost who are numerous to warrant this change as if something major changed. 

Who they can shutdown is situational since they can do it only once per turn. So only one enemy can be parried... and if there is only one enemy its not like they will live to take another attack against Gunners or Shinobies.

My main problem with your proposal is that the situational where someone actually lives long enough to attack gunnner in melee more than once without getting ripped to pieces by XCOM troops is very, very rare.

**Comment by ansabalirai** [comment]
"the situational where someone actually lives long enough to attack gunnner or shinobi in melee more than once without getting ripped to pieces by XCOM troops is very, very rare"

![image](https://user-images.githubusercontent.com/15093261/68609824-3545cc80-046b-11ea-8b5e-440263808dba.png)

On a serious note, I understand the need for this change and think that changing AI behavior (even if it is as coarse as giving them a cooldown on melee) is fine.

**Comment by Grobobobo** [comment]
>If it was that serious, Pavonis would have changed that way back

I recall a pretty strong request to nerf combatives, especially coming from xwynns

>My main problem with your proposal is that the situational where someone actually lives long enough to attack gunnner or shinobi in melee more than once without getting ripped to pieces by XCOM troops is very, very rare.

The nerf won't change anything about that though, but it will help against completely shutting down a muton elite by parking your shinobi/gunner next to him.

**Comment by Ziktofel** [comment]
Don't you put your soldier under a high risk by putting him next to an enemy? If the enemy is alone, this kind of shutting him down is OK for me but you're probably winning at this situation already

In XCOM1 there was more powerful ability called Close combat specialist, even more effective at shutting down powerful enemies (See Goliath class at LW1). In LW1 I managed to make 3 muttons elites to skip their turns because of CCS threat (they moved if there were more aliens in CCS range than CCSing soldier ammo and skipped turn otherwise)

**Comment by Grobobobo** [comment]
Sometimes It is risky, a lot of times it's not.

LW1 balance is irrelevant to LW2.

**Comment by allenhu0912** [comment]
Mutons have a tendency to move forwards upon activation, so it is often perfectly fine to just park a Shinobi next to them because they will still be in cover relative to all the aliens behind the Muton.

I am personally for such a change as it encourages cheese tactics to kill mutons way before you can deal with them in any other way

**Comment by Fallguy55** [comment]
It's really not a risk to have a combatives troop next to a Muton. He can easily be behind full cover, or even hunkering down. During this, he freely and nearly fully disables a Muton. It becomes no threat at all, and you can focus your fire at other enemies. You can even use your combatives troop to fire freely, as long as they maintain the position in the muton's face. 

Mutons should be serious threats, but whenever I activate one, I'm relieved because they're so easily handled. A sectoid is more dangerous most of the time.

**Comment by HellHound989** [comment]
The amount of times I intentionally use Combatives to shut down an enemy is pretty far between them.

I essentially disagree. Its quite rare you will find a melee type unit (Muton, Lancer, Lids, etc) in such a position that allows you to run up and park your soldier with Combatives next to them while still maintaining cover to everything else. More often, the times I proc Combatives is when a Lancer or Lid runs up to my Shinobi or Gunner instead of the other way around.

Look at it this way: XCOM has many ways to fully shutdown enemy units (I especially utilize my Assault's Stun gun the most) already. This suggestion is akin to asking to nerf those abilities. Besides, Combatives can only proc once per turn. If anything needs a nerf, its Whirlwind

**Comment by Grobobobo** [comment]
merged.
