### ISSUE TITLE
Ability Points as a reward for a Flawless mission?

### ISSUE THREAD

**Issue by HarmlessOrange** [long-war-2/lwotc#741]
Currently there aren't that many ways to get XCOM Ability Points, and those that we don't give that much. Merely 1 skill per 1 Covert Action, which takes over a week of time.

So what if we were awarded 1-3 XCOM ability points for completing a mission without getting any soldiers wounded or killed?

There's already a mod that does this, so that might not be that hard to code. (however it also gives other supplies alongside XCOM Ability Points) 

https://steamcommunity.com/sharedfiles/filedetails/?id=1127174933

**Comment by HarmlessOrange** [comment]
There could be also a Resistance Order to increase that reward to 2-4 AP per flawless

**Comment by Grobobobo** [comment]
The last thing this mod needs is more positive feedback loops.

**Comment by ansabalirai** [comment]
Keep in mind that you can also use the WOTC flawless mod yourself if you so desire

**Comment by Anxoczt** [comment]
It would be great if flawless rewarded you AP, but it has to be nerfed to half so you get rewarded for doing good and maybe some month limit so you can only get X AP per month max.

**Comment by j663beast** [comment]
A more balanced way to add XCOM Ability points could be a negative feedback loop on deaths by being added to Vengeance from the Gorilla Tactics School.

**Comment by Anxoczt** [comment]
> A more balanced way to add XCOM Ability points could be a negative feedback loop on deaths by being added to Vengeance from the Gorilla Tactics School.

That would just beg to be abused to high hell. I would have no qualms of mass recruiting scrubs, send them alongside my legit troops and massacre them on purpose because 10 supplies for 4-5 AP a person killed is well worth it given what can happen with it.

**Comment by j663beast** [comment]
can be balanced by the AP given being base 1 AP with +1 AP per rank of soldier, 2 AP for 10 supplies is no longer as abuseable, especially with the Battle madness chance on death of your specialist.

Also I never get Vengeance in its current state, the supplies cost for the vengeance also needs to be included.

**Comment by Anxoczt** [comment]
> can be balanced by the AP given being base 1 AP with +1 AP per rank of soldier (i.e. 1/2/3/4/5/6/7/8/9) , 2 AP for 10 supplies is no longer as abuseable, especially with the Battle madness chance on death of your specialist.
> 
> Also I never get Vengeance in its current state, the supplies cost for the vengeance also needs to be included.
> 
> Edit or 0AP for rookies +2AP per rank (i.e. 0/2/4/6/8/10/12/14/16)

Still wouldnt solve much, you can simply produce squaddies with GTS (So its 2 AP/10 supplies) and if you have continent bonus that makes all GTS trainees sergeants (6 AP per 10 supplies) then you are back at square one, only now its slower. But it being slow isnt that much of a problem in LW2 as it would be in vanilla.

**Comment by HarmlessOrange** [comment]
I liked the idea of putting a limit on how many AP rewards you can get per month. It rewards you for doing great, but it also makes sure to not go overboard.

Maybe +1 AP per flawless with limit of 5 AP per month, with a resistance order increasing the AP per flawless and limit by 1. 

So without Resistance Order you need 5 flawless per month to reach the limit, or 3 with the Resistance Order.

I think that should be Templar's resistance order, as their orders seems to be focused on our troops.

**Comment by just-dont** [comment]
I tried playing around with Flawless mod (editing it to remove all other rewards), and I rather didn't like the sudden opportunity cost of 1 potential AP if you fail to achieve flawless rating. I think a better approach would be to not create any additional positive feedback loops (or negative ones, as they are abusable as hell).

Instead, I've tried another approach with this mod - [https://steamcommunity.com/sharedfiles/filedetails/?id=1550754061](https://steamcommunity.com/sharedfiles/filedetails/?id=1550754061), and I'm liking it way more. The whole idea goes like this:
1) Stats are buyable for AP.
2) Either the cost will increase with each purchase or there's only a limited amount of purchases per soldier, so you can't pool your AP into making superheroes.
3) Stat-boosting covert ops would be gone - I don't think they are a very useful addition as-is, since they offer a random reward (you can wait a looooong time if you want a particular stat boosted) and the UI is problematic as best - no way to indicate you don't have APs and no way to tell how much boosts this particular soldier already received.
4) You're getting a flat amount of AP every supply drop - the amount should be rather low as to not upset the balance too much. Flat rate also doesn't create any kind of feedback loops.

The mod above already makes all points except for #2 possible (so currently I'm just not buying stats more than 2 times per soldier).

**Comment by Grobobobo** [comment]
Just No.
