### ISSUE TITLE
Faceless Spawned in standard Destroy Relay mission. No faceless DE, not lib mission. 

### ISSUE THREAD

**Issue by Ledzeff** [long-war-2/lwotc#749]
[Launch.log](https://github.com/long-war-2/lwotc/files/3872642/Launch.log)

**Comment by Anthogator** [comment]
`PrePlacedEncounters[6]=(EncounterID="DKVx2_FacelessAndCivilians_LW",    EncounterZoneOffsetAlongLOP=5.0,    EncounterZoneWidth=44.0), \\` (line 265)
and similar lines in XComSchedules.ini are the relevant lines that caused this faceless to spawn. Currently faceless can spawn on alert levels 4, 5, 7, 9, 11, 12, 13, 15, 16, 17, 18, 19, 21, and 23... but _not_ alert levels 6, 8, 10, 14, 20, 22, or 24+.

So even if faceless spawning on regular guerrilla ops is intentional, they currently can not spawn on several specific and random alert levels.

**Comment by Ledzeff** [comment]
https://www.dropbox.com/s/oqj6a10sv0sdqre/save_Do%20mission%20then%20load%20counterattack%20missi?dl=0

**Comment by Ledzeff** [comment]
https://www.dropbox.com/s/o7wh5bq8nnkzjwe/save_Faceless%20bug?dl=0

**Comment by Anthogator** [comment]
See Pull Request #757

**Comment by pledbrook** [comment]
That's the Dark Event encounter. You shouldn't remove it from the schedules, otherwise there won't be any Faceless on missions when the corresponding Dark Event is active.

**Comment by pledbrook** [comment]
Which version of the mod are you using? I just tried with my dev build and there were no Faceless pods when I launched the mission. This may have been something that's already fixed. Or it could be the result of one of the other mods you're using.

**Comment by Anthogator** [comment]
So far as I can tell, this is the Dark Event encounter though.

`PrePlacedEncounters[8]=(EncounterID="DKVx2_FacelessAndCivilians_LW",    EncounterZoneOffsetAlongLOP=5.0, IncludeTacticalTag="DarkEvent_Infiltrator"), \\`

**Comment by pledbrook** [comment]
Yes, you're right. This looks like it was probably a copy-and-paste error in the original LW2 schedules. Understandable. When I tested it, I probably got one of the other schedules.

**Comment by pledbrook** [comment]
This was fixed by #767
