### ISSUE TITLE
Decrease the stun/burn chance from the sword.

### ISSUE THREAD

**Issue by Grobobobo** [long-war-2/lwotc#755]
Weirdly enough, it makes sword, a weapon that's supposed to be risky quite safe. Currently the fusion blade's chance to burn is 50%, which is frankly insane. A slash + a bladestorm hit, or combatives  counter + bladestorm is a 75% chance to set an enemy on fire, disabling it for a turn and likely killing it outright because it will die to the burn's massive damage. A combatives nerf I proposed won't do anything if a muton will be set on fire.  Considering the chances of the enemy dying outright are already super high, an additional 75% risk reduction is just too good.

There is no reason for shinobis to have that strong, free CC, so i propose removing the bonuses from 25/50% to 10/10%, so it still can happen, but will be less reliable.

**Comment by HarmlessOrange** [comment]
I agree to to that, and also I propose adding a high stun chance to vibroblade.

Because nobody uses them.

**Comment by Grobobobo** [comment]
Not sure if giving it a high stun chance is the best way to buff it, but lack of it's usage is noted.

**Comment by HarmlessOrange** [comment]
Then I'll copy-paste my suggestion from #735

> 

>     * The cheap way, after archon's autopsy, a proving ground project would appear that would bump vibro-blades damage.

> Maybe alongside bumping the damage, it could also bump the stun chance to 50% or even 66%. Currently it's 25% I think.

> Also to add to my previous suggestion, a 'Takedown' ability for gunners. It works like Fleche but instead dmg bonus it will disable enemy's weapon. One of Gunner's roles is to pin down an enemy, Takedown would help them disable key targets that are dangerous even when Suppressed.

> For balance purposes it could have a cooldown of 2 turns, and would require the Combatives perk, meaning you need to sacriface +1 damage and Grazing Fire.

**Comment by allenhu0912** [comment]
I think it's partially justified by having each individual sword require a corpse; the fusion blade in particular requires a long time to get online due to needing Archon corpses.

By the way, I think the burning damage from swords works weirdly. It does a massive amount of damage compared to flamethrower burning damage.

**Comment by ansabalirai** [comment]
While we discussed this at length in discord, just for completion's sake, I'd suggest to either remove the chances altogether or give the player a way to increase the chances to make them a little more reliable rather than just another random thing that the player cannot bank on.

An alternative would be to change the sealed armor DE to be a tactical (i.e. permanent) one instead and also apply to other variants of troopers and officers (with a percentage chance to occur), which allows the player to better know if they should rely on the burn chance or consider using a different tactic
