### ISSUE TITLE
Remove more Resistance Orders

### ISSUE THREAD

**Issue by Anthogator** [long-war-2/lwotc#756]
Attachment one, Tac Analysis, Greater Resolve, maybe more.

**Comment by HarmlessOrange** [comment]
Why?

**Comment by Anthogator** [comment]
This is a reminder for Grobobobo who mentioned on discord that he wanted a reminder to do these things.

Greater Resolve definitely should go with how infiltration works. It is causing bugs.

Tactical Analysis is VERY strong. I can see why he mentioned this one.

I assume Inside Knowledge is the attachment one he was mentioning (weapon attachment effects are increased). This is probably too strong with auto-loaders in particular. I think this one could probably stay though.

**Comment by HarmlessOrange** [comment]
I see.

**Comment by Anxoczt** [comment]
Tactical Analysis should be nerfed and reimplimented as a modifier to reflex actions so with this order aliens have a smaller chance of taking a reflex action.

**Comment by Grobobobo** [comment]
Probably, too many resistance orders have been removed, and we haven't re-added any.

**Comment by HarmlessOrange** [comment]
I could think up of some new ones but I would need a list of existing and removed Resistance Orders, as well what they did.

**Comment by Grobobobo** [comment]
Here's the list of the resistance orders: https://xcom.fandom.com/wiki/Resistance_Orders
The ones disabled because they are already GTS upgrades:

- Vengeance
- Vulture
- IntegratedWarfare
- LightningStrike
- StayWithMe

The ones disabled because they simply not work:
- BombSquad
- MunitionsExperts

The ones disabled due to imbalance/little usefulness:
- SuitUp
- VolunteerArmy
- Infiltrate (might want to reenable that one actually)
- RecruitingCenters
- LiveFireTraining
- Sabotage
- Decoys and Deceptions (was disabled back when chosen were disabled, but considering the direction with the chosen I'm planning, I don't think I want it anyway, at least now without a nerf)
- DoubleAgent
- DeeperLearningI
- DeeperLearningII
- GreaterResolve (hold up, then how did porkchop get it?)
- TrialByFire 
- MachineLearning

So yeah, quite a lot, which is decreasing the game's variety. I think resistance orders should be given some thought.

**Comment by HarmlessOrange** [comment]
Okay, thanks. I'll start working on the list of new ones.

As of now here are my thoughts on some of the disabled ones:

Why is Volunteer Army disabled? That one was a great filler. You have a chance to get an additional soldier for your squad, one that was expendable.

Is it the fact that they _are_ expendable makes that RO OP? Then how about getting one of your resistance fighters from the region? If he dies, he's removed from the haven. Now you have +1 soldier in your squad that actually brings some penalty if he dies.

...Also, I'll say that I think the resistance fighters needs a buff late-game.

Weapon-wise they're fine, despite having worse weapons by 2 tech levels. But they have 3-5 hp. Very bad late-game. How about giving them +1hp (Ablative or not) for when you research Predator Suit, and then another +1hp when you research Warden Armor? That would give them a chance to tank a shot from one of the higher-level ADVENT.

Suit up - I never actually used that thing, it’s bad as hell yeah.

Recruiting Centers - This one with bit of a rework could be nice. How about instead of lowering the cost of the recruits, it doubles the performance of personnel assigned to recruiting? So you can personel into a Haven much faster.

Live Fire Training - I think I saw that as a continent bonus. Bomb Squad and Munitions Expert too.

Sabotage - OP as it is yes. 

Greater Resolve - Completely useless, I agree.

Once I finish a list of my suggestions for new Resistance Orders I’ll open a new thread.

**Comment by Grobobobo** [comment]
> Is it the fact that they are expendable makes that RO OP? Then how about getting one of your resistance fighters from the region? If he dies, he's removed from the haven. Now you have +1 soldier in your squad that actually brings some penalty if he dies.

Yes, it is. I don't exactly know how doable ismaking the haven rebel show up instead, but It's worth considering.

Yeah, resistance orders that boost certain jobs can work quite well.

**Comment by HarmlessOrange** [comment]
List done, see #760

**Comment by pledbrook** [comment]
Deeper Learning just needs to be integrated into the LWOTC XP system.

**Comment by Grobobobo** [comment]
Tac analysis has been removed, and the resistance orders has been disabled by default for now. The rest falls under #72 .
