### ISSUE TITLE
Ideas for new and already existing Resistance Orders

### ISSUE THREAD

**Issue by HarmlessOrange** [long-war-2/lwotc#760]
**Completely new Orders:**

Psionic Prowess - Templars - Lower alien’s will by 10% (Works like the Information War, except for organic enemies)

Alpha Strike - Reapers - Increase damage by +1 and ignore 1 armor when you break concealment (Works for an entire turn after Squad Concealment was broken. Doesn’t work if your concealment was broken on the Aliens’ turn. Doesn't work on Phantom soldiers unless they broke concealment on the same turn.)

_It hurts more when they don't expect it._

Distraction - Skirmishers - The ‘Reinforcements Bucket’ fills up slower. (In-game it should be: “Reinforcements arrive slower”)

_While their numbers are endless, they can't be everywhere._

Ace Pilot - ??? - Evac arrives 1 turn faster. (Immediately if on rookie)

Guy on the Inside - Reapers - Increases the ‘Boost Infiltration’ effect by 25% (so 125% on rookie, 75% on Legend and 100% on any other difficulty)

_So I know a guy, who knows the other guy, who could get us inside pretty easily._

A Favor - Reapers - Lower the prices of Black Market by 10%

A Big Favor - Reapers - Lower the prices of Black Market by 20% (15% if it proves to be too OP)

Information Network - Skirmishers - Increase the performance of all personnel assigned to ‘Intel’ by 20% (Doubling it would be too op)

Propaganda - Skirmishers - Doubles the performance of all personnel assigned to ‘Recruit’.

Scavenger - Skirmishers - Increase the performance of all personnel assigned to ‘Supplies’ by 20%

Out of Sight, Out of Mind - Reapers - Personnel assigned to ‘Hidden’ will now help to reduce ADVENT Strength (Normally it just does nothing. Effect stacks the more resistance personnel is Hidden in the region.)

Good Intel - Skirmishers - All Intel costs are reduced. (Giving it a solid % would break a lot of shit. So how breaking it that way: Contact costs are reduced by 15%, ‘Boost Infiltration’ is reduced by 3 intel (or 5 if you want an even number), Intervention’s cost is reduced by 2 intel. Intel payment for Prevent Risk in Resistance Ring is reduced by 20%)

Quick Study - Templars - Training time in the GTS (Both of the Recruits and the Officer’s) is cut by 33%.

Rebel Threat - Reapers - Successful missions have a bigger impact on the AVATAR Project. (Successful missions slows down AVATAR Project even further.)

_The Elders are getting wary of our successes. Good._

Trails in the Sky - Templars - Reinforcements flare is visible when at 100% infiltration or above. (This Order should not exist on Rookie difficulty. If too OP then raise it to 125% infiltration.)

Diversion - Reapers - Increases Lost’s chance to target ADVENT instead XCOM. (from 30/70 to 60/40. Because Beta 2 changed the Lost targeting, to 50/50 now I propose the 90/10 ADVENT / XCOM odds when using this RO.)

_Why waste time dealing with the Lost, when we can make them ADVENT's problem._

**Ideas for rework of the existing/removed ones:**

Art of War - Templars -Flawless mission now award +2 XCOM AP (Limit is 6 AP per month.)

Volunteer Army - Move it to Skirmishers - The resistance fighters are now taken from the Haven, if they die they’re removed from the Haven of the region the mission is in. So now there’s a penalty if they die.

Sabotage - Skirmishers - 50% Chance to remove 1 additional AVATAR progress block when reducing the AVATAR progress.

Greater Resolve - Templars - Reduces the wound type by 1 level. (Gravely wounded becomes wounded, wounded becomes slightly wounded, slightly wounded are still slightly wounded.)

**Comment by Anthogator** [comment]
Guy On The Inside: On Legend, Boost Infiltration currently boosts by 50%, so this RO would increase boost's value by 50% of its total current value from 50% boost to 75% boost. Not saying that's a particular problem, just noting it.

A Favor/A Big Favor: Is it possible to have specific items with reduced costs, a la the Very Interested items that you can sell for more? If so, it might be an interesting RO to have, reducing a random item (excluding sci/eng) get reduced to 50% cost, especially since most players rarely, if ever, purchase items from the Black Market.

For all the Resistance Job orders that increase the effectiveness of rebels, I think it would be interesting if these orders nullified the Avenger scan bonus to that job, instead increasing the rebel's efficiencies. This could be very useful in many situations still, but would require a choice - if you are attempting to liberate one region in particular, especially one with low rebel counts, this may not be the right choice.

Out of Sight Out of Mind: Just a note to Grobobobo as per our previous conversation, that if this was coded, it wouldn't be hard to also have this effect for resistance drones if they got added.

Good Intel: Any reason to not just increase Intel gains, instead of reduce Intel costs? Feels less abusable - Not going to wait til the beginning of the next month to contact 3 regions because the Intel costs got way reduced by switching CAs.

Quick Study: Just a note that I think this would be better named Live Fire Exercises and should go to Skirmishers.

Noisy Opponent: Also think this one should be renamed to Diversion, primarily so it sounds like something XCOM is doing rather than something the aliens are doing.

Art of War: I'd rather see this one increase XCOM AP awards that are already granted, such as through CAs or defeating the Chosen. Alternatively, have this one grant small XCOM AP awards for some of the actions that grant them in WotC that were removed for LWotC. (Shooting a flanked opponent comes to mind as an example.)

Volunteer Army: Why move this to Skirmishers? Otherwise yes, very yes.

Sabotage: Not sure how well this one would work since AVATAR progress is supposed to be primarily tied to facilities and all such facility pips get removed when the facility is destroyed.

Greater Resolve: Is there a way to tie Will into this? Basically give a percent chance to reduce the wound type by 1 that is rolled by Will?

**Comment by HarmlessOrange** [comment]
> Guy On The Inside: On Legend, Boost Infiltration currently boosts by 50%, so this RO would increase boost's value by 50% of its total current value from 50% boost to 75% boost. Not saying that's a particular problem, just noting it.

I actually didn't know that. I never played LW on Legend... and I don't think the wiki said anything about it either. In that case it on Legend it would be 75% with the RO.

> Good Intel: Any reason to not just increase Intel gains, instead of reduce Intel costs? Feels less abusable - Not going to wait til the beginning of the next month to contact 3 regions because the Intel costs got way reduced by switching CAs.

Because Inside Job and Inside Job II are already doing this (10% and 15% increase respectively), and looking at the list of disabled RO (On #756) they're also still active. Also after a prolonged consideration all three RO could be moved to Reapers.

> Quick Study: Just a note that I think this would be better named Live Fire Exercises and should go to Skirmishers.

...I actually didn't specify whose Order that is, huh. And 'Quick Study' because in Vanilla Long War 2 (and also in LWOTC, but it seems to be useless here) there's a perk 'Quick Study' which reduced Officer and Bonus Ability training time. 

Also I think it should go with the Templar, because their Orders are primarily focused on our troops. Also Skirmishers have the majority on this list. 

> Noisy Opponent: Also think this one should be renamed to Diversion, primarily so it sounds like something XCOM is doing rather than something the aliens are doing.

I was struggling to find a good name for that, thanks.

> Art of War: I'd rather see this one increase XCOM AP awards that are already granted, such as through CAs or defeating the Chosen. Alternatively, have this one grant small XCOM AP awards for some of the actions that grant them in WotC that were removed for LWotC. (Shooting a flanked opponent comes to mind as an example.)

I don't think increasing CAs or Chosen's AP reward is a good idea, it's too weak on its own. However re-enabling AP rewards for Height Advantage Shots or Ambush kill _is_ a good alternative.

> Volunteer Army: Why move this to Skirmishers? Otherwise yes, very yes.

My thought process was that Skirmishers are more focused on either supporting our infrastructure or hindering ADVENT (They have Orders like faster excavation and building, or Lowering their Tech score and getting that -1 Ability Point upon the reveal.)

Reapers meanwhile are more focused on gathering the resources and getting advantages while in concealment (Popular support and Infiltrate for example). To me Volunteer Army fitted Skirmishers more.

 > Sabotage: Not sure how well this one would work since AVATAR progress is supposed to be primarily tied to facilities and all such facility pips get removed when the facility is destroyed.

If it's possible it could remove 1 pip of progress from the Water Base every time you do a mission on Golden Path or destroy an AVATAR facility.

**Comment by HarmlessOrange** [comment]
EDIT: Added flavor text to some of the Resistance Orders.

Today I had a rather boring shift, which allowed me to think of few more things. 

Completely new ones:
Good Morale - Templars - Soldiers’ combat stats are slightly improved. (+ 8% Aim, + 8% Crit, + 10% Hack + 10 Will, +1 Mobility.)

_When the morale is high, our soldiers fight better._

Harsh Training - Skirmishers - Resistance Fighters’ combat stats are vastly improved. (+15% Aim, + 10% Crit, + 20% Will + 2 Mobility, +2 Health. They have squaddie/rookie level of aim so we can get away with bigger boost to stats.)

_These people will need a lot of training if they want to stand up against the aliens._

Better Equipment - Skirmishers - Resistance Fighters’ weapon tech is improved by 1 level. (In other words they’re now 1 level behind XCOM tech. If XCOM have Magnetic, they’ll have lasers. If XCOM has Plasma, they’ll have Coilguns.)

Existing ones:

Double Agent - No more Hidden Dark Evenets, and you can see in which region there’s a DE mission. (So you know where to scan to counteract that event. 

Two ways I can see it done: 1) Lit up the region on the map with red color, which I have no idea if it's even possible. However this is a bit more balanced as in case of multiple Dark Events you won’t know which DE is in which region.

2) Add a small info: ‘Located in: [REGION NAME]‘ when clicking on the Dark Event. Probably an easier one to code, but that would make that RO a bit more OP.)

Popular Support - Reapers - Is there someone who uses both of these at once? I’m not going to waste 2 RO slots for mere 25% more supplies. Remove Popular Support I and rename the whole thing (I’m thinking ‘All In’ is a nice name), I have something that I think is better suited for ‘Popular Support’.

NEW Popular Support - Reapers - Civilians don’t yell, nor they’ll reveal our squad. (So now it’s a bit easier and safer to move around. Especially when jumping from the edges.)

**Comment by Grobobobo** [comment]
Resistance orders will not be supported.
