### ISSUE TITLE
Intel Mini-Retals and Protect The Device missions: Pods don't beeline objective.

### ISSUE THREAD

**Issue by Clibanarius** [long-war-2/lwotc#761]
Okay, this is a weird one to prove unless you run LW2 next to LWotC, but: In LW2, there's ALWAYS a pod of enemies that are set to beeline the objective in Protect The Device missions, which encompass Intel Mini-Retals. In LWotC, they simply don't. They don't patrol, they don't move from their starting position, they just chill. It gives your Resistance Worker and Haven Advisor team faaaaaaaaaaar too much lee-way in how they behave. They can sit at spawn with the device for 10, 20 turns and they'll never be harassed. Should be that it's one or two turns max before the pod finds them and activate. Hopefully this behavior has been noticed by someone else.

**Comment by Clibanarius** [comment]
Spoke too soon. Apparently reloading my game caused them to start functioning properly again. Odd, that one.

**Comment by Anxoczt** [comment]
This is odd since my enemies always go for the objective and i am happy that i managed to get to the data tap first before something starts to shoot it and my rebels are in range of getting killed instantly by the first AoE attack. But this is quite map dependant. If Advent troops have to make their way through many obstacles it might take a while before they get in to LoS of the data tap.
