### ISSUE TITLE
Avatar countdown timer not stopping after completing psionic gate mission

### ISSUE THREAD

**Issue by PatrickWinekiller** [long-war-2/lwotc#824]
After finally liberating my first region, we learn of the avatar project THAT IS ALREADY TICKING OMG! So I send my best mates to get that psi gate golden path mission that reduces avatar progress by 3 pips right? It was a good plan, but nope, upon completing the psionic gate mission the countdown (which was down to 3 days) was still ticking. It is worth noting that a) I did have the dark event that causes the aliens to make a breakthrough in "an unknown project" and b) I've reduced campaign difficulty mid-way and disabled grim-horizon (yes, I was suicidal back in the day).

See attached saved-game.
[save_p panic.zip](https://github.com/long-war-2/lwotc/files/3995241/save_p.panic.zip)

**Comment by jmartinez989** [comment]
So I know what is going on here but forgot to report this a while back.

So if you wait a very long time to liberate your first mission the avatar project can get to 20 blocks before you even liberate. the thing is it can go past that amount so that when you do finally reveal it it can look like you have only 20 blocks since the countdown is running but behind the scenes you actually have something like 25 blocks of avatar project progress. This would make it so that even though you clear a mission that reduces avatar project progress if it only reduces something like 3 blocks of avatar but you have 25 then you are still left with 22 which means you are still at 20 or more so the doom timer does not go away.

This also causes another bug that makes it so that the avatar project doom timer does not count down until you reveal the avatar project which means you could technically keep playing the game indefinitely without fear of the timer until liberating a region. In LW2 you could lose the game to the avatar project doom timer reaching zero before you even liberate a region (which has happened to me in LW2).

**Comment by Grobobobo** [comment]
So the way to go would be to enable the avatar countdown even when it's not revealed. I wonder what is it caused by.

**Comment by PatrickWinekiller** [comment]
That explains why exploding a 5 pip factory ALSO did not stop the timer.  Perhaps adding a limit would suffice?

**Comment by wdanny69** [comment]
this has been worked around by auto revealing the avatar once 2 progress has been made instead of requiring liberation

https://github.com/long-war-2/lwotc/commit/e9061dc26294d9ba7418f9d1207cd1657022a0ce
