### ISSUE TITLE
Bug: Intel retaliations crash to desktop as soon as you launch the mission

### ISSUE THREAD

**Issue by jmartinez989** [long-war-2/lwotc#83]
[intelretal.zip](https://github.com/long-war-2/lwotc/files/3070720/intelretal.zip)

Looks like the retaliations generated from intel gathering  are crashing to desktop right away.

I wonder if this has anything to do with the game trying to get Chosen in it. I know that the first retaliation is when the chosen usually show up.  I have attached the save file.

This happens even if I only have LWotC mod active and all other mods off.

**Comment by ansabalirai** [comment]
Do you know if this was a mini intel retal or a full haven retaliation? From your description, it seems the latter.

BTW, I think the former doesn't really have an equivalent in WOTC

**Comment by jmartinez989** [comment]
Its the one that triggers when an area is at Advent Strength of 3 and you have most of all of your resistance rebels assigned to intel. The one where you have to rescue them while they guard the data tap.

**Comment by ansabalirai** [comment]
Hmmm, so the mini inte retal. That is a blocking issue since they are a lot more frequent and an integral part of haven management. I did not have a retal in my playthrough at all, so it is good to know that the mission is at least generated at the strat layer.
I wonder if the fact that LW2 had pods deploy on yellow alert from turn 0 could have anything to do with this?

**Comment by jmartinez989** [comment]
Just had this happen on a standard retaliation. The mission just states to stop the advent retaliation. It looks like at this point no retaliations will start up with LWotC.  Included the save file with issue.
[regularretal.zip](https://github.com/long-war-2/lwotc/files/3071332/regularretal.zip)

**Comment by pledbrook** [comment]
Both missions have proxy rebel units, just like Jailbreak, so I'm wondering if you're running into the same issue. However, this time the crashes are reproducible from the save files. I'm just not sure if that's because there's some iffy state in them due to other issues.

I'll see if I can reproduce another way. I tested this missions successfully before, but I used a debug command to force the missions. I'll try an alternative approach.

In the mean time, you may want to back up your personal XCOM 2 Config directory and then delete its contents before running LW2 again. Also, consider moving _Documents\My Games\XCOM2 War of the Chosen\XComGame\SaveData\profile.bin_ to a safe directory somewhere else. I have known that file to cause issues.

**Comment by pledbrook** [comment]
OK, this is reproducible. Will look into it. Not sure whether I can get it into the alpha 2.

**Comment by pledbrook** [comment]
I'm afraid this one has me stumped, so there's a good chance a fix won't make it into alpha-2, sorry. It really is a blocker, too 😢

**Comment by jmartinez989** [comment]
> I'm afraid this one has me stumped, so there's a good chance a fix won't make it into alpha-2, sorry. It really is a blocker, too

This is actually ok. Even though it is a blocker it is still playable. It actually gives you a chance to learn how to play when getting set back by retaliations you cannot stop anyway. I think it is ok if this one does not make it to alpha 2. I think there are bigger issues that need to be addressed first. Would def be interested in finding out what exactly is causing it though.

In the meantime I'll keep progressing through the campaign and report anything else.

**Comment by pledbrook** [comment]
The problem has been identified and it had nothing to do with the missions other than they are instant launch (as opposed to infiltration). Testing a fix now.

**Comment by pledbrook** [comment]
Interestingly, this has uncovered another bug. If you try to abort an infiltration and then press return on the popup screen that appears when the Skyranger arrives at the infiltration site, you'll actually start the mission!

**Comment by jmartinez989** [comment]
Lol that is an interesting bug.
