### ISSUE TITLE
Network Tower Hack breaks Squad Concealment (and shouldn't)

### ISSUE THREAD

**Issue by DerAva** [long-war-2/lwotc#830]
In LW2 1.5 (and all previous versions) a Shinobi hacking the regional network tower would remain concealed (and so the squad also remains concealed, if it still is) after completing the network tower hack. 
In the current version this hack breaks concealment.

For comparison: LW2 1.5 hack: https://youtu.be/rCh9BewZ7R4?t=16m43s
LWotC tower hack: https://youtu.be/Qh72bBOKPgg?t=14m45s

**Comment by pledbrook** [comment]
This is behaviour that's new to WOTC and affects *all* missions with a hack objective. I actually prefer the new behaviour as it introduces an added challenge to pure-stealth hack missions. I can be persuaded otherwise if the argument for reverting this behaviour is good, but it won't go into beta 3.

**Comment by pledbrook** [comment]
Leaving as WOTC behaviour
