### ISSUE TITLE
Can't extract from zip file

### ISSUE THREAD

**Issue by Zaramnor** [long-war-2/lwotc#86]
Hi, I downloaded LongWar2_WOTC-1.6-alpha-1.zip (2,127,003,337 Bytes) and extracted everything, besides 

LongWarOfTheChosen.XComMod and
ModPreview.jpg

files. I can see them in the zip file, but can't open or extract them.

**Comment by pledbrook** [comment]
Yes, sorry. The compression is BZip2, which Windows can't seem to handle. I was caught out by Windows happily opening the archive. I don't know why it doesn't like those two files.

Anyway, I think there's another issue for this somewhere. I'll find the link, which explains what to put in that `.XComMod` file.

**Comment by pledbrook** [comment]
For the time being, you can either use 7zip to unpack the archive or simply create the `LongWarOfTheChosen.XComMod` file where you unpacked the rest of the archive and set its content to:
```
[mod]
publishedFileId=0
Title=Long War 2 [WOTC]
Description=Long War 2 overhaul mod for War of the Chosen     
RequiresXPACK=true
```
Alternatively, I'm hoping to get an alpha-2 out tomorrow and I'll be sure to use normal compression for that. You should probably wait for that release anyway because it has a bunch of important fixes.

**Comment by Zaramnor** [comment]
I created the file manually with the contend mentioned above - worked. Thx
