### ISSUE TITLE
Suggestion: smoke rocket breaker

### ISSUE THREAD

**Issue by daruperez** [long-war-2/lwotc#917]
Hi,
Wouldn't the smoke have to protect the launcher?

it must not protect the enemy ... or the smoke must be eliminated

**Comment by Anxoczt** [comment]
Uh
Its hard to decypher what you are saying, would you like that rocket launcher creates smoke on Technical's position like a perk for flamethrower ? Or do you want the concussive rocket to have its smoke removed ?.

Concussive rocket, what i discovered is suppose to be "I dont wana deal with this group yet" weapon, that you launch to mass stun or disorient targets. The smoke is its drawback since a AoE stun/mass disorientation would be quite overpowered on its own.

**Comment by daruperez** [comment]
Hi,
"...would you like that rocket launcher creates smoke on Technical's position like a perk for flamethrower?": Yes

"...The smoke is its drawback since a AoE stun/mass disorientation would be quite overpowered on its own": some enemies do not suffer it ..., and they have the benefit of smoke ..., painful for your troops

**Comment by Grobobobo** [comment]
@ChrisTheThinMint will likely implement those changes on his own.

**Comment by Grobobobo** [comment]
The concussion rocket has recieved a different change.
