### ISSUE TITLE
Kill Zone does not trigger

### ISSUE THREAD

**Issue by xauier** [long-war-2/lwotc#919]
Kill zone skill (Gunner) does not trigger at any action. I guess someone need to take a look there.
In may case, enemies without and special abilities (lightning reflexes / shadowstep) are dancing around within the zone and the gunner is kind of sleeping :(

**Comment by McTrevor79** [comment]
Kill Zone is rather difficult to set up. The enemies need to move at least two tiles inside the zone in sight of the gunner. So enemies at the edge of it moving out of it do not trigger a reaction shot. Also it works better for enemies that are rather far away because close to the gunner the killzone is very narrow.

**Comment by Grobobobo** [comment]
Current Kill Zone trigger works as intended.
