### ISSUE TITLE
Some ability icons are blacked out

### ISSUE THREAD

**Issue by ionbomb** [long-war-2/lwotc#93]
Playing alpha 2.
Mods: Yet another F1, Evac All, Free Camera Rotation

Some ability icons are blacked out, on all soldiers. Seems to be Frag & Flashbang grenades, as well as "Reload". 

Image: ![20190415002717_1](https://user-images.githubusercontent.com/49572327/56100889-4e5abf00-5f16-11e9-9e15-d2bd92b7675e.jpg)

**Comment by ansabalirai** [comment]
I had this issue as well. Steps I did which fixed this for me:

- Download the highlander and the LWOTC mod separately and extract them in the Mods folder. Basically, you should have two folders in there.
- Assuming alternative mod launcher is being used, try to delete and reinstall(extract) it again. Since I was using it to play both vanilla/LW2 and WOTC alternatively, some mods were showing as duplicates there for some reason, even when pointing to different directories.
- Clear the config folder (this is just good practice)

YMMV

**Comment by pledbrook** [comment]
See my comment [on the promotion issue](https://github.com/long-war-2/lwotc/issues/92#issuecomment-483123121).

**Comment by ionbomb** [comment]
See my comment [on the promotion issue](https://github.com/long-war-2/lwotc/issues/92#issuecomment-483339822). 

This has resolved the problem for me.
