### ISSUE TITLE
[Beta3] Soldiers returning from CAs not getting promoted after hitting the xp threshold

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#978]
As described in discord, it seems that sometimes undertaking a CA which gives you a few points of XP and pushes you above the threshold doesn't actually result in a promotion. In the save attached, the gunner on the ongoing CA is already above the next promotion threshold but has not promoted.
[XPThresholdBug.zip](https://github.com/long-war-2/lwotc/files/4579814/XPThresholdBug.zip)

**Comment by pledbrook** [comment]
This is just how vanilla works. It's confusing, but at the end of normal missions, each squad member has a `bRankedUp` flag cleared. If they then have enough XP to be promoted, they're ranked up and the flag is set to `true`.

Covert actions never clear this flag, so they can't promote soldiers if they haven't gone on a normal mission since they last ranked up. This is understandable as they want to throttle promotions based on missions, although I honestly think this is an oversight.

Not sure what to do. Could try to make covert actions clear the flag. It's not like you can rack up huge amounts of XP on missions or covert actions to give you multiple rank ups.

**Comment by copyrite** [comment]
Closing, known base game bug https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/1063
