### ISSUE TITLE
Flamethrower range is increased from LW2

### ISSUE THREAD

**Issue by ansabalirai** [long-war-2/lwotc#98]
As mentioned in discord, the range of the flamethrower is increased from 7 to 8 tiles. This can be quite potent for concealment ambushes, especially early game.
https://gfycat.com/LiquidBlushingDotterel
So, we need to discuss if this ok from a balance point of view.

**Comment by TheSwingman** [comment]
Eh, I always thought the flamethrower range was perfectly fine in my eyes. Technicals are super strong and what balances them out is their short range, at least with regards to the fireman tree. 

Something better to look at would be fixing the issue with leaning out of cover to burn things; more often than not you would move your technical into a position, thinking that you had a good flamethrower play, only to find that the flamethrower would not hit the enemy that was right in front of you because of wonky lean/targeting mechanics. That's something that I'd look at fixing before giving the flamethrower more range. Just my two cents.

**Comment by ansabalirai** [comment]
I think you misunderstood my comment. I am proposing to reduce the range from 8 to 7 as in vanilla LW2. The targeting bug has always been there and I have personally learnt to live with that. If it can be fixed, great. If not, meh. Not a big deal for me

**Comment by ansabalirai** [comment]
I am actually proposing to reduce the range, for exactly the reasons you mentioned (i.e. from 8 back to 7 tiles). Regarding the targeting issue, it has kinda always been there and I personally have learnt to live with it. If you trust yourself, you can use ttc, so not that big a deal for me

**Comment by pledbrook** [comment]
I don't know if the values are different from LW2. It could just be the way that vanilla and LW2 flamethrowers interpret those numbers. Anyway, look in `XComLW_SoldierSkills.ini` for `FLAMETHROWER_TILE_LENGTH`.

Note that this mod is currently using the vanilla flamethrower because of the bug in the custom LW2 one. Also, the vanilla one is implemented in native code, so is less laggy. However, vanilla flamethrower doesn't support step out (LW2 did support it) and it doesn't hit units behind high cover.

**Comment by yoshimo** [comment]
I would say it is ok to miss people behind high cover.

**Comment by SirMrMister** [comment]
Compromise to grazing people behind high cover?

**Comment by yoshimo** [comment]
maybe burn the cover down depending of material in addition but grazing seems ok.

**Comment by TheSwingman** [comment]
Hmmm. 

There's two paths in my eyes: 

1. Keep the standard LW2 system with flamethrower targeting, since the player can generally predict whether or not your flamethrower will not hit a target that you are standing next to; starting range starts at 7 tiles. 

2. If you revert to the vanilla system that does not hit targets in full cover, it may be prudent to increase the range due to the loss of power in that regard. Bumping it up to a starting 8 tiles, that can be increased to 9 with the respective perk in the tree would compensate for that loss of power, potentially.

**Comment by SirMrMister** [comment]
I say differentiaye two cases of full cover: those who can sidestep out of cover (or into halfcover) and those who can’t (either because there is full or halfcover to their side or because the square next to them is also high cover).

The first would get grazed as the flames do go around corners a bit, but the second wouldn’t because flames do not got through walls like ghosts. Maybe a way to more easily implement this would be visibility checks - if target is in full cover and it or its tile is in sight of the flamethrower wielder (accountinf for sodestepping both ways), then graze. If target is in full cover but its tile wouldn’t be visible when accounting sidestepping, no damage.

Actually, you could forgo the cover aspect of the second check completely, so that full cover protects a bit beyond it, casting a shadow fro:the flames: if a flamethrower target’s tile would not be visible by the flamethrower unit (accounting for sidestepping), then no damage at all. It would admittely create cases where a tree blocks a little cone of tiles behind it, but the tile the tree provides cover for would suffer graze, and it would allow for solid walls to completely block the flamethrower.

**Comment by pledbrook** [comment]
We really can't do much with the flamethrower targeting without overriding the vanilla implementation. And I just don't think that's worth the effort and performance penalty.

On a positive note, I discovered that if you are between flanking and 45º to the enemy, the flamethrower will hit them behind high cover. I can live with that and it makes sense.

**Comment by TheSwingman** [comment]
> We really can't do much with the flamethrower targeting without overriding the vanilla implementation. And I just don't think that's worth the effort and performance penalty.
> 
> On a positive note, I discovered that if you are between flanking and 45º to the enemy, the flamethrower will hit them behind high cover. I can live with that and it makes sense.


That's acceptable for me as well. 
The focus definitely needs to be about getting the mod to a playable state. Maybe we could revisit this later for a balancing pass.

**Comment by ansabalirai** [comment]
I am not sure I understand what grazing means when it comes to flamethrower. Does it imply hitting the enemy but not the tile? I don't think the graze band as applied to guns is applicable.

**Comment by SirMrMister** [comment]
> I am not sure I understand what grazing means when it comes to flamethrower. Does it imply hitting the enemy but not the tile? I don't think the graze band as applied to guns is applicable.

By grazing I just meant doing partial damage, like in XCOM:EW.

**Comment by pledbrook** [comment]
OK, so going back to the original issue, I probably just set the numbers incorrectly. LW2 didn't have a simple tile length config option, so I think I guessed.

Solution: reduce tile length to 7 in `XComLW_SoldierSkills.ini`. This can be tested with existing installations.

**Comment by pledbrook** [comment]
Is the cone "width" OK? I think it's currently 5 tiles.

**Comment by Ronar1** [comment]
As someone who has beaten LW2 L/I and even liberated all regions, I must say flamethrowers are bonkers broken and not being able to go through full cover is fine. It would probably be fine to keep the burn distance at the original levels also.

**Comment by TheSwingman** [comment]
> As someone who has beaten LW2 L/I and even liberated all regions, I must say flamethrowers are bonkers broken and not being able to go through full cover is fine. It would probably be fine to keep the burn distance at the original levels also.

I mean, I've beaten LW2 L/Bronzeman, and while I'd agree with the sentiment that flamethrowers are powerful, I'm not sure I'd say that they are "bonkers broken" because from my understanding of the philosophy of alien units and XCOM units, everything is supposed to be powerful. 

You have tons of tools at your disposal, but so does the enemy, and any downgrade in the ability of the units at your disposal starts to really hamper the balance of the game as a whole.

**Comment by pledbrook** [comment]
One thing I would like to restore if possible is step out. Not being able to step out to use the flamethrower is so unintuitive and makes it very hard to use.

**Comment by Ronar1** [comment]
The thing about abilities that just require a point and click is that it breaks the integrity of the game mechanics. What I mean is that XCOM is a game mainly about percentage chances to hit as well as positioning. Even grenades are subjected to an RNG damage value of 1-5 because they understood the importance of this. Anything that bypasses RNG should be subjected to heavy positioning. The flamethrower has some RNG tied to it, but with napalm x its basically a point and click super AOE. Its pretty hard to lose engagements especially if a unit can do that from a very lax position. Being forced to try and position around enemies in full cover was probably one of the more fair things to happen to this class. If anything, being able to hunker down to put out fire should be restored too.

**Comment by TheSwingman** [comment]
> The thing about abilities that just require a point and click is that it breaks the integrity of the game mechanics. What I mean is that XCOM is a game mainly about percentage chances to hit as well as positioning. Even grenades are subjected to an RNG damage value of 1-5 because they understood the importance of this. Anything that bypasses RNG should be subjected to heavy positioning. The flamethrower has some RNG tied to it, but with napalm x its basically a point and click super AOE. Its pretty hard to lose engagements especially if a unit can do that from a very lax position. Being forced to try and position around enemies in full cover was probably one of the more fair things to happen to this class. If anything, being able to hunker down to put out fire should be restored too.

I disagree that point and click abilities break the integrity of the game when you consider that the aliens are powerful as well. 

Napalm-X is powerful but it still isn't guaranteed, and you still are subjected to resource management. 
XCOM for me has always been about mitigating misses and risk. A good team always has ways to mitigate mistakes, but you only have so many resources, so you don't always press the "please die/panic/blow up" button if something happens because the reality is you might need it later on, especially on those long missions. You weigh those choices and that's why I really enjoyed LW2 for its moments of, PUSH FORWARD! WE NEED TO GET TO THE OBJECTIVE! and you have a Overwatch Ranger and Overwatch Specialist pushing forward with Ever Vigilant and the rest of the team dealing with specific targets that needed to be dealt with, and you have a turn where the team is attacking the aliens and being proactive. 

And let's be real here, there aren't that many abilities in the game that require a point and click. Flamethrowers are like that because they provide a valid alternative to just loading out your Technicals with Rockets and going to town, albeit with shorter range.

**Comment by pledbrook** [comment]
Fixed
