### ISSUE TITLE
Cannot act but can move after stunning with arc thrower

### ISSUE THREAD

**Issue by MagSigeasol** [long-war-2/lwotc#99]
A unit was mind controlled, so I stunned it with the assault's arc thrower.

When it 'recovered', it was locked in a stun state (abilities unavailable) but it could move.

Thus, could not evac the soldier - see saved game:

[save_Stun bug - cannot evac.zip](https://github.com/long-war-2/lwotc/files/3083117/save_Stun.bug.-.cannot.evac.zip)

**Comment by MagSigeasol** [comment]
Having googled around, this seems to be a vanilla bug that has not been resolved. Not sure if this was ever an issue in WotC and for some reason LW2 has brought it back.

**Comment by pledbrook** [comment]
Well, I can certainly look into it. It might be something that could be fixed in the highlander.

**Comment by torma** [comment]
Seems to also affect enemy units.
It also looks like the  stun debuff is not shown for the unit.
I tried to recreate the turn where the unit got stunned but it played out differently.
I added a new file because this one contains files from before and after stunning the unit.
Save Files at:
https://drive.google.com/file/d/11W0so7ZzhBzGNZcSxaQboMnOkcBBW6GN/view?usp=sharing

Mod list (only listing additional mods):
[WOTC] New Target Icons
WOTC - Extended information
Evac All - WOTC
[WOTC] Additional Icons
[WOTC + Classic] Tacticalui Killcounter
Yet Another F1

**Comment by TyborPL** [comment]
Can conform all of this. Friendly or enemy units stunned with arc thrower are stunned forever. Pretty powerful exploit IMO.

**Comment by pledbrook** [comment]
Does this only happen if the stunner has Electroshock?

**Comment by TyborPL** [comment]
> Does this only happen if the stunner has Electroshock?

No. Here is a save where stunned officer teleports around. My assault only has lightning reflexes.
[save_IRONMAN- Campaign 57.zip](https://github.com/long-war-2/lwotc/files/3526843/save_IRONMAN-.Campaign.57.zip)

**Comment by pledbrook** [comment]
Yes, sorry, this has already been fixed. It had nothing to do with other abilities/effects.
