### ISSUE TITLE
Archon King's overreaction

### ISSUE THREAD

**Issue by Savancosinus** [long-war-2/lwotc#996]
Hi,
Don't know if it's intended, but I'm facing the Archon King, and he takes an action each time I target him (instead of 25% of the time). He's the first (and the only one) king I've meet, and it happened during an HQ's assault.
I could send you my save files, but they're in french. :/
Version (LWotC) - "lwotc-dev-0015 (HighLander v1.2)"
Mods - Required mods, + HackPlus (WotC).

**Comment by pledbrook** [comment]
Early testers wanted the behaviour reverted to WOTC from the old LW2 setup. Perhaps if folks are struggling too much with them, we can go back to the LW2 approach.

**Comment by Savancosinus** [comment]
I see... Hope there's a boolean I can change to reverse his behaviour. :)

The fight wasn't challenging, it was unfair. I reloaded countless times. 
During the mission, he killed most of my soldiers, and I coludn't fight back, he just put too much pressure.
Also, he wasn't the last enemy on the map, I've to fight 2 pods (with 2 mutons elites in one of them) after that. That's too much, and i only played at medium difficulty. :/

**Comment by Savancosinus** [comment]
Maybe is it possible to set the following variable to "100".
ALIEN_RULER_ACTION_BONUS_APPLY_CHANCE=
Everyone would be happy in this case. :)

**Comment by ansabalirai** [comment]
I second this suggestion. I know sitreps allow you to be a bit more proactive when coming across the rulers, but it would be nice to get away from just having a single hard counter aka frost bomb being essential to deal with them (in before the few beta strikers on discord object...)
At the very least, i agree that restoring the ruler reaction chance to percentage based and setting it to 100% default can be a compromise. At least for me, that removes a mod from my game.

**Comment by bobjjones** [comment]
Fighting viper king now, having the same problem. The frost bomb is not a hard counter. It barely gives you two actions before he is all over you again. I think this scenario is unwinnable. He is just moving too often. I never liked the rulers having actions after every action. This gives him a number of actions per round proportional to the number of soldiers on the mission. Giving them extra actions is fine, and it makes sense to interrupt the players turn so that they don't have 5 actions on their turn like the chosen do, but right now, the ruler has 2 plus 2 times the number of soldiers actions, which is ridiculous.

**Comment by bobjjones** [comment]
Well, I managed to drive him off by summoning the lost while he was frozen and letting him waste his actions on them. My thinking here is that acting after each soldier,s turn 8s ok, but acting after every action is a bit much. Perhaps you just give alien rulers the battle lord ability. I don't have anyone ranked high enough to have it yet, but its description seems to match the behavior I am describing.

**Comment by Grobobobo** [comment]
Balanced by making the alien rulers appear later on.
